// This file has been generated by beamsplitter

#include <gltfio/FilamentAsset.h>
#include <filament/Box.h>
#include <utils/Entity.h>

#include <jni.h>

#include <string>

// Copies filament::Aabb to and from its Java counterpart, member by member.
static filament::Aabb readAabb_generated(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::Aabb out;
    {
        jfloatArray a = (jfloatArray) env->GetObjectField(obj, env->GetFieldID(cls, "min", "[F"));
        jfloat* p = env->GetFloatArrayElements(a, nullptr);
        out.min = *reinterpret_cast<filament::math::details::TVec3<float>*>(p);
        env->ReleaseFloatArrayElements(a, p, JNI_ABORT);
    }
    {
        jfloatArray a = (jfloatArray) env->GetObjectField(obj, env->GetFieldID(cls, "max", "[F"));
        jfloat* p = env->GetFloatArrayElements(a, nullptr);
        out.max = *reinterpret_cast<filament::math::details::TVec3<float>*>(p);
        env->ReleaseFloatArrayElements(a, p, JNI_ABORT);
    }
    return out;
}

static jobject writeAabb_generated(JNIEnv* env, const filament::Aabb& in) {
    jclass cls = env->FindClass("com/google/android/filament/Aabb_generated");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    {
        jfloatArray a = env->NewFloatArray(3);
        env->SetFloatArrayRegion(a, 0, 3, reinterpret_cast<const jfloat*>(&in.min));
        env->SetObjectField(obj, env->GetFieldID(cls, "min", "[F"), a);
    }
    {
        jfloatArray a = env->NewFloatArray(3);
        env->SetFloatArrayRegion(a, 0, 3, reinterpret_cast<const jfloat*>(&in.max));
        env->SetObjectField(obj, env->GetFieldID(cls, "max", "[F"), a);
    }
    return obj;
}


extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetEntities(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getEntities();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetEntityCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getEntityCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetLightEntities(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getLightEntities();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetLightEntityCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getLightEntityCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetRenderableEntities(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getRenderableEntities();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetRenderableEntityCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getRenderableEntityCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetCameraEntities(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getCameraEntities();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetCameraEntityCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getCameraEntityCount();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetRoot(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) utils::Entity::smuggle(((filament::gltfio::FilamentAsset*) nativeObject)->getRoot());
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nPopRenderable(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) utils::Entity::smuggle(((filament::gltfio::FilamentAsset*) nativeObject)->popRenderable());
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nPopRenderables(JNIEnv* env, jclass, jlong nativeObject, jlong entities, jlong count) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->popRenderables((utils::Entity*) entities, count);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetResourceUriCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getResourceUriCount();
}

extern "C" JNIEXPORT jobject JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetBoundingBox(JNIEnv* env, jclass, jlong nativeObject) {
    return writeAabb_generated(env, ((filament::gltfio::FilamentAsset*) nativeObject)->getBoundingBox());
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetName(JNIEnv* env, jclass, jlong nativeObject, jint arg0) {
    return env->NewStringUTF(((filament::gltfio::FilamentAsset*) nativeObject)->getName(utils::Entity::import(arg0)));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetFirstEntityByName(JNIEnv* env, jclass, jlong nativeObject, jstring name) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jint result = (jint) utils::Entity::smuggle(((filament::gltfio::FilamentAsset*) nativeObject)->getFirstEntityByName(name_));
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetEntitiesByName(JNIEnv* env, jclass, jlong nativeObject, jstring name, jlong entities, jlong maxCount) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jlong result = (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getEntitiesByName(name_, (utils::Entity*) entities, maxCount);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetEntitiesByPrefix(JNIEnv* env, jclass, jlong nativeObject, jstring prefix, jlong entities, jlong maxCount) {
    const char* prefix_ = env->GetStringUTFChars(prefix, nullptr);
    jlong result = (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getEntitiesByPrefix(prefix_, (utils::Entity*) entities, maxCount);
    env->ReleaseStringUTFChars(prefix, prefix_);
    return result;
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetExtras(JNIEnv* env, jclass, jlong nativeObject, jint entity) {
    return env->NewStringUTF(((filament::gltfio::FilamentAsset*) nativeObject)->getExtras(utils::Entity::import(entity)));
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetMorphTargetNameAt(JNIEnv* env, jclass, jlong nativeObject, jint entity, jlong targetIndex) {
    return env->NewStringUTF(((filament::gltfio::FilamentAsset*) nativeObject)->getMorphTargetNameAt(utils::Entity::import(entity), targetIndex));
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetMorphTargetCountAt(JNIEnv* env, jclass, jlong nativeObject, jint entity) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getMorphTargetCountAt(utils::Entity::import(entity));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetWireframe(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) utils::Entity::smuggle(((filament::gltfio::FilamentAsset*) nativeObject)->getWireframe());
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetEngine(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getEngine();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nReleaseSourceData(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::gltfio::FilamentAsset*) nativeObject)->releaseSourceData();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetSceneCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getSceneCount();
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetSceneName(JNIEnv* env, jclass, jlong nativeObject, jlong sceneIndex) {
    return env->NewStringUTF(((filament::gltfio::FilamentAsset*) nativeObject)->getSceneName(sceneIndex));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nDetachFilamentComponents(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::gltfio::FilamentAsset*) nativeObject)->detachFilamentComponents();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nAreFilamentComponentsDetached(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::gltfio::FilamentAsset*) nativeObject)->areFilamentComponentsDetached();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetInstance(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getInstance();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_gltfio_FilamentAsset_1generated_nGetAssetInstanceCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::gltfio::FilamentAsset*) nativeObject)->getAssetInstanceCount();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - FilamentAsset::getResourceUris() const: returns unresolved type const char *const *
//   - FilamentAsset::getSourceAsset(): return type: const void * is opaque, so there is nothing to marshal
//   - FilamentAsset::addEntitiesToScene(filament::Scene &, const Entity *, size_t, SceneMask) const: parameter "sceneFilter": SceneMask crosses by copy, and Java has no value type
//   - FilamentAsset::getAssetInstances(): returns unresolved type FilamentInstance **
