#!/usr/bin/env bash
# Syntax-checks the generated embind bindings against the real Filament headers.
#
# This is the acceptance check for the JavaScript emitter: a generated file that
# does not compile is worthless, and embind reports most mistakes only at compile
# time. Nothing is linked and no wasm is produced, so a full run is quick.
#
#   tools/beamsplitter2/verify-js.sh                    # every generated file
#   tools/beamsplitter2/verify-js.sh web/filament-js/filament/Camera_generated.cpp
#
# Override EMSDK or PYTHON if they live somewhere else.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
EMSDK="${EMSDK:-$(dirname "$ROOT")/emsdk}"
EMXX="$EMSDK/upstream/emscripten/em++.py"

# emcc needs Python 3.10 or newer, which is often not the system python3.
PYTHON="${PYTHON:-}"
if [ -z "$PYTHON" ]; then
    for candidate in python3.13 python3.12 python3.11 python3.10 python3; do
        if command -v "$candidate" >/dev/null 2>&1 &&
           "$candidate" -c 'import sys; sys.exit(sys.version_info < (3, 10))'; then
            PYTHON="$candidate"
            break
        fi
    done
fi

if [ ! -f "$EMXX" ]; then
    echo "verify-js.sh: no emscripten at $EMSDK (set EMSDK)" >&2
    exit 1
fi
if [ -z "$PYTHON" ]; then
    echo "verify-js.sh: need python 3.10+ to run emcc (set PYTHON)" >&2
    exit 1
fi

# The include path comes from the tool, which is where the header lists live. A
# second copy here is how libs/iblprefilter went missing from it for a release.
INCLUDES=()
while IFS= read -r dir; do INCLUDES+=("-I$ROOT/$dir"); done \
    < <(cd "$ROOT/tools/beamsplitter2" && go run . -includes)
if [ ${#INCLUDES[@]} -eq 0 ]; then
    echo "verify-js.sh: beamsplitter2 -includes printed nothing" >&2
    exit 1
fi

# Not header directories the tool parses: stb is pulled in by image/, and
# jsbindings_helpers.h lives beside the generated bindings.
INCLUDES+=("-I$ROOT/third_party/stb" "-I$ROOT/web/filament-js")

# materials/uberarchive.h is generated by the build rather than checked in.
for candidate in "$ROOT"/out/cmake-wasm-*/libs/gltfio; do
    if [ -f "$candidate/materials/uberarchive.h" ]; then
        INCLUDES+=("-I$candidate")
        break
    fi
done

FILES=("$@")
if [ ${#FILES[@]} -eq 0 ]; then
    while IFS= read -r file; do FILES+=("$file"); done \
        < <(find "$ROOT/web/filament-js" -name '*_generated.cpp' | sort)
fi

failed=0
for file in "${FILES[@]}"; do
    # -std=c++20 and -fno-rtti match the Filament build, and embind needs to be
    # told about the second.
    if output=$("$PYTHON" "$EMXX" -fsyntax-only -std=c++20 -fno-rtti \
            -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 \
            "${INCLUDES[@]}" "$file" 2>&1); then
        echo "ok   ${file#"$ROOT"/}"
    else
        echo "FAIL ${file#"$ROOT"/}"
        echo "$output" | grep -E '(error|warning):' | head -8 | sed 's/^/       /'
        failed=$((failed + 1))
    fi
done

if [ "$failed" -ne 0 ]; then
    echo "$failed file(s) failed to compile" >&2
    exit 1
fi
