// This file has been generated by beamsplitter
package com.google.android.filament.gltfio;

public class FilamentInstance_generated {
    private final long mNativeObject;

    public FilamentInstance_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getAsset() {
        return nGetAsset(mNativeObject);
    }
    private static native long nGetAsset(long nativeObject);

    public long getEntities() {
        return nGetEntities(mNativeObject);
    }
    private static native long nGetEntities(long nativeObject);

    public long getEntityCount() {
        return nGetEntityCount(mNativeObject);
    }
    private static native long nGetEntityCount(long nativeObject);

    public int getRoot() {
        return nGetRoot(mNativeObject);
    }
    private static native int nGetRoot(long nativeObject);

    public void applyMaterialVariant(long variantIndex) {
        nApplyMaterialVariant(mNativeObject, variantIndex);
    }
    private static native void nApplyMaterialVariant(long nativeObject, long variantIndex);

    public long getMaterialVariantCount() {
        return nGetMaterialVariantCount(mNativeObject);
    }
    private static native long nGetMaterialVariantCount(long nativeObject);

    public String getMaterialVariantName(long variantIndex) {
        return nGetMaterialVariantName(mNativeObject, variantIndex);
    }
    private static native String nGetMaterialVariantName(long nativeObject, long variantIndex);

    public long getAnimator() {
        return nGetAnimator(mNativeObject);
    }
    private static native long nGetAnimator(long nativeObject);

    public long getSkinCount() {
        return nGetSkinCount(mNativeObject);
    }
    private static native long nGetSkinCount(long nativeObject);

    public String getSkinNameAt(long skinIndex) {
        return nGetSkinNameAt(mNativeObject, skinIndex);
    }
    private static native String nGetSkinNameAt(long nativeObject, long skinIndex);

    public long getJointCountAt(long skinIndex) {
        return nGetJointCountAt(mNativeObject, skinIndex);
    }
    private static native long nGetJointCountAt(long nativeObject, long skinIndex);

    public long getJointsAt(long skinIndex) {
        return nGetJointsAt(mNativeObject, skinIndex);
    }
    private static native long nGetJointsAt(long nativeObject, long skinIndex);

    public void attachSkin(long skinIndex, int target) {
        nAttachSkin(mNativeObject, skinIndex, target);
    }
    private static native void nAttachSkin(long nativeObject, long skinIndex, int target);

    public void detachSkin(long skinIndex, int target) {
        nDetachSkin(mNativeObject, skinIndex, target);
    }
    private static native void nDetachSkin(long nativeObject, long skinIndex, int target);

    public void recomputeBoundingBoxes() {
        nRecomputeBoundingBoxes(mNativeObject);
    }
    private static native void nRecomputeBoundingBoxes(long nativeObject);

    public com.google.android.filament.Aabb_generated getBoundingBox() {
        return nGetBoundingBox(mNativeObject);
    }
    private static native com.google.android.filament.Aabb_generated nGetBoundingBox(long nativeObject);

    public long getMaterialInstanceCount() {
        return nGetMaterialInstanceCount(mNativeObject);
    }
    private static native long nGetMaterialInstanceCount(long nativeObject);

    public void detachMaterialInstances() {
        nDetachMaterialInstances(mNativeObject);
    }
    private static native void nDetachMaterialInstances(long nativeObject);
}
