// This file has been generated by beamsplitter
package com.google.android.filament.gltfio;

public class FilamentAsset_generated {
    private final long mNativeObject;

    public FilamentAsset_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getEntities() {
        return nGetEntities(mNativeObject);
    }
    private static native long nGetEntities(long nativeObject);

    public long getEntityCount() {
        return nGetEntityCount(mNativeObject);
    }
    private static native long nGetEntityCount(long nativeObject);

    public long getLightEntities() {
        return nGetLightEntities(mNativeObject);
    }
    private static native long nGetLightEntities(long nativeObject);

    public long getLightEntityCount() {
        return nGetLightEntityCount(mNativeObject);
    }
    private static native long nGetLightEntityCount(long nativeObject);

    public long getRenderableEntities() {
        return nGetRenderableEntities(mNativeObject);
    }
    private static native long nGetRenderableEntities(long nativeObject);

    public long getRenderableEntityCount() {
        return nGetRenderableEntityCount(mNativeObject);
    }
    private static native long nGetRenderableEntityCount(long nativeObject);

    public long getCameraEntities() {
        return nGetCameraEntities(mNativeObject);
    }
    private static native long nGetCameraEntities(long nativeObject);

    public long getCameraEntityCount() {
        return nGetCameraEntityCount(mNativeObject);
    }
    private static native long nGetCameraEntityCount(long nativeObject);

    public int getRoot() {
        return nGetRoot(mNativeObject);
    }
    private static native int nGetRoot(long nativeObject);

    public int popRenderable() {
        return nPopRenderable(mNativeObject);
    }
    private static native int nPopRenderable(long nativeObject);

    public long popRenderables(long entities, long count) {
        return nPopRenderables(mNativeObject, entities, count);
    }
    private static native long nPopRenderables(long nativeObject, long entities, long count);

    public long getResourceUriCount() {
        return nGetResourceUriCount(mNativeObject);
    }
    private static native long nGetResourceUriCount(long nativeObject);

    public com.google.android.filament.Aabb_generated getBoundingBox() {
        return nGetBoundingBox(mNativeObject);
    }
    private static native com.google.android.filament.Aabb_generated nGetBoundingBox(long nativeObject);

    public String getName(int arg0) {
        return nGetName(mNativeObject, arg0);
    }
    private static native String nGetName(long nativeObject, int arg0);

    public int getFirstEntityByName(String name) {
        return nGetFirstEntityByName(mNativeObject, name);
    }
    private static native int nGetFirstEntityByName(long nativeObject, String name);

    public long getEntitiesByName(String name, long entities, long maxCount) {
        return nGetEntitiesByName(mNativeObject, name, entities, maxCount);
    }
    private static native long nGetEntitiesByName(long nativeObject, String name, long entities, long maxCount);

    public long getEntitiesByPrefix(String prefix, long entities, long maxCount) {
        return nGetEntitiesByPrefix(mNativeObject, prefix, entities, maxCount);
    }
    private static native long nGetEntitiesByPrefix(long nativeObject, String prefix, long entities, long maxCount);

    public String getExtras(int entity) {
        return nGetExtras(mNativeObject, entity);
    }
    private static native String nGetExtras(long nativeObject, int entity);

    public String getMorphTargetNameAt(int entity, long targetIndex) {
        return nGetMorphTargetNameAt(mNativeObject, entity, targetIndex);
    }
    private static native String nGetMorphTargetNameAt(long nativeObject, int entity, long targetIndex);

    public long getMorphTargetCountAt(int entity) {
        return nGetMorphTargetCountAt(mNativeObject, entity);
    }
    private static native long nGetMorphTargetCountAt(long nativeObject, int entity);

    public int getWireframe() {
        return nGetWireframe(mNativeObject);
    }
    private static native int nGetWireframe(long nativeObject);

    public long getEngine() {
        return nGetEngine(mNativeObject);
    }
    private static native long nGetEngine(long nativeObject);

    public void releaseSourceData() {
        nReleaseSourceData(mNativeObject);
    }
    private static native void nReleaseSourceData(long nativeObject);

    public long getSceneCount() {
        return nGetSceneCount(mNativeObject);
    }
    private static native long nGetSceneCount(long nativeObject);

    public String getSceneName(long sceneIndex) {
        return nGetSceneName(mNativeObject, sceneIndex);
    }
    private static native String nGetSceneName(long nativeObject, long sceneIndex);

    public void detachFilamentComponents() {
        nDetachFilamentComponents(mNativeObject);
    }
    private static native void nDetachFilamentComponents(long nativeObject);

    public boolean areFilamentComponentsDetached() {
        return nAreFilamentComponentsDetached(mNativeObject);
    }
    private static native boolean nAreFilamentComponentsDetached(long nativeObject);

    public long getInstance() {
        return nGetInstance(mNativeObject);
    }
    private static native long nGetInstance(long nativeObject);

    public long getAssetInstanceCount() {
        return nGetAssetInstanceCount(mNativeObject);
    }
    private static native long nGetAssetInstanceCount(long nativeObject);
}
