// This file has been generated by beamsplitter
package com.google.android.filament.gltfio;

public class MaterialProvider_generated {
    private final long mNativeObject;

    public MaterialProvider_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getMaterialsCount() {
        return nGetMaterialsCount(mNativeObject);
    }
    private static native long nGetMaterialsCount(long nativeObject);

    public void destroyMaterials() {
        nDestroyMaterials(mNativeObject);
    }
    private static native void nDestroyMaterials(long nativeObject);

    public boolean needsDummyData(int attrib) {
        return nNeedsDummyData(mNativeObject, attrib);
    }
    private static native boolean nNeedsDummyData(long nativeObject, int attrib);
}
