// This file has been generated by beamsplitter
package com.google.android.filament.gltfio;

public class MaterialKey_generated {
    public byte baseColorUV;
    public byte emissiveUV;
    public byte aoUV;
    public byte normalUV;
    public byte specularTextureUV;
    public byte specularColorTextureUV;
    public short padding2;
}
