// This file has been generated by beamsplitter
package com.google.android.filament.gltfio;

public class TrsTransformManager_generated {
    private final long mNativeObject;

    public TrsTransformManager_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public boolean hasComponent(int e) {
        return nHasComponent(mNativeObject, e);
    }
    private static native boolean nHasComponent(long nativeObject, int e);

    public int getInstance(int e) {
        return nGetInstance(mNativeObject, e);
    }
    private static native int nGetInstance(long nativeObject, int e);

    public void create(int entity) {
        nCreate(mNativeObject, entity);
    }
    private static native void nCreate(long nativeObject, int entity);

    public void create(int entity, float[] translation, float[] rotation, float[] scale) {
        nCreate(mNativeObject, entity, translation, rotation, scale);
    }
    private static native void nCreate(long nativeObject, int entity, float[] translation, float[] rotation, float[] scale);

    public void destroy(int e) {
        nDestroy(mNativeObject, e);
    }
    private static native void nDestroy(long nativeObject, int e);

    public void setTranslation(int ci, float[] translation) {
        nSetTranslation(mNativeObject, ci, translation);
    }
    private static native void nSetTranslation(long nativeObject, int ci, float[] translation);

    public float[] getTranslation(int ci) {
        float[] out = new float[3];
        nGetTranslation(mNativeObject, ci, out);
        return out;
    }
    private static native void nGetTranslation(long nativeObject, int ci, float[] out);

    public void setRotation(int ci, float[] rotation) {
        nSetRotation(mNativeObject, ci, rotation);
    }
    private static native void nSetRotation(long nativeObject, int ci, float[] rotation);

    public float[] getRotation(int ci) {
        float[] out = new float[4];
        nGetRotation(mNativeObject, ci, out);
        return out;
    }
    private static native void nGetRotation(long nativeObject, int ci, float[] out);

    public void setScale(int ci, float[] scale) {
        nSetScale(mNativeObject, ci, scale);
    }
    private static native void nSetScale(long nativeObject, int ci, float[] scale);

    public float[] getScale(int ci) {
        float[] out = new float[3];
        nGetScale(mNativeObject, ci, out);
        return out;
    }
    private static native void nGetScale(long nativeObject, int ci, float[] out);

    public void setTrs(int ci, float[] translation, float[] rotation, float[] scale) {
        nSetTrs(mNativeObject, ci, translation, rotation, scale);
    }
    private static native void nSetTrs(long nativeObject, int ci, float[] translation, float[] rotation, float[] scale);

    public float[] getTransform(int ci) {
        float[] out = new float[16];
        nGetTransform(mNativeObject, ci, out);
        return out;
    }
    private static native void nGetTransform(long nativeObject, int ci, float[] out);
}
