// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class AgxToneMapperSettings_generated {
    public int look = 0;

    public boolean notEquals(AgxToneMapperSettings_generated rhs) {
        return nNotEquals(this, rhs);
    }
    private static native boolean nNotEquals(AgxToneMapperSettings_generated self, AgxToneMapperSettings_generated rhs);

    public boolean equals(AgxToneMapperSettings_generated rhs) {
        return nEquals(this, rhs);
    }
    private static native boolean nEquals(AgxToneMapperSettings_generated self, AgxToneMapperSettings_generated rhs);
}
