// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class AnimationSettings_generated {
    public boolean enabled = false;
    public float time = -1f;
    public float speed = 1f;
}
