// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class AutomationEngine_generated {
    private final long mNativeObject;

    public AutomationEngine_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static AutomationEngine_generated create(long spec, long settings) {
        return new AutomationEngine_generated(nCreate(spec, settings));
    }
    private static native long nCreate(long spec, long settings);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public static long createFromJSON(String jsonSpec, long size) {
        return nCreateFromJSON(jsonSpec, size);
    }
    private static native long nCreateFromJSON(String jsonSpec, long size);

    public static long createDefault() {
        return nCreateDefault();
    }
    private static native long nCreateDefault();

    public void startRunning() {
        nStartRunning(mNativeObject);
    }
    private static native void nStartRunning(long nativeObject);

    public void startBatchMode() {
        nStartBatchMode(mNativeObject);
    }
    private static native void nStartBatchMode(long nativeObject);

    public void tick(long engine, long content, float deltaTime) {
        nTick(mNativeObject, engine, content, deltaTime);
    }
    private static native void nTick(long nativeObject, long engine, long content, float deltaTime);

    public void applySettings(long engine, String json, long jsonLength, long content) {
        nApplySettings(mNativeObject, engine, json, jsonLength, content);
    }
    private static native void nApplySettings(long nativeObject, long engine, String json, long jsonLength, long content);

    public long getColorGrading(long engine) {
        return nGetColorGrading(mNativeObject, engine);
    }
    private static native long nGetColorGrading(long nativeObject, long engine);

    public ViewerOptions_generated getViewerOptions() {
        return nGetViewerOptions(mNativeObject);
    }
    private static native ViewerOptions_generated nGetViewerOptions(long nativeObject);

    public long getSettings() {
        return nGetSettings(mNativeObject);
    }
    private static native long nGetSettings(long nativeObject);

    public void signalBatchMode() {
        nSignalBatchMode(mNativeObject);
    }
    private static native void nSignalBatchMode(long nativeObject);

    public void stopRunning() {
        nStopRunning(mNativeObject);
    }
    private static native void nStopRunning(long nativeObject);

    public void terminate() {
        nTerminate(mNativeObject);
    }
    private static native void nTerminate(long nativeObject);

    public void setOptions(AutomationEngine_generated.Options options) {
        nSetOptions(mNativeObject, options);
    }
    private static native void nSetOptions(long nativeObject, AutomationEngine_generated.Options options);

    public boolean shouldClose() {
        return nShouldClose(mNativeObject);
    }
    private static native boolean nShouldClose(long nativeObject);

    public static void exportSettings(long settings, String filename) {
        nExportSettings(settings, filename);
    }
    private static native void nExportSettings(long settings, String filename);

    public static void exportScreenshot(long view, long renderer, String filename, boolean autoclose, long automationEngine) {
        nExportScreenshot(view, renderer, filename, autoclose, automationEngine);
    }
    private static native void nExportScreenshot(long view, long renderer, String filename, boolean autoclose, long automationEngine);

    public AutomationEngine_generated.Options getOptions() {
        return nGetOptions(mNativeObject);
    }
    private static native AutomationEngine_generated.Options nGetOptions(long nativeObject);

    public boolean isRunning() {
        return nIsRunning(mNativeObject);
    }
    private static native boolean nIsRunning(long nativeObject);

    public long currentTest() {
        return nCurrentTest(mNativeObject);
    }
    private static native long nCurrentTest(long nativeObject);

    public long testCount() {
        return nTestCount(mNativeObject);
    }
    private static native long nTestCount(long nativeObject);

    public boolean isBatchModeEnabled() {
        return nIsBatchModeEnabled(mNativeObject);
    }
    private static native boolean nIsBatchModeEnabled(long nativeObject);

    public String getStatusMessage() {
        return nGetStatusMessage(mNativeObject);
    }
    private static native String nGetStatusMessage(long nativeObject);

    public void requestClose() {
        nRequestClose(mNativeObject);
    }
    private static native void nRequestClose(long nativeObject);

    public boolean isTerminated() {
        return nIsTerminated(mNativeObject);
    }
    private static native boolean nIsTerminated(long nativeObject);

public static class Options {
    public float sleepDuration = 0.200000003f;
    public int minFrameCount = 2;
    public boolean verbose = true;
    public boolean exportScreenshots = false;
    public boolean exportSettings = false;
    public int exportFormat = 0;
}


public static class ViewerContent {
    private final long mNativeObject;

    public ViewerContent(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}

}
