// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class CameraSettings_generated {
    public float[] center = new float[3];
    public float[] lookAt = new float[3];
    public float[] up = new float[3];
    public float horizontalFov = 0f;
    public float near = 0.100000001f;
    public float far = 100f;
    public float focalLength = 28f;
    public float aperture = 16f;
    public float shutterSpeed = 125f;
    public float sensitivity = 100f;
    public float focusDistance = 10f;
    public float eyeOcularDistance = 0f;
    public float eyeToeIn = 0f;
    public int projection = 0;
    public boolean enabled = false;
    public float[] scaling = new float[2];
    public float[] shift = new float[2];
}
