// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class ColorGradingSettings_generated {
    private final long mNativeObject;

    public ColorGradingSettings_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public boolean notEquals(long rhs) {
        return nNotEquals(mNativeObject, rhs);
    }
    private static native boolean nNotEquals(long nativeObject, long rhs);

    public boolean equals(long rhs) {
        return nEquals(mNativeObject, rhs);
    }
    private static native boolean nEquals(long nativeObject, long rhs);
}
