// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class GenericToneMapperSettings_generated {
    public float contrast = 1.54999995f;
    public float midGrayIn = 0.180000007f;
    public float midGrayOut = 0.215000004f;
    public float hdrMax = 10f;

    public boolean notEquals(GenericToneMapperSettings_generated rhs) {
        return nNotEquals(this, rhs);
    }
    private static native boolean nNotEquals(GenericToneMapperSettings_generated self, GenericToneMapperSettings_generated rhs);

    public boolean equals(GenericToneMapperSettings_generated rhs) {
        return nEquals(this, rhs);
    }
    private static native boolean nEquals(GenericToneMapperSettings_generated self, GenericToneMapperSettings_generated rhs);
}
