// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class Ktx2Reader_generated {
    private final long mNativeObject;

    public Ktx2Reader_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Ktx2Reader_generated create(long engine, boolean quiet) {
        return new Ktx2Reader_generated(nCreate(engine, quiet));
    }
    private static native long nCreate(long engine, boolean quiet);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public int requestFormat(int format) {
        return nRequestFormat(mNativeObject, format);
    }
    private static native int nRequestFormat(long nativeObject, int format);

    public void unrequestFormat(int format) {
        nUnrequestFormat(mNativeObject, format);
    }
    private static native void nUnrequestFormat(long nativeObject, int format);

public static class Async {
    private final long mNativeObject;

    public Async(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getTexture() {
        return nGetTexture(mNativeObject);
    }
    private static native long nGetTexture(long nativeObject);

    public int doTranscoding() {
        return nDoTranscoding(mNativeObject);
    }
    private static native int nDoTranscoding(long nativeObject);

    public void uploadImages() {
        nUploadImages(mNativeObject);
    }
    private static native void nUploadImages(long nativeObject);
}

}
