// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class KtxBlobIndex_generated {
    public int mipLevel;
    public int arrayIndex;
    public int cubeFace;
}
