// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class KtxInfo_generated {
    public int endianness;
    public int glType;
    public int glTypeSize;
    public int glFormat;
    public int glInternalFormat;
    public int glBaseInternalFormat;
    public int pixelWidth;
    public int pixelHeight;
    public int pixelDepth;
}
