// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class LinearImage_generated {
    private final long mNativeObject;

    public LinearImage_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static LinearImage_generated create(int width, int height, int channels) {
        return new LinearImage_generated(nCreate(width, height, channels));
    }
    private static native long nCreate(int width, int height, int channels);

    public static LinearImage_generated create() {
        return new LinearImage_generated(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public int getWidth() {
        return nGetWidth(mNativeObject);
    }
    private static native int nGetWidth(long nativeObject);

    public int getHeight() {
        return nGetHeight(mNativeObject);
    }
    private static native int nGetHeight(long nativeObject);

    public int getChannels() {
        return nGetChannels(mNativeObject);
    }
    private static native int nGetChannels(long nativeObject);

    public void reset() {
        nReset(mNativeObject);
    }
    private static native void nReset(long nativeObject);

    public boolean isValid() {
        return nIsValid(mNativeObject);
    }
    private static native boolean nIsValid(long nativeObject);
}
