// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class Manipulator_generated {
    private final long mNativeObject;

    public Manipulator_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public int getMode() {
        return nGetMode(mNativeObject);
    }
    private static native int nGetMode(long nativeObject);

    public void setViewport(int width, int height) {
        nSetViewport(mNativeObject, width, height);
    }
    private static native void nSetViewport(long nativeObject, int width, int height);

    public void grabBegin(int x, int y, boolean strafe) {
        nGrabBegin(mNativeObject, x, y, strafe);
    }
    private static native void nGrabBegin(long nativeObject, int x, int y, boolean strafe);

    public void grabUpdate(int x, int y) {
        nGrabUpdate(mNativeObject, x, y);
    }
    private static native void nGrabUpdate(long nativeObject, int x, int y);

    public void grabEnd() {
        nGrabEnd(mNativeObject);
    }
    private static native void nGrabEnd(long nativeObject);

    public void keyDown(int key) {
        nKeyDown(mNativeObject, key);
    }
    private static native void nKeyDown(long nativeObject, int key);

    public void keyUp(int key) {
        nKeyUp(mNativeObject, key);
    }
    private static native void nKeyUp(long nativeObject, int key);

    public void scroll(int x, int y, float scrolldelta) {
        nScroll(mNativeObject, x, y, scrolldelta);
    }
    private static native void nScroll(long nativeObject, int x, int y, float scrolldelta);

    public void update(float deltaTime) {
        nUpdate(mNativeObject, deltaTime);
    }
    private static native void nUpdate(long nativeObject, float deltaTime);

public static class Config {
    private final long mNativeObject;

    public Config(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}


public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long viewport(int width, int height) {
        return nViewport(mNativeObject, width, height);
    }
    private static native long nViewport(long nativeObject, int width, int height);

    public long targetPosition(float x, float y, float z) {
        return nTargetPosition(mNativeObject, x, y, z);
    }
    private static native long nTargetPosition(long nativeObject, float x, float y, float z);

    public long upVector(float x, float y, float z) {
        return nUpVector(mNativeObject, x, y, z);
    }
    private static native long nUpVector(long nativeObject, float x, float y, float z);

    public long zoomSpeed(float val) {
        return nZoomSpeed(mNativeObject, val);
    }
    private static native long nZoomSpeed(long nativeObject, float val);

    public long orbitHomePosition(float x, float y, float z) {
        return nOrbitHomePosition(mNativeObject, x, y, z);
    }
    private static native long nOrbitHomePosition(long nativeObject, float x, float y, float z);

    public long orbitSpeed(float x, float y) {
        return nOrbitSpeed(mNativeObject, x, y);
    }
    private static native long nOrbitSpeed(long nativeObject, float x, float y);

    public long fovDirection(int fov) {
        return nFovDirection(mNativeObject, fov);
    }
    private static native long nFovDirection(long nativeObject, int fov);

    public long fovDegrees(float degrees) {
        return nFovDegrees(mNativeObject, degrees);
    }
    private static native long nFovDegrees(long nativeObject, float degrees);

    public long farPlane(float distance) {
        return nFarPlane(mNativeObject, distance);
    }
    private static native long nFarPlane(long nativeObject, float distance);

    public long mapExtent(float worldWidth, float worldHeight) {
        return nMapExtent(mNativeObject, worldWidth, worldHeight);
    }
    private static native long nMapExtent(long nativeObject, float worldWidth, float worldHeight);

    public long mapMinDistance(float mindist) {
        return nMapMinDistance(mNativeObject, mindist);
    }
    private static native long nMapMinDistance(long nativeObject, float mindist);

    public long flightStartPosition(float x, float y, float z) {
        return nFlightStartPosition(mNativeObject, x, y, z);
    }
    private static native long nFlightStartPosition(long nativeObject, float x, float y, float z);

    public long flightStartOrientation(float pitch, float yaw) {
        return nFlightStartOrientation(mNativeObject, pitch, yaw);
    }
    private static native long nFlightStartOrientation(long nativeObject, float pitch, float yaw);

    public long flightMaxMoveSpeed(float maxSpeed) {
        return nFlightMaxMoveSpeed(mNativeObject, maxSpeed);
    }
    private static native long nFlightMaxMoveSpeed(long nativeObject, float maxSpeed);

    public long flightSpeedSteps(int steps) {
        return nFlightSpeedSteps(mNativeObject, steps);
    }
    private static native long nFlightSpeedSteps(long nativeObject, int steps);

    public long flightPanSpeed(float x, float y) {
        return nFlightPanSpeed(mNativeObject, x, y);
    }
    private static native long nFlightPanSpeed(long nativeObject, float x, float y);

    public long flightMoveDamping(float damping) {
        return nFlightMoveDamping(mNativeObject, damping);
    }
    private static native long nFlightMoveDamping(long nativeObject, float damping);

    public long groundPlane(float a, float b, float c, float d) {
        return nGroundPlane(mNativeObject, a, b, c, d);
    }
    private static native long nGroundPlane(long nativeObject, float a, float b, float c, float d);

    public long panning(boolean enabled) {
        return nPanning(mNativeObject, enabled);
    }
    private static native long nPanning(long nativeObject, boolean enabled);

    public long build(int mode) {
        return nBuild(mNativeObject, mode);
    }
    private static native long nBuild(long nativeObject, int mode);
}

}
