// This file has been generated by beamsplitter
package com.google.android.filament.utils;

public class Transcoder_generated {
    private final long mNativeObject;

    public Transcoder_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Transcoder_generated create(Transcoder_generated.Config config) {
        return new Transcoder_generated(nCreate(config));
    }
    private static native long nCreate(Transcoder_generated.Config config);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

public static class Config {
    public int componentType;
    public boolean normalized;
    public int componentCount;
    public int inputStrideBytes = 0;
}

}
