// This file has been generated by beamsplitter

#include <gltfio/AssetLoader.h>
#include <gltfio/MaterialProvider.h>
#include <gltfio/ResourceLoader.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(gltfio_structs) {

value_object<filament::gltfio::AssetConfiguration>("AssetConfiguration")
    ;

value_object<filament::gltfio::AssetConfigurationExtended>("AssetConfigurationExtended")
    ;

value_object<filament::gltfio::MaterialKey>("MaterialKey")
    .field("baseColorUV", &filament::gltfio::MaterialKey::baseColorUV)
    .field("emissiveUV", &filament::gltfio::MaterialKey::emissiveUV)
    .field("aoUV", &filament::gltfio::MaterialKey::aoUV)
    .field("normalUV", &filament::gltfio::MaterialKey::normalUV)
    .field("specularTextureUV", &filament::gltfio::MaterialKey::specularTextureUV)
    .field("specularColorTextureUV", &filament::gltfio::MaterialKey::specularColorTextureUV)
    .field("padding2", &filament::gltfio::MaterialKey::padding2)
    ;

value_object<filament::gltfio::ResourceConfiguration>("ResourceConfiguration")
    .field("normalizeSkinningWeights", &filament::gltfio::ResourceConfiguration::normalizeSkinningWeights)
    ;

} // EMSCRIPTEN_BINDINGS
