// This file has been generated by beamsplitter

#include <gltfio/Animator.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::gltfio::Animator>(filament::gltfio::Animator* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(gltfio_Animator) {

class_<filament::gltfio::Animator>("Animator")
    .function("applyAnimation", &filament::gltfio::Animator::applyAnimation)
    .function("updateBoneMatrices", &filament::gltfio::Animator::updateBoneMatrices)
    .function("applyCrossFade", &filament::gltfio::Animator::applyCrossFade)
    .function("resetBoneMatrices", &filament::gltfio::Animator::resetBoneMatrices)
    .function("getAnimationCount", &filament::gltfio::Animator::getAnimationCount)
    .function("getAnimationDuration", &filament::gltfio::Animator::getAnimationDuration)
    .function("getAnimationName", &filament::gltfio::Animator::getAnimationName, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Animator::addInstance(FFilamentInstance *): parameter "instance" has unresolved type FFilamentInstance *


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
