// This file has been generated by beamsplitter

#include <gltfio/AssetLoader.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::gltfio::AssetLoader>(filament::gltfio::AssetLoader* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(gltfio_AssetLoader) {

class_<filament::gltfio::AssetLoader>("AssetLoader")
    .class_function("create", &filament::gltfio::AssetLoader::create, allow_raw_pointers())
    .function("createAsset", (filament::gltfio::FilamentAsset* (*) (filament::gltfio::AssetLoader* self, emscripten::val bytes, uint32_t numBytes)) [](filament::gltfio::AssetLoader* self, emscripten::val bytes, uint32_t numBytes) -> filament::gltfio::FilamentAsset* {
        auto bytes_ = emscripten::convertJSArrayToNumberVector<uint8_t>(bytes);
        return self->createAsset(reinterpret_cast<const uint8_t*>(bytes_.data()), numBytes);
    }, allow_raw_pointers())
    .function("createInstance", &filament::gltfio::AssetLoader::createInstance, allow_raw_pointers())
    .function("enableDiagnostics", &filament::gltfio::AssetLoader::enableDiagnostics)
    .function("destroyAsset", &filament::gltfio::AssetLoader::destroyAsset, allow_raw_pointers())
    .function("gc", &filament::gltfio::AssetLoader::gc)
    .function("getMaterialsCount", &filament::gltfio::AssetLoader::getMaterialsCount)
    .function("getNames", &filament::gltfio::AssetLoader::getNames, allow_raw_pointers())
    .function("getNodeManager", (filament::gltfio::NodeManager* (*) (filament::gltfio::AssetLoader* self)) [](filament::gltfio::AssetLoader* self) -> filament::gltfio::NodeManager* {
        return &self->getNodeManager();
    }, allow_raw_pointers())
    .function("getMaterialProvider", (filament::gltfio::MaterialProvider* (*) (filament::gltfio::AssetLoader* self)) [](filament::gltfio::AssetLoader* self) -> filament::gltfio::MaterialProvider* {
        return &self->getMaterialProvider();
    }, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - AssetLoader::AssetLoader(const AssetLoader &): explicitly deleted
//   - AssetLoader::AssetLoader(AssetLoader &&): explicitly deleted
//   - AssetLoader::destroy(AssetLoader **): parameter "loader" has unresolved type AssetLoader **
//   - AssetLoader::createInstancedAsset(const uint8_t *, uint32_t, FilamentInstance **, size_t): parameter "instances" has unresolved type FilamentInstance **
//   - AssetLoader::getMaterials() const: returns unresolved type const filament::Material *const *


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
