// This file has been generated by beamsplitter

#include <gltfio/FilamentInstance.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(gltfio_FilamentInstance) {

class_<filament::gltfio::FilamentInstance>("FilamentInstance")
    .function("getAsset", &filament::gltfio::FilamentInstance::getAsset, allow_raw_pointers())
    .function("getEntities", &filament::gltfio::FilamentInstance::getEntities, allow_raw_pointers())
    .function("getEntityCount", &filament::gltfio::FilamentInstance::getEntityCount)
    .function("getRoot", &filament::gltfio::FilamentInstance::getRoot)
    .function("applyMaterialVariant", &filament::gltfio::FilamentInstance::applyMaterialVariant)
    .function("getMaterialVariantCount", &filament::gltfio::FilamentInstance::getMaterialVariantCount)
    .function("getMaterialVariantName", &filament::gltfio::FilamentInstance::getMaterialVariantName, allow_raw_pointers())
    .function("getAnimator", &filament::gltfio::FilamentInstance::getAnimator, allow_raw_pointers())
    .function("getSkinCount", &filament::gltfio::FilamentInstance::getSkinCount)
    .function("getSkinNameAt", &filament::gltfio::FilamentInstance::getSkinNameAt, allow_raw_pointers())
    .function("getJointCountAt", &filament::gltfio::FilamentInstance::getJointCountAt)
    .function("getJointsAt", &filament::gltfio::FilamentInstance::getJointsAt, allow_raw_pointers())
    .function("attachSkin", &filament::gltfio::FilamentInstance::attachSkin)
    .function("detachSkin", &filament::gltfio::FilamentInstance::detachSkin)
    .function("recomputeBoundingBoxes", &filament::gltfio::FilamentInstance::recomputeBoundingBoxes)
    .function("getBoundingBox", &filament::gltfio::FilamentInstance::getBoundingBox)
    .function("getMaterialInstanceCount", &filament::gltfio::FilamentInstance::getMaterialInstanceCount)
    .function("detachMaterialInstances", &filament::gltfio::FilamentInstance::detachMaterialInstances)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - FilamentInstance::getInverseBindMatricesAt(size_t) const: returns const math::mat4f *, an array with no length
//   - FilamentInstance::getMaterialInstances() const: returns unresolved type const MaterialInstance *const *
//   - FilamentInstance::getMaterialInstances(): returns unresolved type MaterialInstance *const *


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
