// This file has been generated by beamsplitter

#include <gltfio/TrsTransformManager.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::gltfio::TrsTransformManager>(filament::gltfio::TrsTransformManager* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(gltfio_TrsTransformManager) {

class_<filament::gltfio::TrsTransformManager>("TrsTransformManager")
    .function("hasComponent", &filament::gltfio::TrsTransformManager::hasComponent)
    .function("getInstance", (uint32_t (*) (filament::gltfio::TrsTransformManager* self, utils::Entity e)) [](filament::gltfio::TrsTransformManager* self, utils::Entity e) -> uint32_t {
        return self->getInstance(e);
    }, allow_raw_pointers())
    .function("create", static_cast<void (filament::gltfio::TrsTransformManager::*)(utils::Entity)>(&filament::gltfio::TrsTransformManager::create))
    .function("create", static_cast<void (filament::gltfio::TrsTransformManager::*)(utils::Entity, const filament::math::details::TVec3<float>&, const filament::math::details::TQuaternion<float>&, const filament::math::details::TVec3<float>&)>(&filament::gltfio::TrsTransformManager::create))
    .function("destroy", &filament::gltfio::TrsTransformManager::destroy)
    .function("setTranslation", (void (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TVec3<float>& translation)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TVec3<float>& translation) -> void {
        self->setTranslation(ci, translation);
    }, allow_raw_pointers())
    .function("getTranslation", (const filament::math::details::TVec3<float>& (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci) -> const filament::math::details::TVec3<float>& {
        return self->getTranslation(ci);
    }, allow_raw_pointers())
    .function("setRotation", (void (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TQuaternion<float>& rotation)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TQuaternion<float>& rotation) -> void {
        self->setRotation(ci, rotation);
    }, allow_raw_pointers())
    .function("getRotation", (const filament::math::details::TQuaternion<float>& (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci) -> const filament::math::details::TQuaternion<float>& {
        return self->getRotation(ci);
    }, allow_raw_pointers())
    .function("setScale", (void (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TVec3<float>& scale)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TVec3<float>& scale) -> void {
        self->setScale(ci, scale);
    }, allow_raw_pointers())
    .function("getScale", (const filament::math::details::TVec3<float>& (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci) -> const filament::math::details::TVec3<float>& {
        return self->getScale(ci);
    }, allow_raw_pointers())
    .function("setTrs", (void (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TVec3<float>& translation, const filament::math::details::TQuaternion<float>& rotation, const filament::math::details::TVec3<float>& scale)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci, const filament::math::details::TVec3<float>& translation, const filament::math::details::TQuaternion<float>& rotation, const filament::math::details::TVec3<float>& scale) -> void {
        self->setTrs(ci, translation, rotation, scale);
    }, allow_raw_pointers())
    .function("getTransform", (flatmat4 (*) (filament::gltfio::TrsTransformManager* self, uint32_t ci)) [](filament::gltfio::TrsTransformManager* self, uint32_t ci) -> flatmat4 {
        return flatmat4 { filament::math::mat4f(self->getTransform(ci)) };
    }, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - TrsTransformManager::TrsTransformManager(const TrsTransformManager &): explicitly deleted
//   - TrsTransformManager::TrsTransformManager(TrsTransformManager &&): explicitly deleted


} // EMSCRIPTEN_BINDINGS
