// This file has been generated by beamsplitter

#include <filament/Box.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Box_1generated_nIsEmpty(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Box*) nativeObject)->isEmpty();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Box_1generated_nGetMin(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out_) {
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec3<float>*>(out) = ((filament::Box*) nativeObject)->getMin();
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Box_1generated_nGetMax(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out_) {
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec3<float>*>(out) = ((filament::Box*) nativeObject)->getMax();
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Box_1generated_nSet(JNIEnv* env, jclass, jlong nativeObject, jfloatArray min, jfloatArray max) {
    jfloat* min_ = env->GetFloatArrayElements(min, nullptr);
    jfloat* max_ = env->GetFloatArrayElements(max, nullptr);
    jlong result = (jlong) &((filament::Box*) nativeObject)->set(*reinterpret_cast<filament::math::details::TVec3<float>*>(min_), *reinterpret_cast<filament::math::details::TVec3<float>*>(max_));
    env->ReleaseFloatArrayElements(min, min_, JNI_ABORT);
    env->ReleaseFloatArrayElements(max, max_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Box_1generated_nUnionSelf(JNIEnv* env, jclass, jlong nativeObject, jlong box) {
    return (jlong) &((filament::Box*) nativeObject)->unionSelf(*(filament::Box*) box);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Box_1generated_nGetBoundingSphere(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out_) {
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec4<float>*>(out) = ((filament::Box*) nativeObject)->getBoundingSphere();
    env->ReleaseFloatArrayElements(out_, out, 0);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Box::translateTo(const math::float3 &) const: return type: Box crosses by copy, and Java has no value type
//   - Box::transform(const math::mat3f &, const math::float3 &, const Box &): return type: Box crosses by copy, and Java has no value type
