// This file has been generated by beamsplitter

#include <filament/ColorGrading.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::ColorGrading::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::ColorGrading::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nQuality(JNIEnv* env, jclass, jlong nativeObject, jint qualityLevel) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->quality((filament::ColorGrading::QualityLevel) qualityLevel);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nFormat(JNIEnv* env, jclass, jlong nativeObject, jint format) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->format((filament::ColorGrading::LutFormat) format);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nDimensions(JNIEnv* env, jclass, jlong nativeObject, jbyte dim) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->dimensions(dim);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nToneMapper(JNIEnv* env, jclass, jlong nativeObject, jlong toneMapper) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->toneMapper((filament::ToneMapper*) toneMapper);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nToneMapping(JNIEnv* env, jclass, jlong nativeObject, jint toneMapping) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->toneMapping((filament::ColorGrading::ToneMapping) toneMapping);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nLuminanceScaling(JNIEnv* env, jclass, jlong nativeObject, jboolean luminanceScaling) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->luminanceScaling(luminanceScaling);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nGamutMapping(JNIEnv* env, jclass, jlong nativeObject, jboolean gamutMapping) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->gamutMapping(gamutMapping);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nExposure(JNIEnv* env, jclass, jlong nativeObject, jfloat exposure) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->exposure(exposure);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nNightAdaptation(JNIEnv* env, jclass, jlong nativeObject, jfloat adaptation) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->nightAdaptation(adaptation);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nWhiteBalance(JNIEnv* env, jclass, jlong nativeObject, jfloat temperature, jfloat tint) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->whiteBalance(temperature, tint);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nChannelMixer(JNIEnv* env, jclass, jlong nativeObject, jfloatArray outRed, jfloatArray outGreen, jfloatArray outBlue) {
    jfloat* outRed_ = env->GetFloatArrayElements(outRed, nullptr);
    jfloat* outGreen_ = env->GetFloatArrayElements(outGreen, nullptr);
    jfloat* outBlue_ = env->GetFloatArrayElements(outBlue, nullptr);
    jlong result = (jlong) &((filament::ColorGrading::Builder*) nativeObject)->channelMixer(*reinterpret_cast<filament::math::details::TVec3<float>*>(outRed_), *reinterpret_cast<filament::math::details::TVec3<float>*>(outGreen_), *reinterpret_cast<filament::math::details::TVec3<float>*>(outBlue_));
    env->ReleaseFloatArrayElements(outRed, outRed_, JNI_ABORT);
    env->ReleaseFloatArrayElements(outGreen, outGreen_, JNI_ABORT);
    env->ReleaseFloatArrayElements(outBlue, outBlue_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nShadowsMidtonesHighlights(JNIEnv* env, jclass, jlong nativeObject, jfloatArray shadows, jfloatArray midtones, jfloatArray highlights, jfloatArray ranges) {
    jfloat* shadows_ = env->GetFloatArrayElements(shadows, nullptr);
    jfloat* midtones_ = env->GetFloatArrayElements(midtones, nullptr);
    jfloat* highlights_ = env->GetFloatArrayElements(highlights, nullptr);
    jfloat* ranges_ = env->GetFloatArrayElements(ranges, nullptr);
    jlong result = (jlong) &((filament::ColorGrading::Builder*) nativeObject)->shadowsMidtonesHighlights(*reinterpret_cast<filament::math::details::TVec4<float>*>(shadows_), *reinterpret_cast<filament::math::details::TVec4<float>*>(midtones_), *reinterpret_cast<filament::math::details::TVec4<float>*>(highlights_), *reinterpret_cast<filament::math::details::TVec4<float>*>(ranges_));
    env->ReleaseFloatArrayElements(shadows, shadows_, JNI_ABORT);
    env->ReleaseFloatArrayElements(midtones, midtones_, JNI_ABORT);
    env->ReleaseFloatArrayElements(highlights, highlights_, JNI_ABORT);
    env->ReleaseFloatArrayElements(ranges, ranges_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nSlopeOffsetPower(JNIEnv* env, jclass, jlong nativeObject, jfloatArray slope, jfloatArray offset, jfloatArray power) {
    jfloat* slope_ = env->GetFloatArrayElements(slope, nullptr);
    jfloat* offset_ = env->GetFloatArrayElements(offset, nullptr);
    jfloat* power_ = env->GetFloatArrayElements(power, nullptr);
    jlong result = (jlong) &((filament::ColorGrading::Builder*) nativeObject)->slopeOffsetPower(*reinterpret_cast<filament::math::details::TVec3<float>*>(slope_), *reinterpret_cast<filament::math::details::TVec3<float>*>(offset_), *reinterpret_cast<filament::math::details::TVec3<float>*>(power_));
    env->ReleaseFloatArrayElements(slope, slope_, JNI_ABORT);
    env->ReleaseFloatArrayElements(offset, offset_, JNI_ABORT);
    env->ReleaseFloatArrayElements(power, power_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nContrast(JNIEnv* env, jclass, jlong nativeObject, jfloat contrast) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->contrast(contrast);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nVibrance(JNIEnv* env, jclass, jlong nativeObject, jfloat vibrance) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->vibrance(vibrance);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nSaturation(JNIEnv* env, jclass, jlong nativeObject, jfloat saturation) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->saturation(saturation);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nCurves(JNIEnv* env, jclass, jlong nativeObject, jfloatArray shadowGamma, jfloatArray midPoint, jfloatArray highlightScale) {
    jfloat* shadowGamma_ = env->GetFloatArrayElements(shadowGamma, nullptr);
    jfloat* midPoint_ = env->GetFloatArrayElements(midPoint, nullptr);
    jfloat* highlightScale_ = env->GetFloatArrayElements(highlightScale, nullptr);
    jlong result = (jlong) &((filament::ColorGrading::Builder*) nativeObject)->curves(*reinterpret_cast<filament::math::details::TVec3<float>*>(shadowGamma_), *reinterpret_cast<filament::math::details::TVec3<float>*>(midPoint_), *reinterpret_cast<filament::math::details::TVec3<float>*>(highlightScale_));
    env->ReleaseFloatArrayElements(shadowGamma, shadowGamma_, JNI_ABORT);
    env->ReleaseFloatArrayElements(midPoint, midPoint_, JNI_ABORT);
    env->ReleaseFloatArrayElements(highlightScale, highlightScale_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nOutputColorSpace(JNIEnv* env, jclass, jlong nativeObject, jlong colorSpace) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->outputColorSpace(*(filament::color::ColorSpace*) colorSpace);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nFastMath(JNIEnv* env, jclass, jlong nativeObject, jboolean fastMath) {
    return (jlong) &((filament::ColorGrading::Builder*) nativeObject)->fastMath(fastMath);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_ColorGrading_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject, jlong engine) {
    return (jlong) ((filament::ColorGrading::Builder*) nativeObject)->build(*(filament::Engine*) engine);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Builder::customLut(utils::FixedCapacityVector<math::float3>, uint8_t): parameter "data" has unresolved type utils::FixedCapacityVector<math::float3>
//   - Builder::exportLut(ExportCallback _Nullable, void * _Nullable): parameter "callback": ExportCallback _Nullable needs a hand-written bridge to a Java object
