// This file has been generated by beamsplitter

#include <backend/DriverEnums.h>

#include <jni.h>

#include <string>

// Copies filament::backend::DescriptorSetLayoutDescriptor to and from its Java counterpart, member by member.
static filament::backend::DescriptorSetLayoutDescriptor readDescriptorSetLayoutDescriptor_generated(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::backend::DescriptorSetLayoutDescriptor out;
    out.type = (filament::backend::DescriptorType) env->GetIntField(obj, env->GetFieldID(cls, "type", "I"));
    out.stageFlags = (filament::backend::ShaderStageFlags) env->GetIntField(obj, env->GetFieldID(cls, "stageFlags", "I"));
    out.binding = env->GetByteField(obj, env->GetFieldID(cls, "binding", "B"));
    out.flags = (filament::backend::DescriptorFlags) env->GetIntField(obj, env->GetFieldID(cls, "flags", "I"));
    out.count = env->GetShortField(obj, env->GetFieldID(cls, "count", "S"));
    return out;
}

static jobject writeDescriptorSetLayoutDescriptor_generated(JNIEnv* env, const filament::backend::DescriptorSetLayoutDescriptor& in) {
    jclass cls = env->FindClass("com/google/android/filament/DescriptorSetLayoutDescriptor_generated");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetIntField(obj, env->GetFieldID(cls, "type", "I"), (jint) in.type);
    env->SetIntField(obj, env->GetFieldID(cls, "stageFlags", "I"), (jint) in.stageFlags);
    env->SetByteField(obj, env->GetFieldID(cls, "binding", "B"), (jbyte) in.binding);
    env->SetIntField(obj, env->GetFieldID(cls, "flags", "I"), (jint) in.flags);
    env->SetShortField(obj, env->GetFieldID(cls, "count", "S"), (jshort) in.count);
    return obj;
}


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_DescriptorSetLayoutDescriptor_1generated_nIsSampler(JNIEnv* env, jclass, jint type) {
    return (jboolean) filament::backend::DescriptorSetLayoutDescriptor::isSampler((filament::backend::DescriptorType) type);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_DescriptorSetLayoutDescriptor_1generated_nIsBuffer(JNIEnv* env, jclass, jint type) {
    return (jboolean) filament::backend::DescriptorSetLayoutDescriptor::isBuffer((filament::backend::DescriptorType) type);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
