// This file has been generated by beamsplitter

#include <filament/ToneMapper.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_DisplayRangeToneMapper_1generated_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::DisplayRangeToneMapper*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_DisplayRangeToneMapper_1generated_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::DisplayRangeToneMapper();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_DisplayRangeToneMapper_1generated_nCall(JNIEnv* env, jclass, jlong nativeObject, jfloatArray c, jfloatArray out_) {
    jfloat* c_ = env->GetFloatArrayElements(c, nullptr);
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec3<float>*>(out) = ((filament::DisplayRangeToneMapper*) nativeObject)->operator()(*reinterpret_cast<filament::math::details::TVec3<float>*>(c_));
    env->ReleaseFloatArrayElements(c, c_, JNI_ABORT);
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_DisplayRangeToneMapper_1generated_nIsOneDimensional(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::DisplayRangeToneMapper*) nativeObject)->isOneDimensional();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_DisplayRangeToneMapper_1generated_nIsLDR(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::DisplayRangeToneMapper*) nativeObject)->isLDR();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
