// This file has been generated by beamsplitter

#include <filament/Engine.h>
#include <utils/Entity.h>

#include <jni.h>

#include <string>

// Copies filament::Engine::Config to and from its Java counterpart, member by member.
static filament::Engine::Config readEngine_generated_Config(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::Engine::Config out;
    out.commandBufferSizeMB = env->GetIntField(obj, env->GetFieldID(cls, "commandBufferSizeMB", "I"));
    out.perRenderPassArenaSizeMB = env->GetIntField(obj, env->GetFieldID(cls, "perRenderPassArenaSizeMB", "I"));
    out.driverHandleArenaSizeMB = env->GetIntField(obj, env->GetFieldID(cls, "driverHandleArenaSizeMB", "I"));
    out.minCommandBufferSizeMB = env->GetIntField(obj, env->GetFieldID(cls, "minCommandBufferSizeMB", "I"));
    out.perFrameCommandsSizeMB = env->GetIntField(obj, env->GetFieldID(cls, "perFrameCommandsSizeMB", "I"));
    out.jobSystemThreadCount = env->GetIntField(obj, env->GetFieldID(cls, "jobSystemThreadCount", "I"));
    out.metalUploadBufferSizeBytes = env->GetLongField(obj, env->GetFieldID(cls, "metalUploadBufferSizeBytes", "J"));
    out.metalDisablePanicOnDrawableFailure = env->GetBooleanField(obj, env->GetFieldID(cls, "metalDisablePanicOnDrawableFailure", "Z"));
    out.disableParallelShaderCompile = env->GetBooleanField(obj, env->GetFieldID(cls, "disableParallelShaderCompile", "Z"));
    out.stereoscopicType = (filament::backend::Platform::StereoscopicType) env->GetIntField(obj, env->GetFieldID(cls, "stereoscopicType", "I"));
    out.stereoscopicEyeCount = env->GetByteField(obj, env->GetFieldID(cls, "stereoscopicEyeCount", "B"));
    out.resourceAllocatorCacheSizeMB = env->GetIntField(obj, env->GetFieldID(cls, "resourceAllocatorCacheSizeMB", "I"));
    out.resourceAllocatorCacheMaxAge = env->GetIntField(obj, env->GetFieldID(cls, "resourceAllocatorCacheMaxAge", "I"));
    out.disableHandleUseAfterFreeCheck = env->GetBooleanField(obj, env->GetFieldID(cls, "disableHandleUseAfterFreeCheck", "Z"));
    out.preferredShaderLanguage = (filament::Engine::Config::ShaderLanguage) env->GetIntField(obj, env->GetFieldID(cls, "preferredShaderLanguage", "I"));
    out.forceGLES2Context = env->GetBooleanField(obj, env->GetFieldID(cls, "forceGLES2Context", "Z"));
    out.assertNativeWindowIsValid = env->GetBooleanField(obj, env->GetFieldID(cls, "assertNativeWindowIsValid", "Z"));
    out.gpuContextPriority = (filament::backend::Platform::GpuContextPriority) env->GetIntField(obj, env->GetFieldID(cls, "gpuContextPriority", "I"));
    out.sharedUboInitialSizeInBytes = env->GetIntField(obj, env->GetFieldID(cls, "sharedUboInitialSizeInBytes", "I"));
    out.asynchronousMode = (filament::backend::Platform::AsynchronousMode) env->GetIntField(obj, env->GetFieldID(cls, "asynchronousMode", "I"));
    out.materialCacheCapacity = env->GetIntField(obj, env->GetFieldID(cls, "materialCacheCapacity", "I"));
    out.programCacheCapacity = env->GetIntField(obj, env->GetFieldID(cls, "programCacheCapacity", "I"));
    out.enableMultipleDirectionalLights = env->GetBooleanField(obj, env->GetFieldID(cls, "enableMultipleDirectionalLights", "Z"));
    return out;
}

static jobject writeEngine_generated_Config(JNIEnv* env, const filament::Engine::Config& in) {
    jclass cls = env->FindClass("com/google/android/filament/Engine_generated$Config");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetIntField(obj, env->GetFieldID(cls, "commandBufferSizeMB", "I"), (jint) in.commandBufferSizeMB);
    env->SetIntField(obj, env->GetFieldID(cls, "perRenderPassArenaSizeMB", "I"), (jint) in.perRenderPassArenaSizeMB);
    env->SetIntField(obj, env->GetFieldID(cls, "driverHandleArenaSizeMB", "I"), (jint) in.driverHandleArenaSizeMB);
    env->SetIntField(obj, env->GetFieldID(cls, "minCommandBufferSizeMB", "I"), (jint) in.minCommandBufferSizeMB);
    env->SetIntField(obj, env->GetFieldID(cls, "perFrameCommandsSizeMB", "I"), (jint) in.perFrameCommandsSizeMB);
    env->SetIntField(obj, env->GetFieldID(cls, "jobSystemThreadCount", "I"), (jint) in.jobSystemThreadCount);
    env->SetLongField(obj, env->GetFieldID(cls, "metalUploadBufferSizeBytes", "J"), (jlong) in.metalUploadBufferSizeBytes);
    env->SetBooleanField(obj, env->GetFieldID(cls, "metalDisablePanicOnDrawableFailure", "Z"), (jboolean) in.metalDisablePanicOnDrawableFailure);
    env->SetBooleanField(obj, env->GetFieldID(cls, "disableParallelShaderCompile", "Z"), (jboolean) in.disableParallelShaderCompile);
    env->SetIntField(obj, env->GetFieldID(cls, "stereoscopicType", "I"), (jint) in.stereoscopicType);
    env->SetByteField(obj, env->GetFieldID(cls, "stereoscopicEyeCount", "B"), (jbyte) in.stereoscopicEyeCount);
    env->SetIntField(obj, env->GetFieldID(cls, "resourceAllocatorCacheSizeMB", "I"), (jint) in.resourceAllocatorCacheSizeMB);
    env->SetIntField(obj, env->GetFieldID(cls, "resourceAllocatorCacheMaxAge", "I"), (jint) in.resourceAllocatorCacheMaxAge);
    env->SetBooleanField(obj, env->GetFieldID(cls, "disableHandleUseAfterFreeCheck", "Z"), (jboolean) in.disableHandleUseAfterFreeCheck);
    env->SetIntField(obj, env->GetFieldID(cls, "preferredShaderLanguage", "I"), (jint) in.preferredShaderLanguage);
    env->SetBooleanField(obj, env->GetFieldID(cls, "forceGLES2Context", "Z"), (jboolean) in.forceGLES2Context);
    env->SetBooleanField(obj, env->GetFieldID(cls, "assertNativeWindowIsValid", "Z"), (jboolean) in.assertNativeWindowIsValid);
    env->SetIntField(obj, env->GetFieldID(cls, "gpuContextPriority", "I"), (jint) in.gpuContextPriority);
    env->SetIntField(obj, env->GetFieldID(cls, "sharedUboInitialSizeInBytes", "I"), (jint) in.sharedUboInitialSizeInBytes);
    env->SetIntField(obj, env->GetFieldID(cls, "asynchronousMode", "I"), (jint) in.asynchronousMode);
    env->SetIntField(obj, env->GetFieldID(cls, "materialCacheCapacity", "I"), (jint) in.materialCacheCapacity);
    env->SetIntField(obj, env->GetFieldID(cls, "programCacheCapacity", "I"), (jint) in.programCacheCapacity);
    env->SetBooleanField(obj, env->GetFieldID(cls, "enableMultipleDirectionalLights", "Z"), (jboolean) in.enableMultipleDirectionalLights);
    return obj;
}


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyEngine(JNIEnv* env, jclass, jlong engine) {
    filament::Engine::destroy((filament::Engine*) engine);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Engine_1generated_nGetSupportedFeatureLevel(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Engine*) nativeObject)->getSupportedFeatureLevel();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Engine_1generated_nSetActiveFeatureLevel(JNIEnv* env, jclass, jlong nativeObject, jint featureLevel) {
    return (jint) ((filament::Engine*) nativeObject)->setActiveFeatureLevel((filament::backend::FeatureLevel) featureLevel);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Engine_1generated_nGetActiveFeatureLevel(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Engine*) nativeObject)->getActiveFeatureLevel();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetMaxAutomaticInstances(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getMaxAutomaticInstances();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsStereoSupported(JNIEnv* env, jclass, jlong nativeObject, jint stereoscopicType) {
    return (jboolean) ((filament::Engine*) nativeObject)->isStereoSupported((filament::backend::Platform::StereoscopicType) stereoscopicType);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsAsynchronousModeEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Engine*) nativeObject)->isAsynchronousModeEnabled();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nHasUnrecoverableFailure(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Engine*) nativeObject)->hasUnrecoverableFailure();
}

extern "C" JNIEXPORT jobject JNICALL
Java_com_google_android_filament_Engine_1generated_nGetConfig(JNIEnv* env, jclass, jlong nativeObject) {
    return writeEngine_generated_Config(env, ((filament::Engine*) nativeObject)->getConfig());
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetMaxStereoscopicEyes(JNIEnv* env, jclass) {
    return (jlong) filament::Engine::getMaxStereoscopicEyes();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetEntityManager(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) &((filament::Engine*) nativeObject)->getEntityManager();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetRenderableManager(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) &((filament::Engine*) nativeObject)->getRenderableManager();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetLightManager(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) &((filament::Engine*) nativeObject)->getLightManager();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetTransformManager(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) &((filament::Engine*) nativeObject)->getTransformManager();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nEnableAccurateTranslations(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Engine*) nativeObject)->enableAccurateTranslations();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nSetAutomaticInstancingEnabled(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    ((filament::Engine*) nativeObject)->setAutomaticInstancingEnabled(enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsAutomaticInstancingEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Engine*) nativeObject)->isAutomaticInstancingEnabled();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateSwapChain(JNIEnv* env, jclass, jlong nativeObject, jint width, jint height, jlong flags) {
    return (jlong) ((filament::Engine*) nativeObject)->createSwapChain(width, height, flags);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateRenderer(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->createRenderer();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateView(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->createView();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateScene(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->createScene();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateCamera(JNIEnv* env, jclass, jlong nativeObject, jint entity) {
    return (jlong) ((filament::Engine*) nativeObject)->createCamera(utils::Entity::import(entity));
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetCameraComponent(JNIEnv* env, jclass, jlong nativeObject, jint entity) {
    return (jlong) ((filament::Engine*) nativeObject)->getCameraComponent(utils::Entity::import(entity));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyCameraComponent(JNIEnv* env, jclass, jlong nativeObject, jint entity) {
    ((filament::Engine*) nativeObject)->destroyCameraComponent(utils::Entity::import(entity));
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateFence(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->createFence();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nCreateSync(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->createSync();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyBufferObject(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::BufferObject*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyVertexBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::VertexBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyFence(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Fence*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroySync(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Sync*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyIndexBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::IndexBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroySkinningBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::SkinningBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyMorphTargetBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::MorphTargetBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyIndirectLight(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::IndirectLight*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyMaterial(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Material*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyMaterialInstance(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::MaterialInstance*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyRenderer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Renderer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyFramePacer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::FramePacer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyScene(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Scene*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroySkybox(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Skybox*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyColorGrading(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::ColorGrading*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroySwapChain(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::SwapChain*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyStream(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Stream*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyTexture(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::Texture*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyRenderTarget(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::RenderTarget*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyView(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::View*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroyInstanceBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->destroy((filament::InstanceBuffer*) p);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nDestroy(JNIEnv* env, jclass, jlong nativeObject, jint e) {
    ((filament::Engine*) nativeObject)->destroy(utils::Entity::import(e));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidBufferObject(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::BufferObject*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidVertexBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::VertexBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidFence(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Fence*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidSync(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Sync*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidIndexBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::IndexBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidSkinningBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::SkinningBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidMorphTargetBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::MorphTargetBuffer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidIndirectLight(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::IndirectLight*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidMaterial(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Material*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValid(JNIEnv* env, jclass, jlong nativeObject, jlong m, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Material*) m, (filament::MaterialInstance*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidExpensive(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValidExpensive((filament::MaterialInstance*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidRenderer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Renderer*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidScene(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Scene*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidSkybox(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Skybox*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidColorGrading(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::ColorGrading*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidSwapChain(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::SwapChain*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidStream(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Stream*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidTexture(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::Texture*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidRenderTarget(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::RenderTarget*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidView(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::View*) p);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsValidInstanceBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong p) {
    return (jboolean) ((filament::Engine*) nativeObject)->isValid((filament::InstanceBuffer*) p);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetBufferObjectCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getBufferObjectCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetViewCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getViewCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetSceneCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getSceneCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetSwapChainCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getSwapChainCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetStreamCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getStreamCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetIndexBufferCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getIndexBufferCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetSkinningBufferCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getSkinningBufferCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetMorphTargetBufferCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getMorphTargetBufferCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetInstanceBufferCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getInstanceBufferCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetVertexBufferCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getVertexBufferCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetIndirectLightCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getIndirectLightCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetMaterialCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getMaterialCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetTextureCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getTextureCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetSkyboxeCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getSkyboxeCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetColorGradingCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getColorGradingCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetRenderTargetCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getRenderTargetCount();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nCancelAsyncCall(JNIEnv* env, jclass, jlong nativeObject, jint id) {
    return (jboolean) ((filament::Engine*) nativeObject)->cancelAsyncCall(id);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nFlushAndWait__J(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Engine*) nativeObject)->flushAndWait();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nFlushAndWait__JJ(JNIEnv* env, jclass, jlong nativeObject, jlong timeout) {
    return (jboolean) ((filament::Engine*) nativeObject)->flushAndWait(timeout);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nFlush(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Engine*) nativeObject)->flush();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nIsPaused(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Engine*) nativeObject)->isPaused();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nSetPaused(JNIEnv* env, jclass, jlong nativeObject, jboolean paused) {
    ((filament::Engine*) nativeObject)->setPaused(paused);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nPumpMessageQueues(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Engine*) nativeObject)->pumpMessageQueues();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nUnprotected(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Engine*) nativeObject)->unprotected();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetDefaultMaterial(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getDefaultMaterial();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Engine_1generated_nGetBackend(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Engine*) nativeObject)->getBackend();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetPlatform(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine*) nativeObject)->getPlatform();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_nExecute(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Engine*) nativeObject)->execute();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetSteadyClockTimeNano(JNIEnv* env, jclass) {
    return (jlong) filament::Engine::getSteadyClockTimeNano();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_nGetDebugRegistry(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) &((filament::Engine*) nativeObject)->getDebugRegistry();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nHasFeatureFlag(JNIEnv* env, jclass, jlong nativeObject, jstring name) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jboolean result = (jboolean) ((filament::Engine*) nativeObject)->hasFeatureFlag(name_);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Engine_1generated_nSetFeatureFlag(JNIEnv* env, jclass, jlong nativeObject, jstring name, jboolean value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jboolean result = (jboolean) ((filament::Engine*) nativeObject)->setFeatureFlag(name_, value);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::Engine::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::Engine::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nBackend(JNIEnv* env, jclass, jlong nativeObject, jint backend) {
    return (jlong) &((filament::Engine::Builder*) nativeObject)->backend((filament::backend::Backend) backend);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nPlatform(JNIEnv* env, jclass, jlong nativeObject, jlong platform) {
    return (jlong) &((filament::Engine::Builder*) nativeObject)->platform((filament::backend::Platform*) platform);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nConfig(JNIEnv* env, jclass, jlong nativeObject, jlong config) {
    return (jlong) &((filament::Engine::Builder*) nativeObject)->config((filament::Engine::Config*) config);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nFeatureLevel(JNIEnv* env, jclass, jlong nativeObject, jint featureLevel) {
    return (jlong) &((filament::Engine::Builder*) nativeObject)->featureLevel((filament::backend::FeatureLevel) featureLevel);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nPaused(JNIEnv* env, jclass, jlong nativeObject, jboolean paused) {
    return (jlong) &((filament::Engine::Builder*) nativeObject)->paused(paused);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nFeature(JNIEnv* env, jclass, jlong nativeObject, jstring name, jboolean value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jlong result = (jlong) &((filament::Engine::Builder*) nativeObject)->feature(name_, value);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nColorGrading(JNIEnv* env, jclass, jlong nativeObject, jlong colorGrading) {
    return (jlong) &((filament::Engine::Builder*) nativeObject)->colorGrading(*(filament::ColorGrading::Builder*) colorGrading);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Engine_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Engine::Builder*) nativeObject)->build();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Engine::getFeatureFlags() const: returns unresolved type utils::Slice<const FeatureFlag>
//   - Engine::create(Backend, Platform * _Nullable, void * _Nullable, const Config * _Nullable): parameter "sharedContext": void * _Nullable is opaque, so there is nothing to marshal
//   - Engine::createAsync(CreateCallback *, void * _Nullable, Backend, Platform * _Nullable, void * _Nullable, const Config * _Nullable): parameter "callback" has unresolved type CreateCallback *
//   - Engine::getEngine(void * _Nonnull): parameter "token": void * _Nonnull is opaque, so there is nothing to marshal
//   - Engine::getDriver() const: returns unresolved type const backend::Driver * _Nonnull
//   - Engine::destroy(Engine * _Nullable * _Nullable): parameter "engine" has unresolved type Engine * _Nullable * _Nullable
//   - Engine::createSwapChain(void * _Nullable, uint64_t): parameter "nativeWindow": void * _Nullable is opaque, so there is nothing to marshal
//   - Engine::runCommandAsync(utils::Invocable<void ()> &&, backend::CallbackHandler * _Nullable, AsyncCompletionCallback, void * _Nullable): parameter "command": takes utils::Invocable<void ()> &&, and Java has no way to move a value
//   - Engine::streamAlloc(size_t, size_t): return type: void * _Nullable is opaque, so there is nothing to marshal
//   - Engine::getJobSystem(): returns unresolved type utils::JobSystem &
//   - Engine::getFeatureFlag(const char * _Nonnull) const: returns unresolved type std::optional<bool>
//   - Engine::getFeatureFlagPtr(const char * _Nonnull) const: returns bool * _Nullable, an array with no length
//   - Engine::compile(backend::CompilerPriorityQueue, const Material * _Nonnull, const View * _Nonnull, utils::tribool, utils::tribool, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "shadowReceiver": utils::tribool crosses by copy, and Java has no value type
//   - Builder::sharedContext(void * _Nullable): parameter "sharedContext": void * _Nullable is opaque, so there is nothing to marshal
//   - Builder::features(std::initializer_list<const char *>): parameter "list" has unresolved type std::initializer_list<const char *>
//   - Builder::build(utils::Invocable<void (void * _Nonnull)> &&) const: parameter "callback": takes utils::Invocable<void (void * _Nonnull)> &&, and Java has no way to move a value
