// This file has been generated by beamsplitter

#include <filament/FramePipelineEstimator.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jdouble JNICALL
Java_com_google_android_filament_FramePipelineEstimator_1generated_nGetZScore(JNIEnv* env, jclass, jint targetPercentile) {
    return (jdouble) filament::FramePipelineEstimator::getZScore((filament::FramePipelineEstimator::TargetPercentile) targetPercentile);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - FramePipelineEstimator::estimateWorkload(FrameInfoHistory, TargetPercentile): parameter "history": FrameInfoHistory crosses by copy, and Java has no value type
//   - FramePipelineEstimator::estimateWorkload(FrameInfoHistory, double): parameter "history": FrameInfoHistory crosses by copy, and Java has no value type
//   - FramePipelineEstimator::estimatePacing(FrameInfoHistory, std::chrono::nanoseconds, TargetPercentile): parameter "pacingPeriod" has unresolved type std::chrono::nanoseconds
//   - FramePipelineEstimator::estimatePacing(FrameInfoHistory, std::chrono::nanoseconds, double): parameter "pacingPeriod" has unresolved type std::chrono::nanoseconds
