// This file has been generated by beamsplitter

#include <filament/IndirectLight.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nSetIntensity(JNIEnv* env, jclass, jlong nativeObject, jfloat intensity) {
    ((filament::IndirectLight*) nativeObject)->setIntensity(intensity);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetIntensity(JNIEnv* env, jclass, jlong nativeObject) {
    return (jfloat) ((filament::IndirectLight*) nativeObject)->getIntensity();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nSetRotation(JNIEnv* env, jclass, jlong nativeObject, jfloatArray rotation) {
    jfloat* rotation_ = env->GetFloatArrayElements(rotation, nullptr);
    ((filament::IndirectLight*) nativeObject)->setRotation(*reinterpret_cast<filament::math::details::TMat33<float>*>(rotation_));
    env->ReleaseFloatArrayElements(rotation, rotation_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetRotation(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out_) {
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TMat33<float>*>(out) = ((filament::IndirectLight*) nativeObject)->getRotation();
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetReflectionsTexture(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::IndirectLight*) nativeObject)->getReflectionsTexture();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetIrradianceTexture(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::IndirectLight*) nativeObject)->getIrradianceTexture();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetDirectionEstimate___3F_3F(JNIEnv* env, jclass, jfloatArray sh, jfloatArray out_) {
    jfloat* sh_ = env->GetFloatArrayElements(sh, nullptr);
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec3<float>*>(out) = filament::IndirectLight::getDirectionEstimate(reinterpret_cast<const filament::math::details::TVec3<float>*>(sh_));
    env->ReleaseFloatArrayElements(sh, sh_, JNI_ABORT);
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetColorEstimate___3F_3F_3F(JNIEnv* env, jclass, jfloatArray sh, jfloatArray direction, jfloatArray out_) {
    jfloat* sh_ = env->GetFloatArrayElements(sh, nullptr);
    jfloat* direction_ = env->GetFloatArrayElements(direction, nullptr);
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec4<float>*>(out) = filament::IndirectLight::getColorEstimate(reinterpret_cast<const filament::math::details::TVec3<float>*>(sh_), *reinterpret_cast<filament::math::details::TVec3<float>*>(direction_));
    env->ReleaseFloatArrayElements(sh, sh_, JNI_ABORT);
    env->ReleaseFloatArrayElements(direction, direction_, JNI_ABORT);
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetDirectionEstimate__J_3F(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out_) {
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec3<float>*>(out) = ((filament::IndirectLight*) nativeObject)->getDirectionEstimate();
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_nGetColorEstimate__J_3F_3F(JNIEnv* env, jclass, jlong nativeObject, jfloatArray direction, jfloatArray out_) {
    jfloat* direction_ = env->GetFloatArrayElements(direction, nullptr);
    jfloat* out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<filament::math::details::TVec4<float>*>(out) = ((filament::IndirectLight*) nativeObject)->getColorEstimate(*reinterpret_cast<filament::math::details::TVec3<float>*>(direction_));
    env->ReleaseFloatArrayElements(direction, direction_, JNI_ABORT);
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::IndirectLight::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::IndirectLight::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nReflections(JNIEnv* env, jclass, jlong nativeObject, jlong cubemap) {
    return (jlong) &((filament::IndirectLight::Builder*) nativeObject)->reflections((filament::Texture*) cubemap);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nIrradiance__JB_3F(JNIEnv* env, jclass, jlong nativeObject, jbyte bands, jfloatArray sh) {
    jfloat* sh_ = env->GetFloatArrayElements(sh, nullptr);
    jlong result = (jlong) &((filament::IndirectLight::Builder*) nativeObject)->irradiance(bands, reinterpret_cast<const filament::math::details::TVec3<float>*>(sh_));
    env->ReleaseFloatArrayElements(sh, sh_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nRadiance(JNIEnv* env, jclass, jlong nativeObject, jbyte bands, jfloatArray sh) {
    jfloat* sh_ = env->GetFloatArrayElements(sh, nullptr);
    jlong result = (jlong) &((filament::IndirectLight::Builder*) nativeObject)->radiance(bands, reinterpret_cast<const filament::math::details::TVec3<float>*>(sh_));
    env->ReleaseFloatArrayElements(sh, sh_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nIrradiance__JJ(JNIEnv* env, jclass, jlong nativeObject, jlong cubemap) {
    return (jlong) &((filament::IndirectLight::Builder*) nativeObject)->irradiance((filament::Texture*) cubemap);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nIntensity(JNIEnv* env, jclass, jlong nativeObject, jfloat envIntensity) {
    return (jlong) &((filament::IndirectLight::Builder*) nativeObject)->intensity(envIntensity);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nRotation(JNIEnv* env, jclass, jlong nativeObject, jfloatArray rotation) {
    jfloat* rotation_ = env->GetFloatArrayElements(rotation, nullptr);
    jlong result = (jlong) &((filament::IndirectLight::Builder*) nativeObject)->rotation(*reinterpret_cast<filament::math::details::TMat33<float>*>(rotation_));
    env->ReleaseFloatArrayElements(rotation, rotation_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_IndirectLight_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject, jlong engine) {
    return (jlong) ((filament::IndirectLight::Builder*) nativeObject)->build(*(filament::Engine*) engine);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
