// This file has been generated by beamsplitter

#include <filament/Material.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_nCreateInstance(JNIEnv* env, jclass, jlong nativeObject, jstring name) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jlong result = (jlong) ((filament::Material*) nativeObject)->createInstance(name_);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_Material_1generated_nGetName(JNIEnv* env, jclass, jlong nativeObject) {
    return env->NewStringUTF(((filament::Material*) nativeObject)->getName());
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetShading(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getShading();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetInterpolation(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getInterpolation();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetBlendingMode(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getBlendingMode();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetVertexDomain(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getVertexDomain();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetSupportedVariants(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getSupportedVariants();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetMaterialDomain(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getMaterialDomain();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetCullingMode(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getCullingMode();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetTransparencyMode(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getTransparencyMode();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nIsColorWriteEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->isColorWriteEnabled();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nIsDepthWriteEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->isDepthWriteEnabled();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nIsDepthCullingEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->isDepthCullingEnabled();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nIsDoubleSided(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->isDoubleSided();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nIsAlphaToCoverageEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->isAlphaToCoverageEnabled();
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_Material_1generated_nGetMaskThreshold(JNIEnv* env, jclass, jlong nativeObject) {
    return (jfloat) ((filament::Material*) nativeObject)->getMaskThreshold();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nHasShadowMultiplier(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->hasShadowMultiplier();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nHasSpecularAntiAliasing(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Material*) nativeObject)->hasSpecularAntiAliasing();
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_Material_1generated_nGetSpecularAntiAliasingVariance(JNIEnv* env, jclass, jlong nativeObject) {
    return (jfloat) ((filament::Material*) nativeObject)->getSpecularAntiAliasingVariance();
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_Material_1generated_nGetSpecularAntiAliasingThreshold(JNIEnv* env, jclass, jlong nativeObject) {
    return (jfloat) ((filament::Material*) nativeObject)->getSpecularAntiAliasingThreshold();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetRefractionMode(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getRefractionMode();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetRefractionType(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getRefractionType();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetReflectionMode(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getReflectionMode();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Material_1generated_nGetFeatureLevel(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Material*) nativeObject)->getFeatureLevel();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_nGetParameterCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Material*) nativeObject)->getParameterCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_nGetParameters(JNIEnv* env, jclass, jlong nativeObject, jlong parameters, jlong count) {
    return (jlong) ((filament::Material*) nativeObject)->getParameters((filament::Material::ParameterInfo*) parameters, count);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Material_1generated_nIsSampler(JNIEnv* env, jclass, jlong nativeObject, jstring name) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jboolean result = (jboolean) ((filament::Material*) nativeObject)->isSampler(name_);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_Material_1generated_nGetSource(JNIEnv* env, jclass, jlong nativeObject) {
    return env->NewStringUTF(std::string(((filament::Material*) nativeObject)->getSource()).c_str());
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_Material_1generated_nGetParameterTransformName(JNIEnv* env, jclass, jlong nativeObject, jstring samplerName) {
    const char* samplerName_ = env->GetStringUTFChars(samplerName, nullptr);
    jstring result = env->NewStringUTF(((filament::Material*) nativeObject)->getParameterTransformName(samplerName_));
    env->ReleaseStringUTFChars(samplerName, samplerName_);
    return result;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameter__JLjava_lang_String_2Z(JNIEnv* env, jclass, jlong nativeObject, jstring name, jboolean value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<bool>(name_, value);
    env->ReleaseStringUTFChars(name, name_);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterInt(JNIEnv* env, jclass, jlong nativeObject, jstring name, jint value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<int32_t>(name_, value);
    env->ReleaseStringUTFChars(name, name_);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterString(JNIEnv* env, jclass, jlong nativeObject, jstring name, jint value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<uint32_t>(name_, value);
    env->ReleaseStringUTFChars(name, name_);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameter__JLjava_lang_String_2F(JNIEnv* env, jclass, jlong nativeObject, jstring name, jfloat value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<float>(name_, value);
    env->ReleaseStringUTFChars(name, name_);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterFloat2(JNIEnv* env, jclass, jlong nativeObject, jstring name, jfloatArray value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* value_ = env->GetFloatArrayElements(value, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<filament::math::float2>(name_, *reinterpret_cast<filament::math::details::TVec2<float>*>(value_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(value, value_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterFloat3__JLjava_lang_String_2_3F(JNIEnv* env, jclass, jlong nativeObject, jstring name, jfloatArray value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* value_ = env->GetFloatArrayElements(value, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<filament::math::float3>(name_, *reinterpret_cast<filament::math::details::TVec3<float>*>(value_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(value, value_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterFloat4__JLjava_lang_String_2_3F(JNIEnv* env, jclass, jlong nativeObject, jstring name, jfloatArray value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* value_ = env->GetFloatArrayElements(value, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<filament::math::float4>(name_, *reinterpret_cast<filament::math::details::TVec4<float>*>(value_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(value, value_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterMat3f(JNIEnv* env, jclass, jlong nativeObject, jstring name, jfloatArray value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* value_ = env->GetFloatArrayElements(value, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<filament::math::mat3f>(name_, *reinterpret_cast<filament::math::details::TMat33<float>*>(value_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(value, value_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterMat4f(JNIEnv* env, jclass, jlong nativeObject, jstring name, jfloatArray value) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* value_ = env->GetFloatArrayElements(value, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter<filament::math::mat4f>(name_, *reinterpret_cast<filament::math::details::TMat44<float>*>(value_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(value, value_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameter__JLjava_lang_String_2JJ(JNIEnv* env, jclass, jlong nativeObject, jstring name, jlong texture, jlong sampler) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter(name_, (filament::Texture*) texture, *(filament::TextureSampler*) sampler);
    env->ReleaseStringUTFChars(name, name_);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterFloat3__JLjava_lang_String_2I_3F(JNIEnv* env, jclass, jlong nativeObject, jstring name, jint type, jfloatArray color) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* color_ = env->GetFloatArrayElements(color, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter(name_, (filament::RgbType) type, *reinterpret_cast<filament::math::details::TVec3<float>*>(color_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(color, color_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_nSetDefaultParameterFloat4__JLjava_lang_String_2I_3F(JNIEnv* env, jclass, jlong nativeObject, jstring name, jint type, jfloatArray color) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jfloat* color_ = env->GetFloatArrayElements(color, nullptr);
    ((filament::Material*) nativeObject)->setDefaultParameter(name_, (filament::RgbaType) type, *reinterpret_cast<filament::math::details::TVec4<float>*>(color_));
    env->ReleaseStringUTFChars(name, name_);
    env->ReleaseFloatArrayElements(color, color_, JNI_ABORT);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_nGetDefaultInstance(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Material*) nativeObject)->getDefaultInstance();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Material_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::Material::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::Material::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_00024Builder_nSphericalHarmonicsBandCount(JNIEnv* env, jclass, jlong nativeObject, jlong shBandCount) {
    return (jlong) &((filament::Material::Builder*) nativeObject)->sphericalHarmonicsBandCount(shBandCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_00024Builder_nShadowSamplingQuality(JNIEnv* env, jclass, jlong nativeObject, jint quality) {
    return (jlong) &((filament::Material::Builder*) nativeObject)->shadowSamplingQuality((filament::Material::Builder::ShadowSamplingQuality) quality);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_00024Builder_nUboBatching(JNIEnv* env, jclass, jlong nativeObject, jint uboBatchingMode) {
    return (jlong) &((filament::Material::Builder*) nativeObject)->uboBatching((filament::Material::UboBatchingMode) uboBatchingMode);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Material_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject, jlong engine) {
    return (jlong) ((filament::Material::Builder*) nativeObject)->build(*(filament::Engine*) engine);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Material::compile(CompilerPriorityQueue, UserVariantFilterMask, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (Material * _Nonnull)> &&, and Java has no way to move a value
//   - Material::compile(CompilerPriorityQueue, UserVariantFilterBit, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (Material * _Nonnull)> &&, and Java has no way to move a value
//   - Material::compile(CompilerPriorityQueue, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (Material * _Nonnull)> &&, and Java has no way to move a value
//   - Material::getRequiredAttributes() const: return type: AttributeBitset crosses by copy, and Java has no value type
//   - Material::hasParameter(const char * _Nonnull) const: 2 bound methods share the target key "hasParameter(Ljava/lang/String;)"
//   - Material::hasParameter(std::string_view) const: 2 bound methods share the target key "hasParameter(Ljava/lang/String;)"
//   - Builder::package(const void * _Nonnull, size_t): parameter "payload": const void * _Nonnull is opaque, so there is nothing to marshal
