// This file has been generated by beamsplitter

#include <filament/MorphTargetBuffer.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nSetPositionsAtLong(JNIEnv* env, jclass, jlong nativeObject, jlong engine, jlong targetIndex, jfloatArray positions, jlong count, jlong offset) {
    jfloat* positions_ = env->GetFloatArrayElements(positions, nullptr);
    ((filament::MorphTargetBuffer*) nativeObject)->setPositionsAt(*(filament::Engine*) engine, targetIndex, reinterpret_cast<const filament::math::details::TVec3<float>*>(positions_), count, offset);
    env->ReleaseFloatArrayElements(positions, positions_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nSetPositionsAtFloat4(JNIEnv* env, jclass, jlong nativeObject, jlong engine, jlong targetIndex, jfloatArray positions, jlong count, jlong offset) {
    jfloat* positions_ = env->GetFloatArrayElements(positions, nullptr);
    ((filament::MorphTargetBuffer*) nativeObject)->setPositionsAt(*(filament::Engine*) engine, targetIndex, reinterpret_cast<const filament::math::details::TVec4<float>*>(positions_), count, offset);
    env->ReleaseFloatArrayElements(positions, positions_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nSetTangentsAt(JNIEnv* env, jclass, jlong nativeObject, jlong engine, jlong targetIndex, jshortArray tangents, jlong count, jlong offset) {
    jshort* tangents_ = env->GetShortArrayElements(tangents, nullptr);
    ((filament::MorphTargetBuffer*) nativeObject)->setTangentsAt(*(filament::Engine*) engine, targetIndex, reinterpret_cast<const filament::math::details::TVec4<short>*>(tangents_), count, offset);
    env->ReleaseShortArrayElements(tangents, tangents_, JNI_ABORT);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nGetVertexCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::MorphTargetBuffer*) nativeObject)->getVertexCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nGetCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::MorphTargetBuffer*) nativeObject)->getCount();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nHasPositions(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::MorphTargetBuffer*) nativeObject)->hasPositions();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nHasTangents(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::MorphTargetBuffer*) nativeObject)->hasTangents();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_nIsCustomMorphingEnabled(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::MorphTargetBuffer*) nativeObject)->isCustomMorphingEnabled();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::MorphTargetBuffer::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::MorphTargetBuffer::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nVertexCount(JNIEnv* env, jclass, jlong nativeObject, jlong vertexCount) {
    return (jlong) &((filament::MorphTargetBuffer::Builder*) nativeObject)->vertexCount(vertexCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nCount(JNIEnv* env, jclass, jlong nativeObject, jlong count) {
    return (jlong) &((filament::MorphTargetBuffer::Builder*) nativeObject)->count(count);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nName(JNIEnv* env, jclass, jlong nativeObject, jstring name, jlong len) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jlong result = (jlong) &((filament::MorphTargetBuffer::Builder*) nativeObject)->name(name_, len);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nWithPositions(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::MorphTargetBuffer::Builder*) nativeObject)->withPositions(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nWithTangents(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::MorphTargetBuffer::Builder*) nativeObject)->withTangents(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nEnableCustomMorphing(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::MorphTargetBuffer::Builder*) nativeObject)->enableCustomMorphing(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_MorphTargetBuffer_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject, jlong engine) {
    return (jlong) ((filament::MorphTargetBuffer::Builder*) nativeObject)->build(*(filament::Engine*) engine);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Builder::name(const utils::StaticString &): parameter "name" is utils::StaticString, which is not bound
