// This file has been generated by beamsplitter

#include <filament/RenderableManager.h>
#include <math/mat4.h>
#include <math/vec4.h>
#include <utils/Entity.h>

#include <jni.h>

#include <string>

// Copies filament::RenderableManager::Bone to and from its Java counterpart, member by member.
static filament::RenderableManager::Bone readRenderableManager_generated_Bone(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::RenderableManager::Bone out;
    {
        jfloatArray a = (jfloatArray) env->GetObjectField(obj, env->GetFieldID(cls, "unitQuaternion", "[F"));
        jfloat* p = env->GetFloatArrayElements(a, nullptr);
        out.unitQuaternion = *reinterpret_cast<filament::math::details::TQuaternion<float>*>(p);
        env->ReleaseFloatArrayElements(a, p, JNI_ABORT);
    }
    {
        jfloatArray a = (jfloatArray) env->GetObjectField(obj, env->GetFieldID(cls, "translation", "[F"));
        jfloat* p = env->GetFloatArrayElements(a, nullptr);
        out.translation = *reinterpret_cast<filament::math::details::TVec3<float>*>(p);
        env->ReleaseFloatArrayElements(a, p, JNI_ABORT);
    }
    out.reserved = env->GetFloatField(obj, env->GetFieldID(cls, "reserved", "F"));
    return out;
}

static jobject writeRenderableManager_generated_Bone(JNIEnv* env, const filament::RenderableManager::Bone& in) {
    jclass cls = env->FindClass("com/google/android/filament/RenderableManager_generated$Bone");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    {
        jfloatArray a = env->NewFloatArray(4);
        env->SetFloatArrayRegion(a, 0, 4, reinterpret_cast<const jfloat*>(&in.unitQuaternion));
        env->SetObjectField(obj, env->GetFieldID(cls, "unitQuaternion", "[F"), a);
    }
    {
        jfloatArray a = env->NewFloatArray(3);
        env->SetFloatArrayRegion(a, 0, 3, reinterpret_cast<const jfloat*>(&in.translation));
        env->SetObjectField(obj, env->GetFieldID(cls, "translation", "[F"), a);
    }
    env->SetFloatField(obj, env->GetFieldID(cls, "reserved", "F"), (jfloat) in.reserved);
    return obj;
}


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nHasComponent(JNIEnv* env, jclass, jlong nativeObject, jint e) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->hasComponent(utils::Entity::import(e));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetInstance(JNIEnv* env, jclass, jlong nativeObject, jint e) {
    return (jint) ((filament::RenderableManager*) nativeObject)->getInstance(utils::Entity::import(e));
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetComponentCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getComponentCount();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nEmpty(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->empty();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetEntity(JNIEnv* env, jclass, jlong nativeObject, jint i) {
    return (jint) utils::Entity::smuggle(((filament::RenderableManager*) nativeObject)->getEntity(i));
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetEntities(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getEntities();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nDestroy(JNIEnv* env, jclass, jlong nativeObject, jint e) {
    ((filament::RenderableManager*) nativeObject)->destroy(utils::Entity::import(e));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetAxisAlignedBoundingBox(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong aabb) {
    ((filament::RenderableManager*) nativeObject)->setAxisAlignedBoundingBox(instance, *(filament::Box*) aabb);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetAxisAlignedBoundingBox(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jlong) &((filament::RenderableManager*) nativeObject)->getAxisAlignedBoundingBox(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetLayerMask(JNIEnv* env, jclass, jlong nativeObject, jint instance, jbyte select, jbyte values) {
    ((filament::RenderableManager*) nativeObject)->setLayerMask(instance, select, values);
}

extern "C" JNIEXPORT jbyte JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetLayerMask(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jbyte) ((filament::RenderableManager*) nativeObject)->getLayerMask(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetPriority(JNIEnv* env, jclass, jlong nativeObject, jint instance, jbyte priority) {
    ((filament::RenderableManager*) nativeObject)->setPriority(instance, priority);
}

extern "C" JNIEXPORT jbyte JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetPriority(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jbyte) ((filament::RenderableManager*) nativeObject)->getPriority(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetChannel(JNIEnv* env, jclass, jlong nativeObject, jint instance, jbyte channel) {
    ((filament::RenderableManager*) nativeObject)->setChannel(instance, channel);
}

extern "C" JNIEXPORT jbyte JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetChannel(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jbyte) ((filament::RenderableManager*) nativeObject)->getChannel(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetCulling(JNIEnv* env, jclass, jlong nativeObject, jint instance, jboolean enable) {
    ((filament::RenderableManager*) nativeObject)->setCulling(instance, enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nIsCullingEnabled(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->isCullingEnabled(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetFogEnabled(JNIEnv* env, jclass, jlong nativeObject, jint instance, jboolean enable) {
    ((filament::RenderableManager*) nativeObject)->setFogEnabled(instance, enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetFogEnabled(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->getFogEnabled(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetLightChannel(JNIEnv* env, jclass, jlong nativeObject, jint instance, jint channel, jboolean enable) {
    ((filament::RenderableManager*) nativeObject)->setLightChannel(instance, channel, enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetLightChannel(JNIEnv* env, jclass, jlong nativeObject, jint instance, jint channel) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->getLightChannel(instance, channel);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetCastShadows(JNIEnv* env, jclass, jlong nativeObject, jint instance, jboolean enable) {
    ((filament::RenderableManager*) nativeObject)->setCastShadows(instance, enable);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetReceiveShadows(JNIEnv* env, jclass, jlong nativeObject, jint instance, jboolean enable) {
    ((filament::RenderableManager*) nativeObject)->setReceiveShadows(instance, enable);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetScreenSpaceContactShadows(JNIEnv* env, jclass, jlong nativeObject, jint instance, jboolean enable) {
    ((filament::RenderableManager*) nativeObject)->setScreenSpaceContactShadows(instance, enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nIsShadowCaster(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->isShadowCaster(instance);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nIsShadowReceiver(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->isShadowReceiver(instance);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nIsScreenSpaceContactShadowsEnabled(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->isScreenSpaceContactShadowsEnabled(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetBones__JIJJJ(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong transforms, jlong boneCount, jlong offset) {
    ((filament::RenderableManager*) nativeObject)->setBones(instance, (filament::RenderableManager::Bone*) transforms, boneCount, offset);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetBones__JI_3FJJ(JNIEnv* env, jclass, jlong nativeObject, jint instance, jfloatArray transforms, jlong boneCount, jlong offset) {
    jfloat* transforms_ = env->GetFloatArrayElements(transforms, nullptr);
    ((filament::RenderableManager*) nativeObject)->setBones(instance, reinterpret_cast<const filament::math::details::TMat44<float>*>(transforms_), boneCount, offset);
    env->ReleaseFloatArrayElements(transforms, transforms_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetSkinningBuffer(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong skinningBuffer, jlong count, jlong offset) {
    ((filament::RenderableManager*) nativeObject)->setSkinningBuffer(instance, (filament::SkinningBuffer*) skinningBuffer, count, offset);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetMorphWeights(JNIEnv* env, jclass, jlong nativeObject, jint instance, jfloatArray weights, jlong count, jlong offset) {
    jfloat* weights_ = env->GetFloatArrayElements(weights, nullptr);
    ((filament::RenderableManager*) nativeObject)->setMorphWeights(instance, reinterpret_cast<const float*>(weights_), count, offset);
    env->ReleaseFloatArrayElements(weights, weights_, JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetMorphTargetBufferOffsetAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jbyte level, jlong primitiveIndex, jlong offset) {
    ((filament::RenderableManager*) nativeObject)->setMorphTargetBufferOffsetAt(instance, level, primitiveIndex, offset);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetMorphTargetBuffer(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getMorphTargetBuffer(instance);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetMorphTargetCount(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getMorphTargetCount(instance);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetPrimitiveCount(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getPrimitiveCount(instance);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetInstanceCount(JNIEnv* env, jclass, jlong nativeObject, jint instance) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getInstanceCount(instance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetMaterialInstanceAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex, jlong materialInstance) {
    ((filament::RenderableManager*) nativeObject)->setMaterialInstanceAt(instance, primitiveIndex, (filament::MaterialInstance*) materialInstance);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nClearMaterialInstanceAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex) {
    ((filament::RenderableManager*) nativeObject)->clearMaterialInstanceAt(instance, primitiveIndex);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetMaterialInstanceAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex) {
    return (jlong) ((filament::RenderableManager*) nativeObject)->getMaterialInstanceAt(instance, primitiveIndex);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetGeometryAt__JIJIJJJJ(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex, jint type, jlong vertices, jlong indices, jlong offset, jlong count) {
    ((filament::RenderableManager*) nativeObject)->setGeometryAt(instance, primitiveIndex, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices, (filament::IndexBuffer*) indices, offset, count);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetGeometryAt__JIJIJJJ(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex, jint type, jlong vertices, jlong offset, jlong count) {
    ((filament::RenderableManager*) nativeObject)->setGeometryAt(instance, primitiveIndex, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices, offset, count);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetBlendOrderAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex, jshort order) {
    ((filament::RenderableManager*) nativeObject)->setBlendOrderAt(instance, primitiveIndex, order);
}

extern "C" JNIEXPORT jshort JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nGetBlendOrderAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex) {
    return (jshort) ((filament::RenderableManager*) nativeObject)->getBlendOrderAt(instance, primitiveIndex);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nSetGlobalBlendOrderEnabledAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex, jboolean enabled) {
    ((filament::RenderableManager*) nativeObject)->setGlobalBlendOrderEnabledAt(instance, primitiveIndex, enabled);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_RenderableManager_1generated_nIsGlobalBlendOrderEnabledAt(JNIEnv* env, jclass, jlong nativeObject, jint instance, jlong primitiveIndex) {
    return (jboolean) ((filament::RenderableManager*) nativeObject)->isGlobalBlendOrderEnabledAt(instance, primitiveIndex);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::RenderableManager::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nCreate(JNIEnv* env, jclass, jlong count) {
    return (jlong) new filament::RenderableManager::Builder(count);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGeometry__JJIJJJJJJ(JNIEnv* env, jclass, jlong nativeObject, jlong index, jint type, jlong vertices, jlong indices, jlong offset, jlong minIndex, jlong maxIndex, jlong count) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->geometry(index, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices, (filament::IndexBuffer*) indices, offset, minIndex, maxIndex, count);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGeometry__JJIJJJJ(JNIEnv* env, jclass, jlong nativeObject, jlong index, jint type, jlong vertices, jlong indices, jlong offset, jlong count) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->geometry(index, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices, (filament::IndexBuffer*) indices, offset, count);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGeometry__JJIJJ(JNIEnv* env, jclass, jlong nativeObject, jlong index, jint type, jlong vertices, jlong indices) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->geometry(index, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices, (filament::IndexBuffer*) indices);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGeometry__JJIJJJ(JNIEnv* env, jclass, jlong nativeObject, jlong index, jint type, jlong vertices, jlong offset, jlong count) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->geometry(index, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices, offset, count);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGeometry__JJIJ(JNIEnv* env, jclass, jlong nativeObject, jlong index, jint type, jlong vertices) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->geometry(index, (filament::backend::PrimitiveType) type, (filament::VertexBuffer*) vertices);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGeometryType(JNIEnv* env, jclass, jlong nativeObject, jint type) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->geometryType((filament::RenderableManager::Builder::GeometryType) type);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nMaterial(JNIEnv* env, jclass, jlong nativeObject, jlong index, jlong materialInstance) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->material(index, (filament::MaterialInstance*) materialInstance);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nBoundingBox(JNIEnv* env, jclass, jlong nativeObject, jlong axisAlignedBoundingBox) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->boundingBox(*(filament::Box*) axisAlignedBoundingBox);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nLayerMask(JNIEnv* env, jclass, jlong nativeObject, jbyte select, jbyte values) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->layerMask(select, values);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nPriority(JNIEnv* env, jclass, jlong nativeObject, jbyte priority) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->priority(priority);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nChannel(JNIEnv* env, jclass, jlong nativeObject, jbyte channel) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->channel(channel);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nCulling(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->culling(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nLightChannel(JNIEnv* env, jclass, jlong nativeObject, jint channel, jboolean enable) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->lightChannel(channel, enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nCastShadows(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->castShadows(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nReceiveShadows(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->receiveShadows(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nScreenSpaceContactShadows(JNIEnv* env, jclass, jlong nativeObject, jboolean enable) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->screenSpaceContactShadows(enable);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nEnableSkinningBuffers(JNIEnv* env, jclass, jlong nativeObject, jboolean enabled) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->enableSkinningBuffers(enabled);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nFog(JNIEnv* env, jclass, jlong nativeObject, jboolean enabled) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->fog(enabled);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nSkinning__JJJJ(JNIEnv* env, jclass, jlong nativeObject, jlong skinningBuffer, jlong count, jlong offset) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->skinning((filament::SkinningBuffer*) skinningBuffer, count, offset);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nSkinning__JJ_3F(JNIEnv* env, jclass, jlong nativeObject, jlong boneCount, jfloatArray transforms) {
    jfloat* transforms_ = env->GetFloatArrayElements(transforms, nullptr);
    jlong result = (jlong) &((filament::RenderableManager::Builder*) nativeObject)->skinning(boneCount, reinterpret_cast<const filament::math::details::TMat44<float>*>(transforms_));
    env->ReleaseFloatArrayElements(transforms, transforms_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nSkinning__JJJ(JNIEnv* env, jclass, jlong nativeObject, jlong boneCount, jlong bones) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->skinning(boneCount, (filament::RenderableManager::Bone*) bones);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nSkinning__JJ(JNIEnv* env, jclass, jlong nativeObject, jlong boneCount) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->skinning(boneCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nBoneIndicesAndWeights(JNIEnv* env, jclass, jlong nativeObject, jlong primitiveIndex, jfloatArray indicesAndWeights, jlong count, jlong bonesPerVertex) {
    jfloat* indicesAndWeights_ = env->GetFloatArrayElements(indicesAndWeights, nullptr);
    jlong result = (jlong) &((filament::RenderableManager::Builder*) nativeObject)->boneIndicesAndWeights(primitiveIndex, reinterpret_cast<const filament::math::details::TVec2<float>*>(indicesAndWeights_), count, bonesPerVertex);
    env->ReleaseFloatArrayElements(indicesAndWeights, indicesAndWeights_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nMorphingLong(JNIEnv* env, jclass, jlong nativeObject, jlong targetCount) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->morphing(targetCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nMorphingMorphTargetBuffer(JNIEnv* env, jclass, jlong nativeObject, jlong morphTargetBuffer) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->morphing((filament::MorphTargetBuffer*) morphTargetBuffer);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nMorphing(JNIEnv* env, jclass, jlong nativeObject, jbyte level, jlong primitiveIndex, jlong offset) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->morphing(level, primitiveIndex, offset);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nBlendOrder(JNIEnv* env, jclass, jlong nativeObject, jlong primitiveIndex, jshort blendOrder) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->blendOrder(primitiveIndex, blendOrder);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nGlobalBlendOrderEnabled(JNIEnv* env, jclass, jlong nativeObject, jlong primitiveIndex, jboolean enabled) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->globalBlendOrderEnabled(primitiveIndex, enabled);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nInstances__JJ(JNIEnv* env, jclass, jlong nativeObject, jlong instanceCount) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->instances(instanceCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nInstances__JJJ(JNIEnv* env, jclass, jlong nativeObject, jlong instanceCount, jlong instanceBuffer) {
    return (jlong) &((filament::RenderableManager::Builder*) nativeObject)->instances(instanceCount, (filament::InstanceBuffer*) instanceBuffer);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderableManager_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject, jlong engine, jint entity) {
    return (jint) ((filament::RenderableManager::Builder*) nativeObject)->build(*(filament::Engine*) engine, utils::Entity::import(entity));
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - RenderableManager::getEnabledAttributesAt(Instance, size_t) const: return type: AttributeBitset crosses by copy, and Java has no value type
//   - Builder::boneIndicesAndWeights(size_t, utils::FixedCapacityVector<utils::FixedCapacityVector<math::float2>>): parameter "indicesAndWeightsVector" has unresolved type utils::FixedCapacityVector<utils::FixedCapacityVector<math::float2>>
