// This file has been generated by beamsplitter

#include <filament/Renderer.h>

#include <jni.h>

#include <string>

// Copies filament::Renderer::DisplayInfo to and from its Java counterpart, member by member.
static filament::Renderer::DisplayInfo readRenderer_generated_DisplayInfo(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::Renderer::DisplayInfo out;
    out.refreshRate = env->GetFloatField(obj, env->GetFieldID(cls, "refreshRate", "F"));
    out.presentationDeadlineNanos = env->GetLongField(obj, env->GetFieldID(cls, "presentationDeadlineNanos", "J"));
    out.vsyncOffsetNanos = env->GetLongField(obj, env->GetFieldID(cls, "vsyncOffsetNanos", "J"));
    return out;
}

static jobject writeRenderer_generated_DisplayInfo(JNIEnv* env, const filament::Renderer::DisplayInfo& in) {
    jclass cls = env->FindClass("com/google/android/filament/Renderer_generated$DisplayInfo");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetFloatField(obj, env->GetFieldID(cls, "refreshRate", "F"), (jfloat) in.refreshRate);
    env->SetLongField(obj, env->GetFieldID(cls, "presentationDeadlineNanos", "J"), (jlong) in.presentationDeadlineNanos);
    env->SetLongField(obj, env->GetFieldID(cls, "vsyncOffsetNanos", "J"), (jlong) in.vsyncOffsetNanos);
    return obj;
}

// Copies filament::Renderer::FrameRateOptions to and from its Java counterpart, member by member.
static filament::Renderer::FrameRateOptions readRenderer_generated_FrameRateOptions(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::Renderer::FrameRateOptions out;
    out.headRoomRatio = env->GetFloatField(obj, env->GetFieldID(cls, "headRoomRatio", "F"));
    out.scaleRate = env->GetFloatField(obj, env->GetFieldID(cls, "scaleRate", "F"));
    out.history = env->GetByteField(obj, env->GetFieldID(cls, "history", "B"));
    out.interval = env->GetByteField(obj, env->GetFieldID(cls, "interval", "B"));
    return out;
}

static jobject writeRenderer_generated_FrameRateOptions(JNIEnv* env, const filament::Renderer::FrameRateOptions& in) {
    jclass cls = env->FindClass("com/google/android/filament/Renderer_generated$FrameRateOptions");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetFloatField(obj, env->GetFieldID(cls, "headRoomRatio", "F"), (jfloat) in.headRoomRatio);
    env->SetFloatField(obj, env->GetFieldID(cls, "scaleRate", "F"), (jfloat) in.scaleRate);
    env->SetByteField(obj, env->GetFieldID(cls, "history", "B"), (jbyte) in.history);
    env->SetByteField(obj, env->GetFieldID(cls, "interval", "B"), (jbyte) in.interval);
    return obj;
}

// Copies filament::Renderer::ClearOptions to and from its Java counterpart, member by member.
static filament::Renderer::ClearOptions readRenderer_generated_ClearOptions(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::Renderer::ClearOptions out;
    {
        jdoubleArray a = (jdoubleArray) env->GetObjectField(obj, env->GetFieldID(cls, "clearColor", "[D"));
        jdouble* p = env->GetDoubleArrayElements(a, nullptr);
        out.clearColor = *reinterpret_cast<filament::math::details::TVec4<double>*>(p);
        env->ReleaseDoubleArrayElements(a, p, JNI_ABORT);
    }
    out.clearStencil = env->GetByteField(obj, env->GetFieldID(cls, "clearStencil", "B"));
    out.clear = env->GetBooleanField(obj, env->GetFieldID(cls, "clear", "Z"));
    out.discard = env->GetBooleanField(obj, env->GetFieldID(cls, "discard", "Z"));
    return out;
}

static jobject writeRenderer_generated_ClearOptions(JNIEnv* env, const filament::Renderer::ClearOptions& in) {
    jclass cls = env->FindClass("com/google/android/filament/Renderer_generated$ClearOptions");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    {
        jdoubleArray a = env->NewDoubleArray(4);
        env->SetDoubleArrayRegion(a, 0, 4, reinterpret_cast<const jdouble*>(&in.clearColor));
        env->SetObjectField(obj, env->GetFieldID(cls, "clearColor", "[D"), a);
    }
    env->SetByteField(obj, env->GetFieldID(cls, "clearStencil", "B"), (jbyte) in.clearStencil);
    env->SetBooleanField(obj, env->GetFieldID(cls, "clear", "Z"), (jboolean) in.clear);
    env->SetBooleanField(obj, env->GetFieldID(cls, "discard", "Z"), (jboolean) in.discard);
    return obj;
}

// Copies filament::Renderer::FrameInfo to and from its Java counterpart, member by member.
static filament::Renderer::FrameInfo readRenderer_generated_FrameInfo(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::Renderer::FrameInfo out;
    out.frameId = env->GetIntField(obj, env->GetFieldID(cls, "frameId", "I"));
    out.gpuFrameDuration = env->GetLongField(obj, env->GetFieldID(cls, "gpuFrameDuration", "J"));
    out.denoisedGpuFrameDuration = env->GetLongField(obj, env->GetFieldID(cls, "denoisedGpuFrameDuration", "J"));
    out.beginFrame = env->GetLongField(obj, env->GetFieldID(cls, "beginFrame", "J"));
    out.endFrame = env->GetLongField(obj, env->GetFieldID(cls, "endFrame", "J"));
    out.backendBeginFrame = env->GetLongField(obj, env->GetFieldID(cls, "backendBeginFrame", "J"));
    out.backendEndFrame = env->GetLongField(obj, env->GetFieldID(cls, "backendEndFrame", "J"));
    out.gpuFrameComplete = env->GetLongField(obj, env->GetFieldID(cls, "gpuFrameComplete", "J"));
    out.vsync = env->GetLongField(obj, env->GetFieldID(cls, "vsync", "J"));
    out.displayPresent = env->GetLongField(obj, env->GetFieldID(cls, "displayPresent", "J"));
    out.presentDeadline = env->GetLongField(obj, env->GetFieldID(cls, "presentDeadline", "J"));
    out.displayPresentInterval = env->GetLongField(obj, env->GetFieldID(cls, "displayPresentInterval", "J"));
    out.compositionToPresentLatency = env->GetLongField(obj, env->GetFieldID(cls, "compositionToPresentLatency", "J"));
    out.expectedPresentLatency = env->GetLongField(obj, env->GetFieldID(cls, "expectedPresentLatency", "J"));
    out.frameScheduleTime = env->GetLongField(obj, env->GetFieldID(cls, "frameScheduleTime", "J"));
    return out;
}

static jobject writeRenderer_generated_FrameInfo(JNIEnv* env, const filament::Renderer::FrameInfo& in) {
    jclass cls = env->FindClass("com/google/android/filament/Renderer_generated$FrameInfo");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetIntField(obj, env->GetFieldID(cls, "frameId", "I"), (jint) in.frameId);
    env->SetLongField(obj, env->GetFieldID(cls, "gpuFrameDuration", "J"), (jlong) in.gpuFrameDuration);
    env->SetLongField(obj, env->GetFieldID(cls, "denoisedGpuFrameDuration", "J"), (jlong) in.denoisedGpuFrameDuration);
    env->SetLongField(obj, env->GetFieldID(cls, "beginFrame", "J"), (jlong) in.beginFrame);
    env->SetLongField(obj, env->GetFieldID(cls, "endFrame", "J"), (jlong) in.endFrame);
    env->SetLongField(obj, env->GetFieldID(cls, "backendBeginFrame", "J"), (jlong) in.backendBeginFrame);
    env->SetLongField(obj, env->GetFieldID(cls, "backendEndFrame", "J"), (jlong) in.backendEndFrame);
    env->SetLongField(obj, env->GetFieldID(cls, "gpuFrameComplete", "J"), (jlong) in.gpuFrameComplete);
    env->SetLongField(obj, env->GetFieldID(cls, "vsync", "J"), (jlong) in.vsync);
    env->SetLongField(obj, env->GetFieldID(cls, "displayPresent", "J"), (jlong) in.displayPresent);
    env->SetLongField(obj, env->GetFieldID(cls, "presentDeadline", "J"), (jlong) in.presentDeadline);
    env->SetLongField(obj, env->GetFieldID(cls, "displayPresentInterval", "J"), (jlong) in.displayPresentInterval);
    env->SetLongField(obj, env->GetFieldID(cls, "compositionToPresentLatency", "J"), (jlong) in.compositionToPresentLatency);
    env->SetLongField(obj, env->GetFieldID(cls, "expectedPresentLatency", "J"), (jlong) in.expectedPresentLatency);
    env->SetLongField(obj, env->GetFieldID(cls, "frameScheduleTime", "J"), (jlong) in.frameScheduleTime);
    return obj;
}


extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Renderer_1generated_nGetMaxFrameHistorySize(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Renderer*) nativeObject)->getMaxFrameHistorySize();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetDisplayInfo(JNIEnv* env, jclass, jlong nativeObject, jobject info) {
    ((filament::Renderer*) nativeObject)->setDisplayInfo(readRenderer_generated_DisplayInfo(env, info));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetFrameRateOptions(JNIEnv* env, jclass, jlong nativeObject, jobject options) {
    ((filament::Renderer*) nativeObject)->setFrameRateOptions(readRenderer_generated_FrameRateOptions(env, options));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetClearOptions(JNIEnv* env, jclass, jlong nativeObject, jobject options) {
    ((filament::Renderer*) nativeObject)->setClearOptions(readRenderer_generated_ClearOptions(env, options));
}

extern "C" JNIEXPORT jobject JNICALL
Java_com_google_android_filament_Renderer_1generated_nGetClearOptions(JNIEnv* env, jclass, jlong nativeObject) {
    return writeRenderer_generated_ClearOptions(env, ((filament::Renderer*) nativeObject)->getClearOptions());
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Renderer_1generated_nGetEngine(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Renderer*) nativeObject)->getEngine();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetVsyncTime(JNIEnv* env, jclass, jlong nativeObject, jlong steadyClockTimeNano) {
    ((filament::Renderer*) nativeObject)->setVsyncTime(steadyClockTimeNano);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSkipFrame(JNIEnv* env, jclass, jlong nativeObject, jlong vsyncSteadyClockTimeNano) {
    ((filament::Renderer*) nativeObject)->skipFrame(vsyncSteadyClockTimeNano);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Renderer_1generated_nShouldRenderFrame(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Renderer*) nativeObject)->shouldRenderFrame();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Renderer_1generated_nBeginFrame(JNIEnv* env, jclass, jlong nativeObject, jlong swapChain, jlong vsyncSteadyClockTimeNano) {
    return (jboolean) ((filament::Renderer*) nativeObject)->beginFrame((filament::SwapChain*) swapChain, vsyncSteadyClockTimeNano);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetPresentationTime(JNIEnv* env, jclass, jlong nativeObject, jlong monotonic_clock_ns) {
    ((filament::Renderer*) nativeObject)->setPresentationTime(monotonic_clock_ns);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetDesiredPresentationTime(JNIEnv* env, jclass, jlong nativeObject, jlong monotonic_clock_ns) {
    ((filament::Renderer*) nativeObject)->setDesiredPresentationTime(monotonic_clock_ns);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetRenderingDeadline(JNIEnv* env, jclass, jlong nativeObject, jlong monotonic_clock_ns) {
    ((filament::Renderer*) nativeObject)->setRenderingDeadline(monotonic_clock_ns);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nRender(JNIEnv* env, jclass, jlong nativeObject, jlong view) {
    ((filament::Renderer*) nativeObject)->render((filament::View*) view);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nCopyFrame(JNIEnv* env, jclass, jlong nativeObject, jlong dstSwapChain, jlong dstViewport, jlong srcViewport, jint flags) {
    ((filament::Renderer*) nativeObject)->copyFrame((filament::SwapChain*) dstSwapChain, *(filament::Viewport*) dstViewport, *(filament::Viewport*) srcViewport, flags);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nEndFrame(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Renderer*) nativeObject)->endFrame();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nRenderStandaloneView(JNIEnv* env, jclass, jlong nativeObject, jlong view) {
    ((filament::Renderer*) nativeObject)->renderStandaloneView((filament::View*) view);
}

extern "C" JNIEXPORT jdouble JNICALL
Java_com_google_android_filament_Renderer_1generated_nGetMaterialTime(JNIEnv* env, jclass, jlong nativeObject) {
    return (jdouble) ((filament::Renderer*) nativeObject)->getMaterialTime();
}

extern "C" JNIEXPORT jdouble JNICALL
Java_com_google_android_filament_Renderer_1generated_nGetUserTime(JNIEnv* env, jclass, jlong nativeObject) {
    return (jdouble) ((filament::Renderer*) nativeObject)->getUserTime();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetMaterialTimeEpoch(JNIEnv* env, jclass, jlong nativeObject, jlong monotonic_clock_ns) {
    ((filament::Renderer*) nativeObject)->setMaterialTimeEpoch(monotonic_clock_ns);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nResetUserTime(JNIEnv* env, jclass, jlong nativeObject) {
    ((filament::Renderer*) nativeObject)->resetUserTime();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSkipNextFrames(JNIEnv* env, jclass, jlong nativeObject, jlong frameCount) {
    ((filament::Renderer*) nativeObject)->skipNextFrames(frameCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Renderer_1generated_nGetFrameToSkipCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Renderer*) nativeObject)->getFrameToSkipCount();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Renderer_1generated_nHasGpuFallenBehind(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Renderer*) nativeObject)->hasGpuFallenBehind();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nSetFrameScheduleTime(JNIEnv* env, jclass, jlong nativeObject, jlong timeSteadyClockNano) {
    ((filament::Renderer*) nativeObject)->setFrameScheduleTime(timeSteadyClockNano);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Renderer_1generated_nPauseRenderThread(JNIEnv* env, jclass, jlong nativeObject, jlong duration_ns) {
    ((filament::Renderer*) nativeObject)->pauseRenderThread(duration_ns);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Renderer::getFrameInfoHistory(size_t) const: returns unresolved type utils::FixedCapacityVector<FrameInfo>
//   - Renderer::setPresentationTime(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setDesiredPresentationTime(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setRenderingDeadline(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::readPixels(uint32_t, uint32_t, uint32_t, uint32_t, backend::PixelBufferDescriptor &&): parameter "buffer": takes backend::PixelBufferDescriptor &&, and Java has no way to move a value
//   - Renderer::readPixels(RenderTarget * _Nonnull, uint32_t, uint32_t, uint32_t, uint32_t, backend::PixelBufferDescriptor &&): parameter "buffer": takes backend::PixelBufferDescriptor &&, and Java has no way to move a value
//   - Renderer::setMaterialTimeEpoch(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setFrameScheduleTime(std::chrono::steady_clock::time_point): parameter "time" has unresolved type std::chrono::steady_clock::time_point
