// This file has been generated by beamsplitter

#include <backend/DriverEnums.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_SamplerParams_1generated_nIsFiltered(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::backend::SamplerParams*) nativeObject)->isFiltered();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Hasher::operator()(SamplerParams) const: parameter "p": SamplerParams crosses by copy, and Java has no value type
//   - EqualTo::operator()(SamplerParams, SamplerParams) const: parameter "lhs": SamplerParams crosses by copy, and Java has no value type
//   - LessThan::operator()(SamplerParams, SamplerParams) const: parameter "lhs": SamplerParams crosses by copy, and Java has no value type
