// This file has been generated by beamsplitter

#include <filament/Stream.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Stream_1generated_nGetStreamType(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((filament::Stream*) nativeObject)->getStreamType();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Stream_1generated_nSetDimensions(JNIEnv* env, jclass, jlong nativeObject, jint width, jint height) {
    ((filament::Stream*) nativeObject)->setDimensions(width, height);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Stream_1generated_nGetTimestamp(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::Stream*) nativeObject)->getTimestamp();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Stream_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::Stream::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Stream_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::Stream::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Stream_1generated_00024Builder_nWidth(JNIEnv* env, jclass, jlong nativeObject, jint width) {
    return (jlong) &((filament::Stream::Builder*) nativeObject)->width(width);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Stream_1generated_00024Builder_nHeight(JNIEnv* env, jclass, jlong nativeObject, jint height) {
    return (jlong) &((filament::Stream::Builder*) nativeObject)->height(height);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Stream_1generated_00024Builder_nName(JNIEnv* env, jclass, jlong nativeObject, jstring name, jlong len) {
    const char* name_ = env->GetStringUTFChars(name, nullptr);
    jlong result = (jlong) &((filament::Stream::Builder*) nativeObject)->name(name_, len);
    env->ReleaseStringUTFChars(name, name_);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Stream_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject, jlong engine) {
    return (jlong) ((filament::Stream::Builder*) nativeObject)->build(*(filament::Engine*) engine);
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Stream::setAcquiredImage(void * _Nonnull, Callback _Nonnull, void * _Nullable, const math::mat3f &): parameter "image": void * _Nonnull is opaque, so there is nothing to marshal
//   - Stream::setAcquiredImage(void * _Nonnull, backend::CallbackHandler * _Nullable, Callback _Nonnull, void * _Nullable, const math::mat3f &): parameter "image": void * _Nonnull is opaque, so there is nothing to marshal
//   - Builder::stream(void * _Nullable): parameter "stream": void * _Nullable is opaque, so there is nothing to marshal
//   - Builder::name(const utils::StaticString &): parameter "name" is utils::StaticString, which is not bound
