// This file has been generated by beamsplitter

#include <filament/SwapChain.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_SwapChain_1generated_nIsProtectedContentSupported(JNIEnv* env, jclass, jlong engine) {
    return (jboolean) filament::SwapChain::isProtectedContentSupported(*(filament::Engine*) engine);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_SwapChain_1generated_nIsSRGBSwapChainSupported(JNIEnv* env, jclass, jlong engine) {
    return (jboolean) filament::SwapChain::isSRGBSwapChainSupported(*(filament::Engine*) engine);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_SwapChain_1generated_nIsMSAASwapChainSupported(JNIEnv* env, jclass, jlong engine, jint samples) {
    return (jboolean) filament::SwapChain::isMSAASwapChainSupported(*(filament::Engine*) engine, samples);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_SwapChain_1generated_nSetFrameRate(JNIEnv* env, jclass, jlong nativeObject, jfloat frameRate, jint compatibility, jint strategy) {
    ((filament::SwapChain*) nativeObject)->setFrameRate(frameRate, (filament::backend::Platform::FrameRateCompatibility) compatibility, (filament::backend::Platform::ChangeFrameRateStrategy) strategy);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_SwapChain_1generated_nIsFrameScheduledCallbackSet(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::SwapChain*) nativeObject)->isFrameScheduledCallbackSet();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - SwapChain::isFrameRateChangeSupported() const: return type: utils::tribool crosses by copy, and Java has no value type
//   - SwapChain::getNativeWindow() const: return type: void * _Nullable is opaque, so there is nothing to marshal
//   - SwapChain::setFrameScheduledCallback(backend::CallbackHandler * _Nullable, FrameScheduledCallback &&, uint64_t): parameter "callback": takes FrameScheduledCallback &&, and Java has no way to move a value
//   - SwapChain::setFrameCompletedCallback(backend::CallbackHandler * _Nullable, FrameCompletedCallback &&): parameter "callback": takes FrameCompletedCallback &&, and Java has no way to move a value
