// This file has been generated by beamsplitter

#include <filament/Viewport.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_Viewport_1generated_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::Viewport*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Viewport_1generated_nCreate__(JNIEnv* env, jclass) {
    return (jlong) new filament::Viewport();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_Viewport_1generated_nCreate__IIII(JNIEnv* env, jclass, jint left, jint bottom, jint width, jint height) {
    return (jlong) new filament::Viewport(left, bottom, width, height);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_Viewport_1generated_nEmpty(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::Viewport*) nativeObject)->empty();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
