// This file has been generated by beamsplitter

#include <filament/BufferObject.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::BufferObject>(filament::BufferObject* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_BufferObject) {

class_<filament::BufferObject>("BufferObject")
    .function("setBuffer", (void (*) (filament::BufferObject* self, filament::Engine& engine, BufferDescriptor buffer, uint32_t byteOffset)) [](filament::BufferObject* self, filament::Engine& engine, BufferDescriptor buffer, uint32_t byteOffset) -> void {
        self->setBuffer(engine, std::move(*buffer.bd), byteOffset);
    }, allow_raw_pointers())
    .function("getByteCount", &filament::BufferObject::getByteCount)
    ;

class_<filament::BufferObject::Builder>("BufferObject$Builder")
    .constructor<>()
    .function("size", (filament::BufferObject::Builder* (*) (filament::BufferObject::Builder* self, uint32_t byteCount)) [](filament::BufferObject::Builder* self, uint32_t byteCount) -> filament::BufferObject::Builder* {
        return &self->size(byteCount);
    }, allow_raw_pointers())
    .function("bindingType", (filament::BufferObject::Builder* (*) (filament::BufferObject::Builder* self, filament::backend::BufferObjectBinding bindingType)) [](filament::BufferObject::Builder* self, filament::backend::BufferObjectBinding bindingType) -> filament::BufferObject::Builder* {
        return &self->bindingType(bindingType);
    }, allow_raw_pointers())
    .function("name", (filament::BufferObject::Builder* (*) (filament::BufferObject::Builder* self, std::string name, size_t len)) [](filament::BufferObject::Builder* self, std::string name, size_t len) -> filament::BufferObject::Builder* {
        return &self->name(name.c_str(), len);
    }, allow_raw_pointers())
    .function("build", &filament::BufferObject::Builder::build, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Builder::name(const utils::StaticString &): parameter "name" is utils::StaticString, which is not bound


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
