// This file has been generated by beamsplitter

#include <filament/ColorSpace.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::color::ColorSpace>(filament::color::ColorSpace* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_ColorSpace) {

class_<filament::color::ColorSpace>("color$ColorSpace")
    .function("equals", &filament::color::ColorSpace::operator==)
    .function("getPrimaries", (const filament::color::Primaries* (*) (filament::color::ColorSpace* self)) [](filament::color::ColorSpace* self) -> const filament::color::Primaries* {
        return &self->getPrimaries();
    }, allow_raw_pointers())
    .function("getWhitePoint", &filament::color::ColorSpace::getWhitePoint)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - ColorSpace::ColorSpace(const Primaries, const TransferFunction, const WhitePoint): parameter "transferFunction" is filament::color::TransferFunction, which is not bound
//   - ColorSpace::getTransferFunction() const: return type is filament::color::TransferFunction, which is not bound


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
