// This file has been generated by beamsplitter

#include <filament/Box.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filament_Corners) {

class_<filament::Aabb::Corners>("Aabb$Corners")
    .function("size", &filament::Aabb::Corners::size)
    .function("get", static_cast<filament::math::details::TVec3<float>& (filament::Aabb::Corners::*)(size_t) noexcept>(&filament::Aabb::Corners::operator[]))
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Corners::begin() const: returns const value_type *, an array with no length
//   - Corners::end() const: returns const value_type *, an array with no length
//   - Corners::begin(): returns value_type *, an array with no length
//   - Corners::end(): returns value_type *, an array with no length
//   - Corners::data() const: returns const value_type *, an array with no length
//   - Corners::data(): returns value_type *, an array with no length


} // EMSCRIPTEN_BINDINGS
