// This file has been generated by beamsplitter

#include <filament/DebugRegistry.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::DebugRegistry>(filament::DebugRegistry* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_DebugRegistry) {

class_<filament::DebugRegistry>("DebugRegistry")
    .function("hasProperty", &filament::DebugRegistry::hasProperty, allow_raw_pointers())
    .function("setPropertyBool", static_cast<bool (filament::DebugRegistry::*)(const char*, bool) noexcept>(&filament::DebugRegistry::setProperty), allow_raw_pointers())
    .function("setPropertyInt", static_cast<bool (filament::DebugRegistry::*)(const char*, int) noexcept>(&filament::DebugRegistry::setProperty), allow_raw_pointers())
    .function("setPropertyFloat", static_cast<bool (filament::DebugRegistry::*)(const char*, float) noexcept>(&filament::DebugRegistry::setProperty), allow_raw_pointers())
    .function("setPropertyFloat2", static_cast<bool (filament::DebugRegistry::*)(const char*, filament::math::details::TVec2<float>) noexcept>(&filament::DebugRegistry::setProperty), allow_raw_pointers())
    .function("setPropertyFloat3", static_cast<bool (filament::DebugRegistry::*)(const char*, filament::math::details::TVec3<float>) noexcept>(&filament::DebugRegistry::setProperty), allow_raw_pointers())
    .function("setPropertyFloat4", static_cast<bool (filament::DebugRegistry::*)(const char*, filament::math::details::TVec4<float>) noexcept>(&filament::DebugRegistry::setProperty), allow_raw_pointers())
    .function("getPropertyBool", (bool (*) (filament::DebugRegistry* self, std::string name, emscripten::val v)) [](filament::DebugRegistry* self, std::string name, emscripten::val v) -> bool {
        auto v_ = emscripten::convertJSArrayToNumberVector<char>(v);
        bool result = self->getProperty(name.c_str(), reinterpret_cast<bool*>(v_.data()));
        for (size_t i = 0; i < v_.size(); i++) v.set(i, (bool) v_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getPropertyInt", (bool (*) (filament::DebugRegistry* self, std::string name, emscripten::val v)) [](filament::DebugRegistry* self, std::string name, emscripten::val v) -> bool {
        auto v_ = emscripten::convertJSArrayToNumberVector<int32_t>(v);
        bool result = self->getProperty(name.c_str(), reinterpret_cast<int*>(v_.data()));
        for (size_t i = 0; i < v_.size(); i++) v.set(i, v_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getPropertyFloat", (bool (*) (filament::DebugRegistry* self, std::string name, emscripten::val v)) [](filament::DebugRegistry* self, std::string name, emscripten::val v) -> bool {
        auto v_ = emscripten::convertJSArrayToNumberVector<float>(v);
        bool result = self->getProperty(name.c_str(), reinterpret_cast<float*>(v_.data()));
        for (size_t i = 0; i < v_.size(); i++) v.set(i, v_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getPropertyFloat2", (bool (*) (filament::DebugRegistry* self, std::string name, emscripten::val v)) [](filament::DebugRegistry* self, std::string name, emscripten::val v) -> bool {
        auto v_ = emscripten::convertJSArrayToNumberVector<float>(v);
        bool result = self->getProperty(name.c_str(), reinterpret_cast<filament::math::details::TVec2<float>*>(v_.data()));
        for (size_t i = 0; i < v_.size(); i++) v.set(i, v_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getPropertyFloat3", (bool (*) (filament::DebugRegistry* self, std::string name, emscripten::val v)) [](filament::DebugRegistry* self, std::string name, emscripten::val v) -> bool {
        auto v_ = emscripten::convertJSArrayToNumberVector<float>(v);
        bool result = self->getProperty(name.c_str(), reinterpret_cast<filament::math::details::TVec3<float>*>(v_.data()));
        for (size_t i = 0; i < v_.size(); i++) v.set(i, v_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getPropertyFloat4", (bool (*) (filament::DebugRegistry* self, std::string name, emscripten::val v)) [](filament::DebugRegistry* self, std::string name, emscripten::val v) -> bool {
        auto v_ = emscripten::convertJSArrayToNumberVector<float>(v);
        bool result = self->getProperty(name.c_str(), reinterpret_cast<filament::math::details::TVec4<float>*>(v_.data()));
        for (size_t i = 0; i < v_.size(); i++) v.set(i, v_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getDataSource", &filament::DebugRegistry::getDataSource, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - DebugRegistry::getPropertyAddress(const char * _Nonnull): return type: void * _Nullable is opaque, so there is nothing to marshal
//   - DebugRegistry::getPropertyAddress(const char * _Nonnull) const: return type: const void * _Nullable is opaque, so there is nothing to marshal


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
