// This file has been generated by beamsplitter

#include <filament/FrameHistoryStream.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::FrameHistoryStream::NewFramesRange::Iterator>(filament::FrameHistoryStream::NewFramesRange::Iterator* ptr) {}
        template<> void raw_destructor<filament::FrameHistoryStream::NewFramesRange>(filament::FrameHistoryStream::NewFramesRange* ptr) {}
        template<> void raw_destructor<filament::FrameHistoryStream::Result>(filament::FrameHistoryStream::Result* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_FrameHistoryStream) {

class_<filament::FrameHistoryStream>("FrameHistoryStream")
    .constructor<filament::Renderer*>()
    .function("getNewFrames", &filament::FrameHistoryStream::getNewFrames)
    ;

class_<filament::FrameHistoryStream::NewFramesRange::Iterator>("FrameHistoryStream$NewFramesRange$Iterator")
    .constructor<>()
    .function("equals", &filament::FrameHistoryStream::NewFramesRange::Iterator::operator==)
    .function("notEquals", &filament::FrameHistoryStream::NewFramesRange::Iterator::operator!=)
    ;

class_<filament::FrameHistoryStream::NewFramesRange>("FrameHistoryStream$NewFramesRange")
    .function("begin", &filament::FrameHistoryStream::NewFramesRange::begin)
    .function("end", &filament::FrameHistoryStream::NewFramesRange::end)
    ;

class_<filament::FrameHistoryStream::Result>("FrameHistoryStream$Result")
    .constructor<>()
    .function("getFrameId", &filament::FrameHistoryStream::Result::getFrameId)
    .function("getMissingId", &filament::FrameHistoryStream::Result::getMissingId)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Iterator::Iterator(const Renderer::FrameInfo *, const int, uint32_t *): parameter "historyStart": struct array with no element type
//   - NewFramesRange::NewFramesRange(utils::FixedCapacityVector<Renderer::FrameInfo>, uint32_t *): parameter "history" has unresolved type utils::FixedCapacityVector<Renderer::FrameInfo>
//   - Result::Result(const Renderer::FrameInfo &): 2 bound methods share the target key "Result/1"
//   - Result::Result(const uint32_t): 2 bound methods share the target key "Result/1"


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
