// This file has been generated by beamsplitter

#include <filament/FramePacer.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::FramePacer>(filament::FramePacer* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_FramePacer) {

class_<filament::FramePacer>("FramePacer")
    .function("configure", &filament::FramePacer::configure)
    .function("getConfiguration", (const filament::FramePacer::Configuration* (*) (filament::FramePacer* self)) [](filament::FramePacer* self) -> const filament::FramePacer::Configuration* {
        return &self->getConfiguration();
    }, allow_raw_pointers())
    .function("setupFrame", &filament::FramePacer::setupFrame)
    .function("setupExtraFrame", &filament::FramePacer::setupExtraFrame)
    .function("hasGpuFallenBehind", &filament::FramePacer::hasGpuFallenBehind, allow_raw_pointers())
    .function("applyPresentationTime", &filament::FramePacer::applyPresentationTime, allow_raw_pointers())
    .function("getPacingStatus", &filament::FramePacer::getPacingStatus)
    .function("resetPacing", &filament::FramePacer::resetPacing)
    .function("getSelectedFrameRate", &filament::FramePacer::getSelectedFrameRate)
    .function("isExactFrameRateAchieved", &filament::FramePacer::isExactFrameRateAchieved)
    ;

class_<filament::FramePacer::Builder>("FramePacer$Builder")
    .constructor<>()
    .function("targetFrameRate", (filament::FramePacer::Builder* (*) (filament::FramePacer::Builder* self, float fps)) [](filament::FramePacer::Builder* self, float fps) -> filament::FramePacer::Builder* {
        return &self->targetFrameRate(fps);
    }, allow_raw_pointers())
    .function("latencyFrames", (filament::FramePacer::Builder* (*) (filament::FramePacer::Builder* self, uint32_t frames)) [](filament::FramePacer::Builder* self, uint32_t frames) -> filament::FramePacer::Builder* {
        return &self->latencyFrames(frames);
    }, allow_raw_pointers())
    .function("build", &filament::FramePacer::Builder::build, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - FramePacer::getExpectedPresentationTime() const: return type: 64-bit integer, which needs -sWASM_BIGINT
//   - FramePacer::getRenderingDeadline() const: return type: 64-bit integer, which needs -sWASM_BIGINT
//   - FramePacer::getEffectiveLatency() const: returns unresolved type std::chrono::nanoseconds
//   - Builder::latency(std::chrono::nanoseconds): parameter "latency" has unresolved type std::chrono::nanoseconds


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
