// This file has been generated by beamsplitter

#include <filament/ColorSpace.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::color::Gamut>(filament::color::Gamut* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_Gamut) {

class_<filament::color::Gamut>("color$Gamut")
    .constructor<const filament::color::Primaries>()
    .constructor<filament::math::details::TVec2<float>, filament::math::details::TVec2<float>, filament::math::details::TVec2<float>>()
    .function("getPrimaries", (const filament::color::Primaries* (*) (filament::color::Gamut* self)) [](filament::color::Gamut* self) -> const filament::color::Primaries* {
        return &self->getPrimaries();
    }, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.


} // EMSCRIPTEN_BINDINGS
