// This file has been generated by beamsplitter

#include <filament/MaterialInstance.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::MaterialInstance>(filament::MaterialInstance* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_MaterialInstance) {

class_<filament::MaterialInstance>("MaterialInstance")
    .class_function("duplicate", &filament::MaterialInstance::duplicate, allow_raw_pointers())
    .function("getMaterial", &filament::MaterialInstance::getMaterial, allow_raw_pointers())
    .function("getName", &filament::MaterialInstance::getName, allow_raw_pointers())
    .function("setParameterBool", static_cast<void (filament::MaterialInstance::*)(const char*, const bool&)>(&filament::MaterialInstance::setParameter<bool>), allow_raw_pointers())
    .function("setParameterInt", static_cast<void (filament::MaterialInstance::*)(const char*, const int32_t&)>(&filament::MaterialInstance::setParameter<int32_t>), allow_raw_pointers())
    .function("setParameterString", static_cast<void (filament::MaterialInstance::*)(const char*, const uint32_t&)>(&filament::MaterialInstance::setParameter<uint32_t>), allow_raw_pointers())
    .function("setParameterFloat", static_cast<void (filament::MaterialInstance::*)(const char*, const float&)>(&filament::MaterialInstance::setParameter<float>), allow_raw_pointers())
    .function("setParameterFloat2", static_cast<void (filament::MaterialInstance::*)(const char*, const filament::math::details::TVec2<float>&)>(&filament::MaterialInstance::setParameter<filament::math::float2>), allow_raw_pointers())
    .function("setParameterFloat3", static_cast<void (filament::MaterialInstance::*)(const char*, const filament::math::details::TVec3<float>&)>(&filament::MaterialInstance::setParameter<filament::math::float3>), allow_raw_pointers())
    .function("setParameterFloat4", static_cast<void (filament::MaterialInstance::*)(const char*, const filament::math::details::TVec4<float>&)>(&filament::MaterialInstance::setParameter<filament::math::float4>), allow_raw_pointers())
    .function("setParameterMat3f", (void (*) (filament::MaterialInstance* self, std::string name, flatmat3 value)) [](filament::MaterialInstance* self, std::string name, flatmat3 value) -> void {
        self->setParameter<filament::math::mat3f>(name.c_str(), filament::math::details::TMat33<float>(value.m));
    }, allow_raw_pointers())
    .function("setParameterMat4f", (void (*) (filament::MaterialInstance* self, std::string name, flatmat4 value)) [](filament::MaterialInstance* self, std::string name, flatmat4 value) -> void {
        self->setParameter<filament::math::mat4f>(name.c_str(), filament::math::details::TMat44<float>(value.m));
    }, allow_raw_pointers())
    .function("setParameterLong", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<char>(values);
        self->setParameter<bool>(name.c_str(), nameLength, reinterpret_cast<const bool*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterInt", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<int32_t>(values);
        self->setParameter<int32_t>(name.c_str(), nameLength, reinterpret_cast<const int32_t*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterString", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<uint32_t>(values);
        self->setParameter<uint32_t>(name.c_str(), nameLength, reinterpret_cast<const uint32_t*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterFloat", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<float>(values);
        self->setParameter<float>(name.c_str(), nameLength, reinterpret_cast<const float*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterFloat2", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<float>(values);
        self->setParameter<filament::math::float2>(name.c_str(), nameLength, reinterpret_cast<const filament::math::details::TVec2<float>*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterFloat3", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<float>(values);
        self->setParameter<filament::math::float3>(name.c_str(), nameLength, reinterpret_cast<const filament::math::details::TVec3<float>*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterFloat4", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<float>(values);
        self->setParameter<filament::math::float4>(name.c_str(), nameLength, reinterpret_cast<const filament::math::details::TVec4<float>*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterMat3f", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<float>(values);
        self->setParameter<filament::math::mat3f>(name.c_str(), nameLength, reinterpret_cast<const filament::math::details::TMat33<float>*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterMat4f", (void (*) (filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count)) [](filament::MaterialInstance* self, std::string name, size_t nameLength, emscripten::val values, size_t count) -> void {
        auto values_ = emscripten::convertJSArrayToNumberVector<float>(values);
        self->setParameter<filament::math::mat4f>(name.c_str(), nameLength, reinterpret_cast<const filament::math::details::TMat44<float>*>(values_.data()), count);
    }, allow_raw_pointers())
    .function("setParameterTextureSampler", static_cast<void (filament::MaterialInstance::*)(const char*, size_t, const filament::Texture*, const filament::TextureSampler&)>(&filament::MaterialInstance::setParameter), allow_raw_pointers())
    .function("setParameterRgbType", static_cast<void (filament::MaterialInstance::*)(const char*, size_t, filament::RgbType, filament::math::details::TVec3<float>)>(&filament::MaterialInstance::setParameter), allow_raw_pointers())
    .function("setParameterRgbaType", static_cast<void (filament::MaterialInstance::*)(const char*, size_t, filament::RgbaType, filament::math::details::TVec4<float>)>(&filament::MaterialInstance::setParameter), allow_raw_pointers())
    .function("setScissor", &filament::MaterialInstance::setScissor)
    .function("unsetScissor", &filament::MaterialInstance::unsetScissor)
    .function("setPolygonOffset", &filament::MaterialInstance::setPolygonOffset)
    .function("setMaskThreshold", &filament::MaterialInstance::setMaskThreshold)
    .function("getMaskThreshold", &filament::MaterialInstance::getMaskThreshold)
    .function("setSpecularAntiAliasingVariance", &filament::MaterialInstance::setSpecularAntiAliasingVariance)
    .function("getSpecularAntiAliasingVariance", &filament::MaterialInstance::getSpecularAntiAliasingVariance)
    .function("setSpecularAntiAliasingThreshold", &filament::MaterialInstance::setSpecularAntiAliasingThreshold)
    .function("getSpecularAntiAliasingThreshold", &filament::MaterialInstance::getSpecularAntiAliasingThreshold)
    .function("setDoubleSided", &filament::MaterialInstance::setDoubleSided)
    .function("isDoubleSided", &filament::MaterialInstance::isDoubleSided)
    .function("setTransparencyMode", &filament::MaterialInstance::setTransparencyMode)
    .function("getTransparencyMode", &filament::MaterialInstance::getTransparencyMode)
    .function("setCullingMode", static_cast<void (filament::MaterialInstance::*)(filament::backend::CullingMode) noexcept>(&filament::MaterialInstance::setCullingMode))
    .function("setCullingMode", static_cast<void (filament::MaterialInstance::*)(filament::backend::CullingMode, filament::backend::CullingMode) noexcept>(&filament::MaterialInstance::setCullingMode))
    .function("getCullingMode", &filament::MaterialInstance::getCullingMode)
    .function("getShadowCullingMode", &filament::MaterialInstance::getShadowCullingMode)
    .function("setColorWrite", &filament::MaterialInstance::setColorWrite)
    .function("isColorWriteEnabled", &filament::MaterialInstance::isColorWriteEnabled)
    .function("setDepthWrite", &filament::MaterialInstance::setDepthWrite)
    .function("isDepthWriteEnabled", &filament::MaterialInstance::isDepthWriteEnabled)
    .function("setDepthCulling", &filament::MaterialInstance::setDepthCulling)
    .function("setDepthFunc", &filament::MaterialInstance::setDepthFunc)
    .function("getDepthFunc", &filament::MaterialInstance::getDepthFunc)
    .function("isDepthCullingEnabled", &filament::MaterialInstance::isDepthCullingEnabled)
    .function("setStencilWrite", &filament::MaterialInstance::setStencilWrite)
    .function("isStencilWriteEnabled", &filament::MaterialInstance::isStencilWriteEnabled)
    .function("setStencilCompareFunction", &filament::MaterialInstance::setStencilCompareFunction)
    .function("setStencilOpStencilFail", &filament::MaterialInstance::setStencilOpStencilFail)
    .function("setStencilOpDepthFail", &filament::MaterialInstance::setStencilOpDepthFail)
    .function("setStencilOpDepthStencilPass", &filament::MaterialInstance::setStencilOpDepthStencilPass)
    .function("setStencilReferenceValue", &filament::MaterialInstance::setStencilReferenceValue)
    .function("setStencilReadMask", &filament::MaterialInstance::setStencilReadMask)
    .function("setStencilWriteMask", &filament::MaterialInstance::setStencilWriteMask)
    .function("commit", &filament::MaterialInstance::commit)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, size_t, const T &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const StringLiteral, const T * _Nonnull, const size_t): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const char * _Nonnull, const T * _Nonnull, const size_t): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const StringLiteral, const Texture * _Nullable, const TextureSampler &): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const char * _Nonnull, const Texture * _Nullable, const TextureSampler &): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const StringLiteral, const RgbType, const math::float3): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const char * _Nonnull, const RgbType, const math::float3): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::setParameter(const StringLiteral, const RgbaType, const math::float4): parameter "name" is filament::MaterialInstance::StringLiteral, which is not bound
//   - MaterialInstance::setParameter(const char * _Nonnull, const RgbaType, const math::float4): 21 bound methods share the target key "setParameter/3"
//   - MaterialInstance::compile(CompilerPriorityQueue, UserVariantFilterMask, backend::CallbackHandler * _Nullable, utils::Invocable<void (MaterialInstance * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (MaterialInstance * _Nonnull)> &&, and JavaScript has no way to move a value
//   - MaterialInstance::compile(CompilerPriorityQueue, UserVariantFilterBit, backend::CallbackHandler * _Nullable, utils::Invocable<void (MaterialInstance * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (MaterialInstance * _Nonnull)> &&, and JavaScript has no way to move a value
//   - MaterialInstance::compile(CompilerPriorityQueue, backend::CallbackHandler * _Nullable, utils::Invocable<void (MaterialInstance * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (MaterialInstance * _Nonnull)> &&, and JavaScript has no way to move a value


class_<std::vector<MaterialInstance*>>("MaterialInstanceVector")
    .function("size", EMBIND_LAMBDA(size_t, (std::vector<MaterialInstance*>* self), {
        return self->size();
    }), allow_raw_pointers())
    .function("get", EMBIND_LAMBDA(MaterialInstance*, (std::vector<MaterialInstance*>* self, size_t i), {
        return (*self)[i];
    }), allow_raw_pointers())
    ;

} // EMSCRIPTEN_BINDINGS
