// This file has been generated by beamsplitter

#include <filament/Material.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::Material>(filament::Material* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_Material) {

class_<filament::Material>("Material")
    .function("createInstance", &filament::Material::createInstance, allow_raw_pointers())
    .function("getName", &filament::Material::getName, allow_raw_pointers())
    .function("getShading", &filament::Material::getShading)
    .function("getInterpolation", &filament::Material::getInterpolation)
    .function("getBlendingMode", &filament::Material::getBlendingMode)
    .function("getVertexDomain", &filament::Material::getVertexDomain)
    .function("getSupportedVariants", &filament::Material::getSupportedVariants)
    .function("getMaterialDomain", &filament::Material::getMaterialDomain)
    .function("getCullingMode", &filament::Material::getCullingMode)
    .function("getTransparencyMode", &filament::Material::getTransparencyMode)
    .function("isColorWriteEnabled", &filament::Material::isColorWriteEnabled)
    .function("isDepthWriteEnabled", &filament::Material::isDepthWriteEnabled)
    .function("isDepthCullingEnabled", &filament::Material::isDepthCullingEnabled)
    .function("isDoubleSided", &filament::Material::isDoubleSided)
    .function("isAlphaToCoverageEnabled", &filament::Material::isAlphaToCoverageEnabled)
    .function("getMaskThreshold", &filament::Material::getMaskThreshold)
    .function("hasShadowMultiplier", &filament::Material::hasShadowMultiplier)
    .function("hasSpecularAntiAliasing", &filament::Material::hasSpecularAntiAliasing)
    .function("getSpecularAntiAliasingVariance", &filament::Material::getSpecularAntiAliasingVariance)
    .function("getSpecularAntiAliasingThreshold", &filament::Material::getSpecularAntiAliasingThreshold)
    .function("getRefractionMode", &filament::Material::getRefractionMode)
    .function("getRefractionType", &filament::Material::getRefractionType)
    .function("getReflectionMode", &filament::Material::getReflectionMode)
    .function("getFeatureLevel", &filament::Material::getFeatureLevel)
    .function("getParameterCount", &filament::Material::getParameterCount)
    .function("isSampler", &filament::Material::isSampler, allow_raw_pointers())
    .function("getSource", &filament::Material::getSource)
    .function("getParameterTransformName", &filament::Material::getParameterTransformName, allow_raw_pointers())
    .function("setDefaultParameterBool", static_cast<void (filament::Material::*)(const char*, bool) noexcept>(&filament::Material::setDefaultParameter<bool>), allow_raw_pointers())
    .function("setDefaultParameterInt", static_cast<void (filament::Material::*)(const char*, int32_t) noexcept>(&filament::Material::setDefaultParameter<int32_t>), allow_raw_pointers())
    .function("setDefaultParameterString", static_cast<void (filament::Material::*)(const char*, uint32_t) noexcept>(&filament::Material::setDefaultParameter<uint32_t>), allow_raw_pointers())
    .function("setDefaultParameterFloat", static_cast<void (filament::Material::*)(const char*, float) noexcept>(&filament::Material::setDefaultParameter<float>), allow_raw_pointers())
    .function("setDefaultParameterFloat2", static_cast<void (filament::Material::*)(const char*, filament::math::details::TVec2<float>) noexcept>(&filament::Material::setDefaultParameter<filament::math::float2>), allow_raw_pointers())
    .function("setDefaultParameterFloat3", static_cast<void (filament::Material::*)(const char*, filament::math::details::TVec3<float>) noexcept>(&filament::Material::setDefaultParameter<filament::math::float3>), allow_raw_pointers())
    .function("setDefaultParameterFloat4", static_cast<void (filament::Material::*)(const char*, filament::math::details::TVec4<float>) noexcept>(&filament::Material::setDefaultParameter<filament::math::float4>), allow_raw_pointers())
    .function("setDefaultParameterMat3f", (void (*) (filament::Material* self, std::string name, flatmat3 value)) [](filament::Material* self, std::string name, flatmat3 value) -> void {
        self->setDefaultParameter<filament::math::mat3f>(name.c_str(), filament::math::details::TMat33<float>(value.m));
    }, allow_raw_pointers())
    .function("setDefaultParameterMat4f", (void (*) (filament::Material* self, std::string name, flatmat4 value)) [](filament::Material* self, std::string name, flatmat4 value) -> void {
        self->setDefaultParameter<filament::math::mat4f>(name.c_str(), filament::math::details::TMat44<float>(value.m));
    }, allow_raw_pointers())
    .function("setDefaultParameterTextureSampler", static_cast<void (filament::Material::*)(const char*, const filament::Texture*, const filament::TextureSampler&) noexcept>(&filament::Material::setDefaultParameter), allow_raw_pointers())
    .function("setDefaultParameterFloat3", static_cast<void (filament::Material::*)(const char*, filament::RgbType, filament::math::details::TVec3<float>) noexcept>(&filament::Material::setDefaultParameter), allow_raw_pointers())
    .function("setDefaultParameterFloat4", static_cast<void (filament::Material::*)(const char*, filament::RgbaType, filament::math::details::TVec4<float>) noexcept>(&filament::Material::setDefaultParameter), allow_raw_pointers())
    .function("getDefaultInstance", static_cast<filament::MaterialInstance* (filament::Material::*)() noexcept>(&filament::Material::getDefaultInstance), allow_raw_pointers())
    ;

class_<filament::Material::Builder>("Material$Builder")
    .constructor<>()
    .function("sphericalHarmonicsBandCount", (filament::Material::Builder* (*) (filament::Material::Builder* self, size_t shBandCount)) [](filament::Material::Builder* self, size_t shBandCount) -> filament::Material::Builder* {
        return &self->sphericalHarmonicsBandCount(shBandCount);
    }, allow_raw_pointers())
    .function("shadowSamplingQuality", (filament::Material::Builder* (*) (filament::Material::Builder* self, filament::Material::Builder::ShadowSamplingQuality quality)) [](filament::Material::Builder* self, filament::Material::Builder::ShadowSamplingQuality quality) -> filament::Material::Builder* {
        return &self->shadowSamplingQuality(quality);
    }, allow_raw_pointers())
    .function("uboBatching", (filament::Material::Builder* (*) (filament::Material::Builder* self, filament::Material::UboBatchingMode uboBatchingMode)) [](filament::Material::Builder* self, filament::Material::UboBatchingMode uboBatchingMode) -> filament::Material::Builder* {
        return &self->uboBatching(uboBatchingMode);
    }, allow_raw_pointers())
    .function("build", &filament::Material::Builder::build, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Material::compile(CompilerPriorityQueue, UserVariantFilterMask, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (Material * _Nonnull)> &&, and JavaScript has no way to move a value
//   - Material::compile(CompilerPriorityQueue, UserVariantFilterBit, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (Material * _Nonnull)> &&, and JavaScript has no way to move a value
//   - Material::compile(CompilerPriorityQueue, backend::CallbackHandler * _Nullable, utils::Invocable<void (Material * _Nonnull)> &&): parameter "callback": takes utils::Invocable<void (Material * _Nonnull)> &&, and JavaScript has no way to move a value
//   - Material::getRequiredAttributes() const: return type is utils::bitset<unsigned int>, which is not bound
//   - Material::getParameters(ParameterInfo * _Nonnull, size_t) const: parameter "parameters": struct array with no element type
//   - Material::hasParameter(const char * _Nonnull) const: 2 bound methods share the target key "hasParameter/1"
//   - Material::hasParameter(std::string_view) const: 2 bound methods share the target key "hasParameter/1"
//   - Builder::package(const void * _Nonnull, size_t): parameter "payload": const void * _Nonnull is opaque, so there is nothing to marshal


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
