// This file has been generated by beamsplitter

#include <backend/Platform.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::backend::Platform::ExternalImage>(filament::backend::Platform::ExternalImage* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_Platform) {

class_<filament::backend::Platform>("Platform")
    .function("getOSVersion", &filament::backend::Platform::getOSVersion)
    .function("pumpEvents", &filament::backend::Platform::pumpEvents)
    .function("isCompositorTimingSupported", &filament::backend::Platform::isCompositorTimingSupported)
    .function("hasInsertBlobFunc", &filament::backend::Platform::hasInsertBlobFunc)
    .function("hasRetrieveBlobFunc", &filament::backend::Platform::hasRetrieveBlobFunc)
    .function("hasBlobFunc", &filament::backend::Platform::hasBlobFunc)
    .function("hasDebugUpdateStatFunc", &filament::backend::Platform::hasDebugUpdateStatFunc)
    .function("debugUpdateStat", static_cast<void (filament::backend::Platform::*)(const char*, uint64_t)>(&filament::backend::Platform::debugUpdateStat), allow_raw_pointers())
    ;

class_<filament::backend::Platform::ExternalImage>("Platform$ExternalImage")
    ;

class_<filament::backend::Platform::ExternalImageHandle>("Platform$ExternalImageHandle")
    .constructor<>()
    .constructor<filament::backend::Platform::ExternalImage*>()
    .function("equals", &filament::backend::Platform::ExternalImageHandle::operator==)
    .function("get", static_cast<filament::backend::Platform::ExternalImage* (filament::backend::Platform::ExternalImageHandle::*)() noexcept>(&filament::backend::Platform::ExternalImageHandle::get), allow_raw_pointers())
    .function("clear", &filament::backend::Platform::ExternalImageHandle::clear)
    .function("reset", &filament::backend::Platform::ExternalImageHandle::reset, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Platform::Platform(): the class is abstract, so there is nothing to construct
//   - Platform::getDeviceInfo(DeviceInfoType, Driver * _Nullable) const: parameter "driver": struct array with no element type
//   - Platform::createDriver(void * _Nullable, const DriverConfig &): parameter "sharedContext": void * _Nullable is opaque, so there is nothing to marshal
//   - Platform::queryCompositorTiming(const SwapChain * _Nonnull, CompositorTiming * _Nonnull) const: parameter "swapchain": struct array with no element type
//   - Platform::setPresentFrameId(const SwapChain * _Nonnull, uint64_t): parameter "swapchain": struct array with no element type
//   - Platform::queryFrameTimestamps(const SwapChain * _Nonnull, uint64_t, FrameTimestamps * _Nonnull) const: parameter "swapchain": struct array with no element type
//   - Platform::isFrameRateChangeSupported(void * _Nullable) const: parameter "nativeWindow": void * _Nullable is opaque, so there is nothing to marshal
//   - Platform::setFrameRate(const SwapChain * _Nonnull, float, FrameRateCompatibility, ChangeFrameRateStrategy): parameter "swapchain": struct array with no element type
//   - Platform::setBlobFunc(InsertBlobFunc &&, RetrieveBlobFunc &&): parameter "insertBlob": takes InsertBlobFunc &&, and JavaScript has no way to move a value
//   - Platform::insertBlob(const void * _Nonnull, size_t, const void * _Nonnull, size_t): parameter "key": const void * _Nonnull is opaque, so there is nothing to marshal
//   - Platform::retrieveBlob(const void * _Nonnull, size_t, void * _Nonnull, size_t): parameter "key": const void * _Nonnull is opaque, so there is nothing to marshal
//   - Platform::setDebugUpdateStatFunc(DebugUpdateStatFunc &&): parameter "debugUpdateStat": takes DebugUpdateStatFunc &&, and JavaScript has no way to move a value
//   - Platform::debugUpdateStat(const char * _Nonnull, utils::CString): parameter "stringValue" is utils::CString, which is not bound


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
