// This file has been generated by beamsplitter

#include <filament/Renderer.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::Renderer>(filament::Renderer* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_Renderer) {

class_<filament::Renderer>("Renderer")
    .function("getMaxFrameHistorySize", &filament::Renderer::getMaxFrameHistorySize)
    .function("setDisplayInfo", &filament::Renderer::setDisplayInfo)
    .function("setFrameRateOptions", &filament::Renderer::setFrameRateOptions)
    .function("setClearOptions", &filament::Renderer::setClearOptions)
    .function("getClearOptions", (const filament::Renderer::ClearOptions* (*) (filament::Renderer* self)) [](filament::Renderer* self) -> const filament::Renderer::ClearOptions* {
        return &self->getClearOptions();
    }, allow_raw_pointers())
    .function("getEngine", static_cast<filament::Engine* (filament::Renderer::*)() noexcept>(&filament::Renderer::getEngine), allow_raw_pointers())
    .function("setVsyncTime", &filament::Renderer::setVsyncTime)
    .function("skipFrame", &filament::Renderer::skipFrame)
    .function("shouldRenderFrame", &filament::Renderer::shouldRenderFrame)
    .function("beginFrame", &filament::Renderer::beginFrame, allow_raw_pointers())
    .function("setPresentationTime", static_cast<void (filament::Renderer::*)(int64_t)>(&filament::Renderer::setPresentationTime))
    .function("setDesiredPresentationTime", static_cast<void (filament::Renderer::*)(int64_t)>(&filament::Renderer::setDesiredPresentationTime))
    .function("setRenderingDeadline", static_cast<void (filament::Renderer::*)(int64_t)>(&filament::Renderer::setRenderingDeadline))
    .function("render", &filament::Renderer::render, allow_raw_pointers())
    .function("copyFrame", &filament::Renderer::copyFrame, allow_raw_pointers())
    .function("readPixels", (void (*) (filament::Renderer* self, uint32_t xoffset, uint32_t yoffset, uint32_t width, uint32_t height, PixelBufferDescriptor buffer)) [](filament::Renderer* self, uint32_t xoffset, uint32_t yoffset, uint32_t width, uint32_t height, PixelBufferDescriptor buffer) -> void {
        self->readPixels(xoffset, yoffset, width, height, std::move(*buffer.pbd));
    }, allow_raw_pointers())
    .function("endFrame", &filament::Renderer::endFrame)
    .function("readPixels", (void (*) (filament::Renderer* self, filament::RenderTarget* renderTarget, uint32_t xoffset, uint32_t yoffset, uint32_t width, uint32_t height, PixelBufferDescriptor buffer)) [](filament::Renderer* self, filament::RenderTarget* renderTarget, uint32_t xoffset, uint32_t yoffset, uint32_t width, uint32_t height, PixelBufferDescriptor buffer) -> void {
        self->readPixels(renderTarget, xoffset, yoffset, width, height, std::move(*buffer.pbd));
    }, allow_raw_pointers())
    .function("renderStandaloneView", &filament::Renderer::renderStandaloneView, allow_raw_pointers())
    .function("getMaterialTime", &filament::Renderer::getMaterialTime)
    .function("getUserTime", &filament::Renderer::getUserTime)
    .function("setMaterialTimeEpoch", static_cast<void (filament::Renderer::*)(int64_t)>(&filament::Renderer::setMaterialTimeEpoch))
    .function("resetUserTime", &filament::Renderer::resetUserTime)
    .function("skipNextFrames", &filament::Renderer::skipNextFrames)
    .function("getFrameToSkipCount", &filament::Renderer::getFrameToSkipCount)
    .function("hasGpuFallenBehind", &filament::Renderer::hasGpuFallenBehind)
    .function("setFrameScheduleTime", static_cast<void (filament::Renderer::*)(uint64_t) noexcept>(&filament::Renderer::setFrameScheduleTime))
    .function("pauseRenderThread", &filament::Renderer::pauseRenderThread)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Renderer::getFrameInfoHistory(size_t) const: returns unresolved type utils::FixedCapacityVector<FrameInfo>
//   - Renderer::setPresentationTime(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setDesiredPresentationTime(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setRenderingDeadline(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setMaterialTimeEpoch(std::chrono::steady_clock::time_point): parameter "monotonic_clock" has unresolved type std::chrono::steady_clock::time_point
//   - Renderer::setFrameScheduleTime(std::chrono::steady_clock::time_point): parameter "time" has unresolved type std::chrono::steady_clock::time_point


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
