// This file has been generated by beamsplitter

#include <filament/Skybox.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::Skybox>(filament::Skybox* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_Skybox) {

class_<filament::Skybox>("Skybox")
    .function("setColor", &filament::Skybox::setColor)
    .function("setLayerMask", &filament::Skybox::setLayerMask)
    .function("getLayerMask", &filament::Skybox::getLayerMask)
    .function("getIntensity", &filament::Skybox::getIntensity)
    .function("getTexture", &filament::Skybox::getTexture, allow_raw_pointers())
    ;

class_<filament::Skybox::Builder>("Skybox$Builder")
    .constructor<>()
    .function("environment", (filament::Skybox::Builder* (*) (filament::Skybox::Builder* self, filament::Texture* cubemap)) [](filament::Skybox::Builder* self, filament::Texture* cubemap) -> filament::Skybox::Builder* {
        return &self->environment(cubemap);
    }, allow_raw_pointers())
    .function("showSun", (filament::Skybox::Builder* (*) (filament::Skybox::Builder* self, bool show)) [](filament::Skybox::Builder* self, bool show) -> filament::Skybox::Builder* {
        return &self->showSun(show);
    }, allow_raw_pointers())
    .function("intensity", (filament::Skybox::Builder* (*) (filament::Skybox::Builder* self, float envIntensity)) [](filament::Skybox::Builder* self, float envIntensity) -> filament::Skybox::Builder* {
        return &self->intensity(envIntensity);
    }, allow_raw_pointers())
    .function("color", (filament::Skybox::Builder* (*) (filament::Skybox::Builder* self, filament::math::details::TVec4<float> color)) [](filament::Skybox::Builder* self, filament::math::details::TVec4<float> color) -> filament::Skybox::Builder* {
        return &self->color(color);
    }, allow_raw_pointers())
    .function("priority", (filament::Skybox::Builder* (*) (filament::Skybox::Builder* self, uint8_t priority)) [](filament::Skybox::Builder* self, uint8_t priority) -> filament::Skybox::Builder* {
        return &self->priority(priority);
    }, allow_raw_pointers())
    .function("build", &filament::Skybox::Builder::build, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.


} // EMSCRIPTEN_BINDINGS
