// This file has been generated by beamsplitter

#include <filament/Sync.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::Sync>(filament::Sync* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_Sync) {

class_<filament::Sync>("Sync")
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Sync::getExternalHandle(CallbackHandler *, Callback, void *): parameter "handler": struct array with no element type


} // EMSCRIPTEN_BINDINGS
