// This file has been generated by beamsplitter

#include <filament/TextureSampler.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filament_TextureSampler) {

class_<filament::TextureSampler>("TextureSampler")
    .constructor<>()
    .constructor<filament::backend::SamplerParams>()
    .constructor<filament::backend::SamplerMinFilter, filament::backend::SamplerMagFilter, filament::backend::SamplerWrapMode>()
    .constructor<filament::backend::SamplerMinFilter, filament::backend::SamplerMagFilter, filament::backend::SamplerWrapMode, filament::backend::SamplerWrapMode, filament::backend::SamplerWrapMode>()
    .function("setMinFilter", &filament::TextureSampler::setMinFilter)
    .function("setMagFilter", &filament::TextureSampler::setMagFilter)
    .function("setWrapModeS", &filament::TextureSampler::setWrapModeS)
    .function("setWrapModeT", &filament::TextureSampler::setWrapModeT)
    .function("setWrapModeR", &filament::TextureSampler::setWrapModeR)
    .function("setAnisotropy", &filament::TextureSampler::setAnisotropy)
    .function("setCompareMode", &filament::TextureSampler::setCompareMode)
    .function("getMinFilter", &filament::TextureSampler::getMinFilter)
    .function("getMagFilter", &filament::TextureSampler::getMagFilter)
    .function("getWrapModeS", &filament::TextureSampler::getWrapModeS)
    .function("getWrapModeT", &filament::TextureSampler::getWrapModeT)
    .function("getWrapModeR", &filament::TextureSampler::getWrapModeR)
    .function("getAnisotropy", &filament::TextureSampler::getAnisotropy)
    .function("getCompareMode", &filament::TextureSampler::getCompareMode)
    .function("getCompareFunc", &filament::TextureSampler::getCompareFunc)
    .function("getSamplerParams", &filament::TextureSampler::getSamplerParams)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - TextureSampler::TextureSampler(MagFilter, WrapMode): 2 bound methods share the target key "TextureSampler/2"
//   - TextureSampler::TextureSampler(CompareMode, CompareFunc): 2 bound methods share the target key "TextureSampler/2"


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
