// This file has been generated by beamsplitter

#include <filament/View.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

// Filament keeps the destructor of everything the engine owns to itself, so
// embind has to be told, once per class, that it cannot delete one.
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<filament::View>(filament::View* ptr) {}
    }
}

EMSCRIPTEN_BINDINGS(filament_View) {

class_<filament::View>("View")
    .function("setName", &filament::View::setName, allow_raw_pointers())
    .function("getName", &filament::View::getName, allow_raw_pointers())
    .function("setScene", &filament::View::setScene, allow_raw_pointers())
    .function("getScene", static_cast<filament::Scene* (filament::View::*)() noexcept>(&filament::View::getScene), allow_raw_pointers())
    .function("setRenderTarget", &filament::View::setRenderTarget, allow_raw_pointers())
    .function("getRenderTarget", &filament::View::getRenderTarget, allow_raw_pointers())
    .function("setViewport", &filament::View::setViewport)
    .function("getViewport", (const filament::Viewport* (*) (filament::View* self)) [](filament::View* self) -> const filament::Viewport* {
        return &self->getViewport();
    }, allow_raw_pointers())
    .function("setCamera", &filament::View::setCamera, allow_raw_pointers())
    .function("hasCamera", &filament::View::hasCamera)
    .function("getCamera", (filament::Camera* (*) (filament::View* self)) [](filament::View* self) -> filament::Camera* {
        return &self->getCamera();
    }, allow_raw_pointers())
    .function("setChannelDepthClearEnabled", &filament::View::setChannelDepthClearEnabled)
    .function("isChannelDepthClearEnabled", &filament::View::isChannelDepthClearEnabled)
    .function("setBlendMode", &filament::View::setBlendMode)
    .function("getBlendMode", &filament::View::getBlendMode)
    .function("setVisibleLayers", &filament::View::setVisibleLayers)
    .function("setLayerEnabled", &filament::View::setLayerEnabled)
    .function("getVisibleLayers", &filament::View::getVisibleLayers)
    .function("setShadowingEnabled", &filament::View::setShadowingEnabled)
    .function("isShadowingEnabled", &filament::View::isShadowingEnabled)
    .function("setScreenSpaceRefractionEnabled", &filament::View::setScreenSpaceRefractionEnabled)
    .function("isScreenSpaceRefractionEnabled", &filament::View::isScreenSpaceRefractionEnabled)
    .function("setSampleCount", &filament::View::setSampleCount)
    .function("getSampleCount", &filament::View::getSampleCount)
    .function("setAntiAliasing", &filament::View::setAntiAliasing)
    .function("getAntiAliasing", &filament::View::getAntiAliasing)
    .function("setTemporalAntiAliasingOptions", &filament::View::setTemporalAntiAliasingOptions)
    .function("getTemporalAntiAliasingOptions", (const filament::TemporalAntiAliasingOptions* (*) (filament::View* self)) [](filament::View* self) -> const filament::TemporalAntiAliasingOptions* {
        return &self->getTemporalAntiAliasingOptions();
    }, allow_raw_pointers())
    .function("setScreenSpaceReflectionsOptions", &filament::View::setScreenSpaceReflectionsOptions)
    .function("getScreenSpaceReflectionsOptions", (const filament::ScreenSpaceReflectionsOptions* (*) (filament::View* self)) [](filament::View* self) -> const filament::ScreenSpaceReflectionsOptions* {
        return &self->getScreenSpaceReflectionsOptions();
    }, allow_raw_pointers())
    .function("setGuardBandOptions", &filament::View::setGuardBandOptions)
    .function("getGuardBandOptions", (const filament::GuardBandOptions* (*) (filament::View* self)) [](filament::View* self) -> const filament::GuardBandOptions* {
        return &self->getGuardBandOptions();
    }, allow_raw_pointers())
    .function("setMultiSampleAntiAliasingOptions", &filament::View::setMultiSampleAntiAliasingOptions)
    .function("getMultiSampleAntiAliasingOptions", (const filament::MultiSampleAntiAliasingOptions* (*) (filament::View* self)) [](filament::View* self) -> const filament::MultiSampleAntiAliasingOptions* {
        return &self->getMultiSampleAntiAliasingOptions();
    }, allow_raw_pointers())
    .function("setColorGrading", &filament::View::setColorGrading, allow_raw_pointers())
    .function("getColorGrading", &filament::View::getColorGrading, allow_raw_pointers())
    .function("setAmbientOcclusionOptions", &filament::View::setAmbientOcclusionOptions)
    .function("getAmbientOcclusionOptions", (const filament::AmbientOcclusionOptions* (*) (filament::View* self)) [](filament::View* self) -> const filament::AmbientOcclusionOptions* {
        return &self->getAmbientOcclusionOptions();
    }, allow_raw_pointers())
    .function("setBloomOptions", &filament::View::setBloomOptions)
    .function("getBloomOptions", &filament::View::getBloomOptions)
    .function("setFogOptions", &filament::View::setFogOptions)
    .function("getFogOptions", &filament::View::getFogOptions)
    .function("setDepthOfFieldOptions", &filament::View::setDepthOfFieldOptions)
    .function("getDepthOfFieldOptions", &filament::View::getDepthOfFieldOptions)
    .function("setVignetteOptions", &filament::View::setVignetteOptions)
    .function("getVignetteOptions", &filament::View::getVignetteOptions)
    .function("setDithering", &filament::View::setDithering)
    .function("getDithering", &filament::View::getDithering)
    .function("setDynamicResolutionOptions", &filament::View::setDynamicResolutionOptions)
    .function("getDynamicResolutionOptions", &filament::View::getDynamicResolutionOptions)
    .function("getLastDynamicResolutionScale", &filament::View::getLastDynamicResolutionScale)
    .function("setRenderQuality", &filament::View::setRenderQuality)
    .function("getRenderQuality", &filament::View::getRenderQuality)
    .function("setDynamicLightingOptions", &filament::View::setDynamicLightingOptions)
    .function("setGridSize", &filament::View::setGridSize)
    .function("getGridSize", &filament::View::getGridSize)
    .function("getEffectiveGridSize", &filament::View::getEffectiveGridSize)
    .function("setShadowType", &filament::View::setShadowType)
    .function("getShadowType", &filament::View::getShadowType)
    .function("setVsmShadowOptions", &filament::View::setVsmShadowOptions)
    .function("getVsmShadowOptions", &filament::View::getVsmShadowOptions)
    .function("setSoftShadowOptions", &filament::View::setSoftShadowOptions)
    .function("getSoftShadowOptions", &filament::View::getSoftShadowOptions)
    .function("setPostProcessingEnabled", &filament::View::setPostProcessingEnabled)
    .function("isPostProcessingEnabled", &filament::View::isPostProcessingEnabled)
    .function("setFrontFaceWindingInverted", &filament::View::setFrontFaceWindingInverted)
    .function("isFrontFaceWindingInverted", &filament::View::isFrontFaceWindingInverted)
    .function("setTransparentPickingEnabled", &filament::View::setTransparentPickingEnabled)
    .function("isTransparentPickingEnabled", &filament::View::isTransparentPickingEnabled)
    .function("setStencilBufferEnabled", &filament::View::setStencilBufferEnabled)
    .function("isStencilBufferEnabled", &filament::View::isStencilBufferEnabled)
    .function("setStereoscopicOptions", &filament::View::setStereoscopicOptions)
    .function("getStereoscopicOptions", (const filament::StereoscopicOptions* (*) (filament::View* self)) [](filament::View* self) -> const filament::StereoscopicOptions* {
        return &self->getStereoscopicOptions();
    }, allow_raw_pointers())
    .function("setFrustumCullingEnabled", &filament::View::setFrustumCullingEnabled)
    .function("isFrustumCullingEnabled", &filament::View::isFrustumCullingEnabled)
    .function("setDebugCamera", &filament::View::setDebugCamera, allow_raw_pointers())
    .function("setFroxelVizEnabled", &filament::View::setFroxelVizEnabled)
    .function("getFroxelConfigurationInfo", &filament::View::getFroxelConfigurationInfo)
    .function("setMaterialGlobal", &filament::View::setMaterialGlobal)
    .function("getMaterialGlobal", &filament::View::getMaterialGlobal)
    .function("getFogEntity", &filament::View::getFogEntity)
    .function("getVisibleRenderableCount", &filament::View::getVisibleRenderableCount)
    .function("clearFrameHistory", &filament::View::clearFrameHistory)
    .function("setAmbientOcclusion", &filament::View::setAmbientOcclusion)
    .function("getAmbientOcclusion", &filament::View::getAmbientOcclusion)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - View::getDirectionalShadowCameras() const: returns unresolved type utils::FixedCapacityVector<const Camera *>
//   - View::pick(uint32_t, uint32_t, backend::CallbackHandler * _Nullable, PickingQueryResultCallback _Nonnull): parameter "callback": PickingQueryResultCallback _Nonnull needs a hand-written bridge to a JavaScript function


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
