// This file has been generated by beamsplitter

#include <camutils/Bookmark.h>
#include <camutils/Manipulator.h>
#include <filament-iblprefilter/IBLPrefilterContext.h>
#include <filameshio/filamesh.h>
#include <geometry/TangentSpaceMesh.h>
#include <geometry/Transcoder.h>
#include <image/ImageSampler.h>
#include <ktxreader/Ktx2Reader.h>
#include <viewer/AutomationEngine.h>
#include <viewer/Settings.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filament_utils_enums) {

enum_<IBLPrefilterContext::Kernel>("IBLPrefilterContext$Kernel")
    .value("D_GGX", IBLPrefilterContext::Kernel::D_GGX)
    ;

enum_<filament::camutils::Fov>("camutils$Fov")
    .value("VERTICAL", filament::camutils::Fov::VERTICAL)
    .value("HORIZONTAL", filament::camutils::Fov::HORIZONTAL)
    ;

enum_<filament::camutils::Manipulator<float>::Key>("camutils$Manipulator$Key")
    .value("FORWARD", filament::camutils::Manipulator<float>::Key::FORWARD)
    .value("LEFT", filament::camutils::Manipulator<float>::Key::LEFT)
    .value("BACKWARD", filament::camutils::Manipulator<float>::Key::BACKWARD)
    .value("RIGHT", filament::camutils::Manipulator<float>::Key::RIGHT)
    .value("UP", filament::camutils::Manipulator<float>::Key::UP)
    .value("DOWN", filament::camutils::Manipulator<float>::Key::DOWN)
    .value("COUNT", filament::camutils::Manipulator<float>::Key::COUNT)
    ;

enum_<filament::camutils::Mode>("camutils$Mode")
    .value("ORBIT", filament::camutils::Mode::ORBIT)
    .value("MAP", filament::camutils::Mode::MAP)
    .value("FREE_FLIGHT", filament::camutils::Mode::FREE_FLIGHT)
    ;

enum_<filament::geometry::ComponentType>("geometry$ComponentType")
    .value("BYTE", filament::geometry::ComponentType::BYTE)
    .value("UBYTE", filament::geometry::ComponentType::UBYTE)
    .value("SHORT", filament::geometry::ComponentType::SHORT)
    .value("USHORT", filament::geometry::ComponentType::USHORT)
    .value("HALF", filament::geometry::ComponentType::HALF)
    .value("FLOAT", filament::geometry::ComponentType::FLOAT)
    ;

enum_<filament::geometry::TangentSpaceMesh::Algorithm>("geometry$TangentSpaceMesh$Algorithm")
    .value("DEFAULT", filament::geometry::TangentSpaceMesh::Algorithm::DEFAULT)
    .value("MIKKTSPACE", filament::geometry::TangentSpaceMesh::Algorithm::MIKKTSPACE)
    .value("LENGYEL", filament::geometry::TangentSpaceMesh::Algorithm::LENGYEL)
    .value("HUGHES_MOLLER", filament::geometry::TangentSpaceMesh::Algorithm::HUGHES_MOLLER)
    .value("FRISVAD", filament::geometry::TangentSpaceMesh::Algorithm::FRISVAD)
    ;

enum_<filament::geometry::TangentSpaceMesh::AuxAttribute>("geometry$TangentSpaceMesh$AuxAttribute")
    .value("UV1", filament::geometry::TangentSpaceMesh::AuxAttribute::UV1)
    .value("COLORS", filament::geometry::TangentSpaceMesh::AuxAttribute::COLORS)
    .value("JOINTS", filament::geometry::TangentSpaceMesh::AuxAttribute::JOINTS)
    .value("WEIGHTS", filament::geometry::TangentSpaceMesh::AuxAttribute::WEIGHTS)
    ;

enum_<filament::viewer::AutomationEngine::Options::ExportFormat>("viewer$AutomationEngine$Options$ExportFormat")
    .value("TIFF", filament::viewer::AutomationEngine::Options::ExportFormat::TIFF)
    .value("PPM", filament::viewer::AutomationEngine::Options::ExportFormat::PPM)
    ;

enum_<filament::viewer::CustomLut>("viewer$CustomLut")
    .value("NONE", filament::viewer::CustomLut::NONE)
    .value("NEGATIVE", filament::viewer::CustomLut::NEGATIVE)
    .value("GRAYSCALE", filament::viewer::CustomLut::GRAYSCALE)
    .value("SEPIA", filament::viewer::CustomLut::SEPIA)
    .value("TEAL_AND_ORANGE", filament::viewer::CustomLut::TEAL_AND_ORANGE)
    ;

enum_<filament::viewer::ToneMapping>("viewer$ToneMapping")
    .value("LINEAR", filament::viewer::ToneMapping::LINEAR)
    .value("ACES_LEGACY", filament::viewer::ToneMapping::ACES_LEGACY)
    .value("ACES", filament::viewer::ToneMapping::ACES)
    .value("FILMIC", filament::viewer::ToneMapping::FILMIC)
    .value("AGX", filament::viewer::ToneMapping::AGX)
    .value("GENERIC", filament::viewer::ToneMapping::GENERIC)
    .value("PBR_NEUTRAL", filament::viewer::ToneMapping::PBR_NEUTRAL)
    .value("GT7", filament::viewer::ToneMapping::GT7)
    .value("DISPLAY_RANGE", filament::viewer::ToneMapping::DISPLAY_RANGE)
    ;

enum_<filamesh::Flags>("filamesh$Flags")
    .value("INTERLEAVED", filamesh::Flags::INTERLEAVED)
    .value("TEXCOORD_SNORM16", filamesh::Flags::TEXCOORD_SNORM16)
    .value("COMPRESSION", filamesh::Flags::COMPRESSION)
    ;

enum_<filamesh::IndexType>("filamesh$IndexType")
    .value("UI32", filamesh::IndexType::UI32)
    .value("UI16", filamesh::IndexType::UI16)
    ;

enum_<image::Filter>("image$Filter")
    .value("DEFAULT", image::Filter::DEFAULT)
    .value("BOX", image::Filter::BOX)
    .value("NEAREST", image::Filter::NEAREST)
    .value("HERMITE", image::Filter::HERMITE)
    .value("GAUSSIAN_SCALARS", image::Filter::GAUSSIAN_SCALARS)
    .value("GAUSSIAN_NORMALS", image::Filter::GAUSSIAN_NORMALS)
    .value("MITCHELL", image::Filter::MITCHELL)
    .value("LANCZOS", image::Filter::LANCZOS)
    .value("MINIMUM", image::Filter::MINIMUM)
    ;

enum_<image::Orientation>("image$Orientation")
    .value("STANDARD", image::Orientation::STANDARD)
    .value("FLIP_X", image::Orientation::FLIP_X)
    .value("FLIP_Y", image::Orientation::FLIP_Y)
    .value("FLIP_XY", image::Orientation::FLIP_XY)
    ;

enum_<ktxreader::Ktx2Reader::Result>("ktxreader$Ktx2Reader$Result")
    .value("SUCCESS", ktxreader::Ktx2Reader::Result::SUCCESS)
    .value("COMPRESSED_TRANSCODE_FAILURE", ktxreader::Ktx2Reader::Result::COMPRESSED_TRANSCODE_FAILURE)
    .value("UNCOMPRESSED_TRANSCODE_FAILURE", ktxreader::Ktx2Reader::Result::UNCOMPRESSED_TRANSCODE_FAILURE)
    .value("FORMAT_UNSUPPORTED", ktxreader::Ktx2Reader::Result::FORMAT_UNSUPPORTED)
    .value("FORMAT_ALREADY_REQUESTED", ktxreader::Ktx2Reader::Result::FORMAT_ALREADY_REQUESTED)
    ;

enum_<ktxreader::Ktx2Reader::TransferFunction>("ktxreader$Ktx2Reader$TransferFunction")
    .value("LINEAR", ktxreader::Ktx2Reader::TransferFunction::LINEAR)
    .value("sRGB", ktxreader::Ktx2Reader::TransferFunction::sRGB)
    ;

} // EMSCRIPTEN_BINDINGS
