// This file has been generated by beamsplitter

#include <viewer/AutomationSpec.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filament_utils_AutomationSpec) {

class_<filament::viewer::AutomationSpec>("viewer$AutomationSpec")
    .class_function("generate", &filament::viewer::AutomationSpec::generate, allow_raw_pointers())
    .class_function("generateDefaultTestCases", &filament::viewer::AutomationSpec::generateDefaultTestCases, allow_raw_pointers())
    .function("size", &filament::viewer::AutomationSpec::size)
    .function("getName", &filament::viewer::AutomationSpec::getName, allow_raw_pointers())
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.


class_<AutomationSpec>("AutomationSpec")
    .class_function("generate", EMBIND_LAMBDA(AutomationSpec*, (std::string json), {
        return AutomationSpec::generate(json.c_str(), json.length());
    }), allow_raw_pointers())
    .class_function("generateDefaultTestCases", &AutomationSpec::generateDefaultTestCases, allow_raw_pointers())
    .function("size", &AutomationSpec::size)
    .function("get", &AutomationSpec::get, allow_raw_pointers())
    .function("getName", EMBIND_LAMBDA(std::string, (AutomationSpec* self, size_t index), {
        return std::string(self->getName(index));
    }), allow_raw_pointers())
    ;

} // EMSCRIPTEN_BINDINGS
