// This file has been generated by beamsplitter

#include <image/Ktx1Bundle.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filament_utils_Ktx1Bundle) {

class_<image::Ktx1Bundle>("image$Ktx1Bundle")
    .constructor<uint32_t, uint32_t, bool>()
    .constructor<const uint8_t*, uint32_t>()
    .function("serialize", (bool (*) (image::Ktx1Bundle* self, emscripten::val destination, uint32_t numBytes)) [](image::Ktx1Bundle* self, emscripten::val destination, uint32_t numBytes) -> bool {
        auto destination_ = emscripten::convertJSArrayToNumberVector<uint8_t>(destination);
        bool result = self->serialize(reinterpret_cast<uint8_t*>(destination_.data()), numBytes);
        for (size_t i = 0; i < destination_.size(); i++) destination.set(i, destination_[i]);
        return result;
    }, allow_raw_pointers())
    .function("getSerializedLength", &image::Ktx1Bundle::getSerializedLength)
    .function("getInfo", (const image::KtxInfo* (*) (image::Ktx1Bundle* self)) [](image::Ktx1Bundle* self) -> const image::KtxInfo* {
        return &self->getInfo();
    }, allow_raw_pointers())
    .function("info", (image::KtxInfo* (*) (image::Ktx1Bundle* self)) [](image::Ktx1Bundle* self) -> image::KtxInfo* {
        return &self->info();
    }, allow_raw_pointers())
    .function("getMetadata", (std::string (*) (image::Ktx1Bundle* self, std::string key, emscripten::val valueSize)) [](image::Ktx1Bundle* self, std::string key, emscripten::val valueSize) -> std::string {
        auto valueSize_ = emscripten::convertJSArrayToNumberVector<size_t>(valueSize);
        std::string result = self->getMetadata(key.c_str(), reinterpret_cast<size_t*>(valueSize_.data()));
        for (size_t i = 0; i < valueSize_.size(); i++) valueSize.set(i, valueSize_[i]);
        return result;
    }, allow_raw_pointers())
    .function("setMetadata", &image::Ktx1Bundle::setMetadata, allow_raw_pointers())
    .function("getSphericalHarmonics", (bool (*) (image::Ktx1Bundle* self, emscripten::val result)) [](image::Ktx1Bundle* self, emscripten::val result) -> bool {
        auto result_ = emscripten::convertJSArrayToNumberVector<float>(result);
        bool result__ = self->getSphericalHarmonics(reinterpret_cast<filament::math::details::TVec3<float>*>(result_.data()));
        for (size_t i = 0; i < result_.size(); i++) result.set(i, result_[i]);
        return result__;
    }, allow_raw_pointers())
    .function("getNumMipLevels", &image::Ktx1Bundle::getNumMipLevels)
    .function("getArrayLength", &image::Ktx1Bundle::getArrayLength)
    .function("isCubemap", &image::Ktx1Bundle::isCubemap)
    .function("setBlob", (bool (*) (image::Ktx1Bundle* self, image::KtxBlobIndex index, emscripten::val data, uint32_t size)) [](image::Ktx1Bundle* self, image::KtxBlobIndex index, emscripten::val data, uint32_t size) -> bool {
        auto data_ = emscripten::convertJSArrayToNumberVector<uint8_t>(data);
        return self->setBlob(index, reinterpret_cast<const uint8_t*>(data_.data()), size);
    }, allow_raw_pointers())
    .function("allocateBlob", &image::Ktx1Bundle::allocateBlob)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Ktx1Bundle::getBlob(KtxBlobIndex, uint8_t **, uint32_t *) const: parameter "data" has unresolved type uint8_t **


class_<Ktx1Bundle>("Ktx1Bundle")
    .constructor(EMBIND_LAMBDA(Ktx1Bundle*, (BufferDescriptor kbd), {
        return new Ktx1Bundle((uint8_t*) kbd.bd->buffer, (uint32_t) kbd.bd->size);
    }))

    /// info ::method:: Obtains properties of the KTX header.
    /// ::retval:: The [KtxInfo] property accessor object.
    .function("getNumMipLevels", &Ktx1Bundle::getNumMipLevels)

    /// getArrayLength ::method:: Obtains length of the texture array.
    /// ::retval:: The number of elements in the texture array
    .function("getArrayLength", &Ktx1Bundle::getArrayLength)

    /// getInternalFormat ::method::
    /// srgb ::argument:: boolean that forces the resulting format to SRGB if possible.
    /// ::retval:: [Texture$InternalFormat]
    /// Returns "undefined" if no valid Filament enumerant exists.
    .function("getInternalFormat",
            EMBIND_LAMBDA(Texture::InternalFormat, (Ktx1Bundle* self, bool srgb), {
        auto result = Ktx1Reader::toTextureFormat(self->info());
        if (srgb) {
            if (result == Texture::InternalFormat::RGB8) {
                result = Texture::InternalFormat::SRGB8;
            }
            if (result == Texture::InternalFormat::RGBA8) {
                result = Texture::InternalFormat::SRGB8_A8;
            }
        }
        return result;
    }), allow_raw_pointers())

    /// getPixelDataFormat ::method::
    /// ::retval:: [PixelDataFormat]
    /// Returns "undefined" if no valid Filament enumerant exists.
    .function("getPixelDataFormat",
            EMBIND_LAMBDA(backend::PixelDataFormat, (Ktx1Bundle* self), {
        return Ktx1Reader::toPixelDataFormat(self->getInfo());
    }), allow_raw_pointers())

    /// getPixelDataType ::method::
    /// ::retval:: [PixelDataType]
    /// Returns "undefined" if no valid Filament enumerant exists.
    .function("getPixelDataType",
            EMBIND_LAMBDA(backend::PixelDataType, (Ktx1Bundle* self), {
        return Ktx1Reader::toPixelDataType(self->getInfo());
    }), allow_raw_pointers())

    /// getCompressedPixelDataType ::method::
    /// ::retval:: [CompressedPixelDataType]
    /// Returns "undefined" if no valid Filament enumerant exists.
    .function("getCompressedPixelDataType",
            EMBIND_LAMBDA(backend::CompressedPixelDataType, (Ktx1Bundle* self), {
        return Ktx1Reader::toCompressedPixelDataType(self->getInfo());
    }), allow_raw_pointers())

    /// isCompressed ::method::
    /// Per spec, compressed textures in KTX always have their glFormat field set to 0.
    /// ::retval:: boolean
    .function("isCompressed", EMBIND_LAMBDA(bool, (Ktx1Bundle* self), {
        return Ktx1Reader::isCompressed(self->getInfo());
    }), allow_raw_pointers())

    .function("isCubemap", &Ktx1Bundle::isCubemap)
    .function("_getBlob", EMBIND_LAMBDA(BufferDescriptor, (Ktx1Bundle* self, KtxBlobIndex index), {
        uint8_t* data = nullptr;
        uint32_t size = 0;
        if (!self->getBlob(index, &data, &size)) {
            utils::slog.e << "Missing or invalid KTX blob at mip level " << index.mipLevel
                          << ", array index " << index.arrayIndex << ", face "
                          << index.cubeFace << utils::io::endl;
            return BufferDescriptor(nullptr, 0);
        }
        return BufferDescriptor(data, size);
    }), allow_raw_pointers())
    .function("_getCubeBlob", EMBIND_LAMBDA(BufferDescriptor,
            (Ktx1Bundle* self, uint32_t miplevel), {
        uint8_t* data = nullptr;
        uint32_t size = 0;
        if (!self->getBlob({miplevel}, &data, &size)) {
            utils::slog.e << "Missing or invalid KTX cubemap mip level " << miplevel
                          << utils::io::endl;
            return BufferDescriptor(nullptr, 0);
        }
        return BufferDescriptor(data, size * 6);
    }), allow_raw_pointers())

    /// info ::method:: Obtains properties of the KTX header.
    /// ::retval:: The [KtxInfo] property accessor object.
    .function("info", &Ktx1Bundle::info)

    /// getMetadata ::method:: Obtains arbitrary metadata from the KTX file.
    /// key ::argument:: string
    /// ::retval:: string
    .function("getMetadata", EMBIND_LAMBDA(std::string, (Ktx1Bundle* self, std::string key), {
        return std::string(self->getMetadata(key.c_str()));
    }), allow_raw_pointers())
    ;

} // EMSCRIPTEN_BINDINGS
