// This file has been generated by beamsplitter

#include <viewer/Settings.h>

#include <jni.h>

#include <string>

// Copies filament::viewer::AgxToneMapperSettings to and from its Java counterpart, member by member.
static filament::viewer::AgxToneMapperSettings readAgxToneMapperSettings_generated(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::viewer::AgxToneMapperSettings out;
    out.look = (filament::AgxToneMapper::AgxLook) env->GetIntField(obj, env->GetFieldID(cls, "look", "I"));
    return out;
}

static jobject writeAgxToneMapperSettings_generated(JNIEnv* env, const filament::viewer::AgxToneMapperSettings& in) {
    jclass cls = env->FindClass("com/google/android/filament/utils/AgxToneMapperSettings_generated");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetIntField(obj, env->GetFieldID(cls, "look", "I"), (jint) in.look);
    return obj;
}


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_utils_AgxToneMapperSettings_1generated_nNotEquals(JNIEnv* env, jclass, jobject self, jobject rhs) {
    filament::viewer::AgxToneMapperSettings obj = readAgxToneMapperSettings_generated(env, self);
    return (jboolean) obj.operator!=(readAgxToneMapperSettings_generated(env, rhs));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_utils_AgxToneMapperSettings_1generated_nEquals(JNIEnv* env, jclass, jobject self, jobject rhs) {
    filament::viewer::AgxToneMapperSettings obj = readAgxToneMapperSettings_generated(env, self);
    return (jboolean) obj.operator==(readAgxToneMapperSettings_generated(env, rhs));
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
