// This file has been generated by beamsplitter

#include <viewer/Settings.h>

#include <jni.h>

#include <string>

// Copies filament::viewer::GenericToneMapperSettings to and from its Java counterpart, member by member.
static filament::viewer::GenericToneMapperSettings readGenericToneMapperSettings_generated(JNIEnv* env, jobject obj) {
    jclass cls = env->GetObjectClass(obj);
    filament::viewer::GenericToneMapperSettings out;
    out.contrast = env->GetFloatField(obj, env->GetFieldID(cls, "contrast", "F"));
    out.midGrayIn = env->GetFloatField(obj, env->GetFieldID(cls, "midGrayIn", "F"));
    out.midGrayOut = env->GetFloatField(obj, env->GetFieldID(cls, "midGrayOut", "F"));
    out.hdrMax = env->GetFloatField(obj, env->GetFieldID(cls, "hdrMax", "F"));
    return out;
}

static jobject writeGenericToneMapperSettings_generated(JNIEnv* env, const filament::viewer::GenericToneMapperSettings& in) {
    jclass cls = env->FindClass("com/google/android/filament/utils/GenericToneMapperSettings_generated");
    jobject obj = env->NewObject(cls, env->GetMethodID(cls, "<init>", "()V"));
    env->SetFloatField(obj, env->GetFieldID(cls, "contrast", "F"), (jfloat) in.contrast);
    env->SetFloatField(obj, env->GetFieldID(cls, "midGrayIn", "F"), (jfloat) in.midGrayIn);
    env->SetFloatField(obj, env->GetFieldID(cls, "midGrayOut", "F"), (jfloat) in.midGrayOut);
    env->SetFloatField(obj, env->GetFieldID(cls, "hdrMax", "F"), (jfloat) in.hdrMax);
    return obj;
}


extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_utils_GenericToneMapperSettings_1generated_nNotEquals(JNIEnv* env, jclass, jobject self, jobject rhs) {
    filament::viewer::GenericToneMapperSettings obj = readGenericToneMapperSettings_generated(env, self);
    return (jboolean) obj.operator!=(readGenericToneMapperSettings_generated(env, rhs));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_utils_GenericToneMapperSettings_1generated_nEquals(JNIEnv* env, jclass, jobject self, jobject rhs) {
    filament::viewer::GenericToneMapperSettings obj = readGenericToneMapperSettings_generated(env, self);
    return (jboolean) obj.operator==(readGenericToneMapperSettings_generated(env, rhs));
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
