// This file has been generated by beamsplitter

#include <viewer/Settings.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_JsonSerializer_1generated_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::viewer::JsonSerializer*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_JsonSerializer_1generated_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::viewer::JsonSerializer();
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_google_android_filament_utils_JsonSerializer_1generated_nWriteJson(JNIEnv* env, jclass, jlong nativeObject, jlong in) {
    return env->NewStringUTF((((filament::viewer::JsonSerializer*) nativeObject)->writeJson(*(filament::viewer::Settings*) in)).c_str());
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_utils_JsonSerializer_1generated_nReadJson(JNIEnv* env, jclass, jlong nativeObject, jstring jsonChunk, jlong size, jlong out) {
    const char* jsonChunk_ = env->GetStringUTFChars(jsonChunk, nullptr);
    jboolean result = (jboolean) ((filament::viewer::JsonSerializer*) nativeObject)->readJson(jsonChunk_, size, (filament::viewer::Settings*) out);
    env->ReleaseStringUTFChars(jsonChunk, jsonChunk_);
    return result;
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// Everything on this class was generated. Anything added below this comment
// block is preserved when regenerating.
