// This file has been generated by beamsplitter

#include <ktxreader/Ktx2Reader.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (ktxreader::Ktx2Reader*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_nCreate(JNIEnv* env, jclass, jlong engine, jboolean quiet) {
    return (jlong) new ktxreader::Ktx2Reader(*(filament::Engine*) engine, quiet);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_nRequestFormat(JNIEnv* env, jclass, jlong nativeObject, jint format) {
    return (jint) ((ktxreader::Ktx2Reader*) nativeObject)->requestFormat((filament::backend::TextureFormat) format);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_nUnrequestFormat(JNIEnv* env, jclass, jlong nativeObject, jint format) {
    ((ktxreader::Ktx2Reader*) nativeObject)->unrequestFormat((filament::backend::TextureFormat) format);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_00024Async_nGetTexture(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((ktxreader::Ktx2Reader::Async*) nativeObject)->getTexture();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_00024Async_nDoTranscoding(JNIEnv* env, jclass, jlong nativeObject) {
    return (jint) ((ktxreader::Ktx2Reader::Async*) nativeObject)->doTranscoding();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_Ktx2Reader_1generated_00024Async_nUploadImages(JNIEnv* env, jclass, jlong nativeObject) {
    ((ktxreader::Ktx2Reader::Async*) nativeObject)->uploadImages();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Ktx2Reader::load(const void *, size_t, TransferFunction): parameter "data": const void * is opaque, so there is nothing to marshal
//   - Ktx2Reader::asyncCreate(const void *, size_t, TransferFunction): parameter "data": const void * is opaque, so there is nothing to marshal
//   - Ktx2Reader::asyncDestroy(Async **): parameter "async" has unresolved type Async **
