// This file has been generated by beamsplitter

#include <geometry/SurfaceOrientation.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_nGetVertexCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::geometry::SurfaceOrientation*) nativeObject)->getVertexCount();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_nGetQuats__J_3FJJ(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out, jlong quatCount, jlong stride) {
    jfloat* out_ = env->GetFloatArrayElements(out, nullptr);
    ((filament::geometry::SurfaceOrientation*) nativeObject)->getQuats(reinterpret_cast<filament::math::details::TQuaternion<float>*>(out_), quatCount, stride);
    env->ReleaseFloatArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_nGetQuats__J_3SJJ(JNIEnv* env, jclass, jlong nativeObject, jshortArray out, jlong quatCount, jlong stride) {
    jshort* out_ = env->GetShortArrayElements(out, nullptr);
    ((filament::geometry::SurfaceOrientation*) nativeObject)->getQuats(reinterpret_cast<filament::math::details::TVec4<short>*>(out_), quatCount, stride);
    env->ReleaseShortArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::geometry::SurfaceOrientation::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::geometry::SurfaceOrientation::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nVertexCount(JNIEnv* env, jclass, jlong nativeObject, jlong vertexCount) {
    return (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->vertexCount(vertexCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nNormals(JNIEnv* env, jclass, jlong nativeObject, jfloatArray arg0, jlong stride) {
    jfloat* arg0_ = env->GetFloatArrayElements(arg0, nullptr);
    jlong result = (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->normals(reinterpret_cast<const filament::math::details::TVec3<float>*>(arg0_), stride);
    env->ReleaseFloatArrayElements(arg0, arg0_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nTangents(JNIEnv* env, jclass, jlong nativeObject, jfloatArray arg0, jlong stride) {
    jfloat* arg0_ = env->GetFloatArrayElements(arg0, nullptr);
    jlong result = (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->tangents(reinterpret_cast<const filament::math::details::TVec4<float>*>(arg0_), stride);
    env->ReleaseFloatArrayElements(arg0, arg0_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nUvs(JNIEnv* env, jclass, jlong nativeObject, jfloatArray arg0, jlong stride) {
    jfloat* arg0_ = env->GetFloatArrayElements(arg0, nullptr);
    jlong result = (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->uvs(reinterpret_cast<const filament::math::details::TVec2<float>*>(arg0_), stride);
    env->ReleaseFloatArrayElements(arg0, arg0_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nPositions(JNIEnv* env, jclass, jlong nativeObject, jfloatArray arg0, jlong stride) {
    jfloat* arg0_ = env->GetFloatArrayElements(arg0, nullptr);
    jlong result = (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->positions(reinterpret_cast<const filament::math::details::TVec3<float>*>(arg0_), stride);
    env->ReleaseFloatArrayElements(arg0, arg0_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nTriangleCount(JNIEnv* env, jclass, jlong nativeObject, jlong triangleCount) {
    return (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->triangleCount(triangleCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nTriangles__J_3I(JNIEnv* env, jclass, jlong nativeObject, jintArray arg0) {
    jint* arg0_ = env->GetIntArrayElements(arg0, nullptr);
    jlong result = (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->triangles(reinterpret_cast<const filament::math::details::TVec3<unsigned int>*>(arg0_));
    env->ReleaseIntArrayElements(arg0, arg0_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nTriangles__J_3S(JNIEnv* env, jclass, jlong nativeObject, jshortArray arg0) {
    jshort* arg0_ = env->GetShortArrayElements(arg0, nullptr);
    jlong result = (jlong) &((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->triangles(reinterpret_cast<const filament::math::details::TVec3<unsigned short>*>(arg0_));
    env->ReleaseShortArrayElements(arg0, arg0_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_SurfaceOrientation_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::geometry::SurfaceOrientation::Builder*) nativeObject)->build();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - SurfaceOrientation::getQuats(filament::math::quath *, size_t, size_t) const: parameter "out": quaternion array with no element type
