// This file has been generated by beamsplitter

#include <geometry/TangentSpaceMesh.h>
#include <math/mat4.h>
#include <math/vec4.h>

#include <jni.h>

#include <string>


extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nDestroy(JNIEnv* env, jclass, jlong mesh) {
    filament::geometry::TangentSpaceMesh::destroy((filament::geometry::TangentSpaceMesh*) mesh);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetVertexCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::geometry::TangentSpaceMesh*) nativeObject)->getVertexCount();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetPositions(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out, jlong stride) {
    jfloat* out_ = env->GetFloatArrayElements(out, nullptr);
    ((filament::geometry::TangentSpaceMesh*) nativeObject)->getPositions(reinterpret_cast<filament::math::details::TVec3<float>*>(out_), stride);
    env->ReleaseFloatArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetUVs(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out, jlong stride) {
    jfloat* out_ = env->GetFloatArrayElements(out, nullptr);
    ((filament::geometry::TangentSpaceMesh*) nativeObject)->getUVs(reinterpret_cast<filament::math::details::TVec2<float>*>(out_), stride);
    env->ReleaseFloatArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetQuats__J_3FJ(JNIEnv* env, jclass, jlong nativeObject, jfloatArray out, jlong stride) {
    jfloat* out_ = env->GetFloatArrayElements(out, nullptr);
    ((filament::geometry::TangentSpaceMesh*) nativeObject)->getQuats(reinterpret_cast<filament::math::details::TQuaternion<float>*>(out_), stride);
    env->ReleaseFloatArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetQuats__J_3SJ(JNIEnv* env, jclass, jlong nativeObject, jshortArray out, jlong stride) {
    jshort* out_ = env->GetShortArrayElements(out, nullptr);
    ((filament::geometry::TangentSpaceMesh*) nativeObject)->getQuats(reinterpret_cast<filament::math::details::TVec4<short>*>(out_), stride);
    env->ReleaseShortArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetTriangleCount(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::geometry::TangentSpaceMesh*) nativeObject)->getTriangleCount();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetTriangles__J_3I(JNIEnv* env, jclass, jlong nativeObject, jintArray out) {
    jint* out_ = env->GetIntArrayElements(out, nullptr);
    ((filament::geometry::TangentSpaceMesh*) nativeObject)->getTriangles(reinterpret_cast<filament::math::details::TVec3<unsigned int>*>(out_));
    env->ReleaseIntArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nGetTriangles__J_3S(JNIEnv* env, jclass, jlong nativeObject, jshortArray out) {
    jshort* out_ = env->GetShortArrayElements(out, nullptr);
    ((filament::geometry::TangentSpaceMesh*) nativeObject)->getTriangles(reinterpret_cast<filament::math::details::TVec3<unsigned short>*>(out_));
    env->ReleaseShortArrayElements(out, out_, 0);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_nRemeshed(JNIEnv* env, jclass, jlong nativeObject) {
    return (jboolean) ((filament::geometry::TangentSpaceMesh*) nativeObject)->remeshed();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nDestroy(JNIEnv*, jclass, jlong nativeObject) {
    delete (filament::geometry::TangentSpaceMesh::Builder*) nativeObject;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nCreate(JNIEnv* env, jclass) {
    return (jlong) new filament::geometry::TangentSpaceMesh::Builder();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nVertexCount(JNIEnv* env, jclass, jlong nativeObject, jlong vertexCount) {
    return (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->vertexCount(vertexCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nNormals(JNIEnv* env, jclass, jlong nativeObject, jfloatArray normals, jlong stride) {
    jfloat* normals_ = env->GetFloatArrayElements(normals, nullptr);
    jlong result = (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->normals(reinterpret_cast<const filament::math::details::TVec3<float>*>(normals_), stride);
    env->ReleaseFloatArrayElements(normals, normals_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nTangents(JNIEnv* env, jclass, jlong nativeObject, jfloatArray tangents, jlong stride) {
    jfloat* tangents_ = env->GetFloatArrayElements(tangents, nullptr);
    jlong result = (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->tangents(reinterpret_cast<const filament::math::details::TVec4<float>*>(tangents_), stride);
    env->ReleaseFloatArrayElements(tangents, tangents_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nUvs(JNIEnv* env, jclass, jlong nativeObject, jfloatArray uvs, jlong stride) {
    jfloat* uvs_ = env->GetFloatArrayElements(uvs, nullptr);
    jlong result = (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->uvs(reinterpret_cast<const filament::math::details::TVec2<float>*>(uvs_), stride);
    env->ReleaseFloatArrayElements(uvs, uvs_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nPositions(JNIEnv* env, jclass, jlong nativeObject, jfloatArray positions, jlong stride) {
    jfloat* positions_ = env->GetFloatArrayElements(positions, nullptr);
    jlong result = (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->positions(reinterpret_cast<const filament::math::details::TVec3<float>*>(positions_), stride);
    env->ReleaseFloatArrayElements(positions, positions_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nTriangleCount(JNIEnv* env, jclass, jlong nativeObject, jlong triangleCount) {
    return (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->triangleCount(triangleCount);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nTriangles__J_3I(JNIEnv* env, jclass, jlong nativeObject, jintArray triangles) {
    jint* triangles_ = env->GetIntArrayElements(triangles, nullptr);
    jlong result = (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->triangles(reinterpret_cast<const filament::math::details::TVec3<unsigned int>*>(triangles_));
    env->ReleaseIntArrayElements(triangles, triangles_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nTriangles__J_3S(JNIEnv* env, jclass, jlong nativeObject, jshortArray triangles) {
    jshort* triangles_ = env->GetShortArrayElements(triangles, nullptr);
    jlong result = (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->triangles(reinterpret_cast<const filament::math::details::TVec3<unsigned short>*>(triangles_));
    env->ReleaseShortArrayElements(triangles, triangles_, JNI_ABORT);
    return result;
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nAlgorithm(JNIEnv* env, jclass, jlong nativeObject, jint algorithm) {
    return (jlong) &((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->algorithm((filament::geometry::TangentSpaceMesh::Algorithm) algorithm);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_utils_TangentSpaceMesh_1generated_00024Builder_nBuild(JNIEnv* env, jclass, jlong nativeObject) {
    return (jlong) ((filament::geometry::TangentSpaceMesh::Builder*) nativeObject)->build();
}


// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - TangentSpaceMesh::getQuats(filament::math::quath *, size_t) const: parameter "out": quaternion array with no element type
//   - Builder::aux(AuxAttribute, InData, size_t): parameter "data": InData crosses by copy, and Java has no value type
