# This file has been generated by beamsplitter

set(GENERATED_JNI_SRC
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/AgxToneMapperSettings_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/AutomationEngine_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/AutomationSpec_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/Bookmark_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/ColorGradingSettings_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/GenericToneMapperSettings_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/IBLPrefilterContext_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/JsonSerializer_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/Ktx1Bundle_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/Ktx2Reader_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/LinearImage_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/Manipulator_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/MeshReader_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/SingleSample_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/SurfaceOrientation_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/TangentSpaceMesh_generated.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/src/main/cpp/Transcoder_generated.cpp
)
