// This file has been generated by beamsplitter

#include <filamat/MaterialBuilder.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filamat_MaterialBuilder) {

class_<filamat::MaterialBuilder>("filamat$MaterialBuilder")
    .constructor<>()
    .function("noSamplerValidation", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enabled)) [](filamat::MaterialBuilder* self, bool enabled) -> filamat::MaterialBuilder* {
        return &self->noSamplerValidation(enabled);
    }, allow_raw_pointers())
    .function("includeEssl1", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enabled)) [](filamat::MaterialBuilder* self, bool enabled) -> filamat::MaterialBuilder* {
        return &self->includeEssl1(enabled);
    }, allow_raw_pointers())
    .function("name", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string name)) [](filamat::MaterialBuilder* self, std::string name) -> filamat::MaterialBuilder* {
        return &self->name(name.c_str());
    }, allow_raw_pointers())
    .function("compilationParameters", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string params)) [](filamat::MaterialBuilder* self, std::string params) -> filamat::MaterialBuilder* {
        return &self->compilationParameters(params.c_str());
    }, allow_raw_pointers())
    .function("shading", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::Shading shading)) [](filamat::MaterialBuilder* self, filament::Shading shading) -> filamat::MaterialBuilder* {
        return &self->shading(shading);
    }, allow_raw_pointers())
    .function("interpolation", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::Interpolation interpolation)) [](filamat::MaterialBuilder* self, filament::Interpolation interpolation) -> filamat::MaterialBuilder* {
        return &self->interpolation(interpolation);
    }, allow_raw_pointers())
    .function("parameter", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string name, filament::backend::UniformType type, filament::backend::Precision precision)) [](filamat::MaterialBuilder* self, std::string name, filament::backend::UniformType type, filament::backend::Precision precision) -> filamat::MaterialBuilder* {
        return &self->parameter(name.c_str(), type, precision);
    }, allow_raw_pointers())
    .function("parameter", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string name, size_t size, filament::backend::UniformType type, filament::backend::Precision precision)) [](filamat::MaterialBuilder* self, std::string name, size_t size, filament::backend::UniformType type, filament::backend::Precision precision) -> filamat::MaterialBuilder* {
        return &self->parameter(name.c_str(), size, type, precision);
    }, allow_raw_pointers())
    .function("variable", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filamat::MaterialBuilder::Variable v, std::string name)) [](filamat::MaterialBuilder* self, filamat::MaterialBuilder::Variable v, std::string name) -> filamat::MaterialBuilder* {
        return &self->variable(v, name.c_str());
    }, allow_raw_pointers())
    .function("variable", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filamat::MaterialBuilder::Variable v, std::string name, filament::backend::Precision precision)) [](filamat::MaterialBuilder* self, filamat::MaterialBuilder::Variable v, std::string name, filament::backend::Precision precision) -> filamat::MaterialBuilder* {
        return &self->variable(v, name.c_str(), precision);
    }, allow_raw_pointers())
    .function("require", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::VertexAttribute attribute)) [](filamat::MaterialBuilder* self, filament::VertexAttribute attribute) -> filamat::MaterialBuilder* {
        return &self->require(attribute);
    }, allow_raw_pointers())
    .function("materialDomain", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::MaterialDomain materialDomain)) [](filamat::MaterialBuilder* self, filament::MaterialDomain materialDomain) -> filamat::MaterialBuilder* {
        return &self->materialDomain(materialDomain);
    }, allow_raw_pointers())
    .function("material", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string code, size_t line)) [](filamat::MaterialBuilder* self, std::string code, size_t line) -> filamat::MaterialBuilder* {
        return &self->material(code.c_str(), line);
    }, allow_raw_pointers())
    .function("materialVertex", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string code, size_t line)) [](filamat::MaterialBuilder* self, std::string code, size_t line) -> filamat::MaterialBuilder* {
        return &self->materialVertex(code.c_str(), line);
    }, allow_raw_pointers())
    .function("quality", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::ShaderQuality quality)) [](filamat::MaterialBuilder* self, filament::ShaderQuality quality) -> filamat::MaterialBuilder* {
        return &self->quality(quality);
    }, allow_raw_pointers())
    .function("featureLevel", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::FeatureLevel featureLevel)) [](filamat::MaterialBuilder* self, filament::backend::FeatureLevel featureLevel) -> filamat::MaterialBuilder* {
        return &self->featureLevel(featureLevel);
    }, allow_raw_pointers())
    .function("blending", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::BlendingMode blending)) [](filamat::MaterialBuilder* self, filament::BlendingMode blending) -> filamat::MaterialBuilder* {
        return &self->blending(blending);
    }, allow_raw_pointers())
    .function("customBlendFunctions", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::BlendFunction srcRGB, filament::backend::BlendFunction srcA, filament::backend::BlendFunction dstRGB, filament::backend::BlendFunction dstA)) [](filamat::MaterialBuilder* self, filament::backend::BlendFunction srcRGB, filament::backend::BlendFunction srcA, filament::backend::BlendFunction dstRGB, filament::backend::BlendFunction dstA) -> filamat::MaterialBuilder* {
        return &self->customBlendFunctions(srcRGB, srcA, dstRGB, dstA);
    }, allow_raw_pointers())
    .function("postLightingBlending", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::BlendingMode blending)) [](filamat::MaterialBuilder* self, filament::BlendingMode blending) -> filamat::MaterialBuilder* {
        return &self->postLightingBlending(blending);
    }, allow_raw_pointers())
    .function("vertexDomain", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::VertexDomain domain)) [](filamat::MaterialBuilder* self, filament::VertexDomain domain) -> filamat::MaterialBuilder* {
        return &self->vertexDomain(domain);
    }, allow_raw_pointers())
    .function("culling", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::CullingMode culling)) [](filamat::MaterialBuilder* self, filament::backend::CullingMode culling) -> filamat::MaterialBuilder* {
        return &self->culling(culling);
    }, allow_raw_pointers())
    .function("colorWrite", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enable)) [](filamat::MaterialBuilder* self, bool enable) -> filamat::MaterialBuilder* {
        return &self->colorWrite(enable);
    }, allow_raw_pointers())
    .function("depthWrite", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enable)) [](filamat::MaterialBuilder* self, bool enable) -> filamat::MaterialBuilder* {
        return &self->depthWrite(enable);
    }, allow_raw_pointers())
    .function("depthCulling", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enable)) [](filamat::MaterialBuilder* self, bool enable) -> filamat::MaterialBuilder* {
        return &self->depthCulling(enable);
    }, allow_raw_pointers())
    .function("instanced", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enable)) [](filamat::MaterialBuilder* self, bool enable) -> filamat::MaterialBuilder* {
        return &self->instanced(enable);
    }, allow_raw_pointers())
    .function("doubleSided", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool doubleSided)) [](filamat::MaterialBuilder* self, bool doubleSided) -> filamat::MaterialBuilder* {
        return &self->doubleSided(doubleSided);
    }, allow_raw_pointers())
    .function("maskThreshold", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, float threshold)) [](filamat::MaterialBuilder* self, float threshold) -> filamat::MaterialBuilder* {
        return &self->maskThreshold(threshold);
    }, allow_raw_pointers())
    .function("alphaToCoverage", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enable)) [](filamat::MaterialBuilder* self, bool enable) -> filamat::MaterialBuilder* {
        return &self->alphaToCoverage(enable);
    }, allow_raw_pointers())
    .function("shadowMultiplier", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool shadowMultiplier)) [](filamat::MaterialBuilder* self, bool shadowMultiplier) -> filamat::MaterialBuilder* {
        return &self->shadowMultiplier(shadowMultiplier);
    }, allow_raw_pointers())
    .function("transparentShadow", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool transparentShadow)) [](filamat::MaterialBuilder* self, bool transparentShadow) -> filamat::MaterialBuilder* {
        return &self->transparentShadow(transparentShadow);
    }, allow_raw_pointers())
    .function("coloredPenumbra", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool coloredPenumbra)) [](filamat::MaterialBuilder* self, bool coloredPenumbra) -> filamat::MaterialBuilder* {
        return &self->coloredPenumbra(coloredPenumbra);
    }, allow_raw_pointers())
    .function("specularAntiAliasing", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool specularAntiAliasing)) [](filamat::MaterialBuilder* self, bool specularAntiAliasing) -> filamat::MaterialBuilder* {
        return &self->specularAntiAliasing(specularAntiAliasing);
    }, allow_raw_pointers())
    .function("specularAntiAliasingVariance", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, float screenSpaceVariance)) [](filamat::MaterialBuilder* self, float screenSpaceVariance) -> filamat::MaterialBuilder* {
        return &self->specularAntiAliasingVariance(screenSpaceVariance);
    }, allow_raw_pointers())
    .function("specularAntiAliasingThreshold", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, float threshold)) [](filamat::MaterialBuilder* self, float threshold) -> filamat::MaterialBuilder* {
        return &self->specularAntiAliasingThreshold(threshold);
    }, allow_raw_pointers())
    .function("clearCoatIorChange", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool clearCoatIorChange)) [](filamat::MaterialBuilder* self, bool clearCoatIorChange) -> filamat::MaterialBuilder* {
        return &self->clearCoatIorChange(clearCoatIorChange);
    }, allow_raw_pointers())
    .function("flipUV", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool flipUV)) [](filamat::MaterialBuilder* self, bool flipUV) -> filamat::MaterialBuilder* {
        return &self->flipUV(flipUV);
    }, allow_raw_pointers())
    .function("linearFog", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enabled)) [](filamat::MaterialBuilder* self, bool enabled) -> filamat::MaterialBuilder* {
        return &self->linearFog(enabled);
    }, allow_raw_pointers())
    .function("shadowFarAttenuation", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enabled)) [](filamat::MaterialBuilder* self, bool enabled) -> filamat::MaterialBuilder* {
        return &self->shadowFarAttenuation(enabled);
    }, allow_raw_pointers())
    .function("multiBounceAmbientOcclusion", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool multiBounceAO)) [](filamat::MaterialBuilder* self, bool multiBounceAO) -> filamat::MaterialBuilder* {
        return &self->multiBounceAmbientOcclusion(multiBounceAO);
    }, allow_raw_pointers())
    .function("specularAmbientOcclusion", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::SpecularAmbientOcclusion specularAO)) [](filamat::MaterialBuilder* self, filament::SpecularAmbientOcclusion specularAO) -> filamat::MaterialBuilder* {
        return &self->specularAmbientOcclusion(specularAO);
    }, allow_raw_pointers())
    .function("refractionMode", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::RefractionMode refraction)) [](filamat::MaterialBuilder* self, filament::RefractionMode refraction) -> filamat::MaterialBuilder* {
        return &self->refractionMode(refraction);
    }, allow_raw_pointers())
    .function("refractionType", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::RefractionType refractionType)) [](filamat::MaterialBuilder* self, filament::RefractionType refractionType) -> filamat::MaterialBuilder* {
        return &self->refractionType(refractionType);
    }, allow_raw_pointers())
    .function("reflectionMode", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::ReflectionMode mode)) [](filamat::MaterialBuilder* self, filament::ReflectionMode mode) -> filamat::MaterialBuilder* {
        return &self->reflectionMode(mode);
    }, allow_raw_pointers())
    .function("transparencyMode", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::TransparencyMode mode)) [](filamat::MaterialBuilder* self, filament::TransparencyMode mode) -> filamat::MaterialBuilder* {
        return &self->transparencyMode(mode);
    }, allow_raw_pointers())
    .function("stereoscopicEyeCount", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, uint8_t eyeCount)) [](filamat::MaterialBuilder* self, uint8_t eyeCount) -> filamat::MaterialBuilder* {
        return &self->stereoscopicEyeCount(eyeCount);
    }, allow_raw_pointers())
    .function("customSurfaceShading", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool customSurfaceShading)) [](filamat::MaterialBuilder* self, bool customSurfaceShading) -> filamat::MaterialBuilder* {
        return &self->customSurfaceShading(customSurfaceShading);
    }, allow_raw_pointers())
    .function("platform", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filamat::MaterialBuilderBase::Platform platform)) [](filamat::MaterialBuilder* self, filamat::MaterialBuilderBase::Platform platform) -> filamat::MaterialBuilder* {
        return &self->platform(platform);
    }, allow_raw_pointers())
    .function("targetApi", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filamat::MaterialBuilderBase::TargetApi targetApi)) [](filamat::MaterialBuilder* self, filamat::MaterialBuilderBase::TargetApi targetApi) -> filamat::MaterialBuilder* {
        return &self->targetApi(targetApi);
    }, allow_raw_pointers())
    .function("optimization", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filamat::MaterialBuilderBase::Optimization optimization)) [](filamat::MaterialBuilder* self, filamat::MaterialBuilderBase::Optimization optimization) -> filamat::MaterialBuilder* {
        return &self->optimization(optimization);
    }, allow_raw_pointers())
    .function("printShaders", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool printShaders)) [](filamat::MaterialBuilder* self, bool printShaders) -> filamat::MaterialBuilder* {
        return &self->printShaders(printShaders);
    }, allow_raw_pointers())
    .function("saveRawVariants", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool saveRawVariants)) [](filamat::MaterialBuilder* self, bool saveRawVariants) -> filamat::MaterialBuilder* {
        return &self->saveRawVariants(saveRawVariants);
    }, allow_raw_pointers())
    .function("generateDebugInfo", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool generateDebugInfo)) [](filamat::MaterialBuilder* self, bool generateDebugInfo) -> filamat::MaterialBuilder* {
        return &self->generateDebugInfo(generateDebugInfo);
    }, allow_raw_pointers())
    .function("variantFilter", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, unsigned int variantFilter)) [](filamat::MaterialBuilder* self, unsigned int variantFilter) -> filamat::MaterialBuilder* {
        return &self->variantFilter(variantFilter);
    }, allow_raw_pointers())
    .function("shaderDefine", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string name, std::string value)) [](filamat::MaterialBuilder* self, std::string name, std::string value) -> filamat::MaterialBuilder* {
        return &self->shaderDefine(name.c_str(), value.c_str());
    }, allow_raw_pointers())
    .function("output", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filamat::MaterialBuilder::VariableQualifier qualifier, filamat::MaterialBuilder::OutputTarget target, filament::backend::Precision precision, filamat::MaterialBuilder::OutputType type, std::string name, int location)) [](filamat::MaterialBuilder* self, filamat::MaterialBuilder::VariableQualifier qualifier, filamat::MaterialBuilder::OutputTarget target, filament::backend::Precision precision, filamat::MaterialBuilder::OutputType type, std::string name, int location) -> filamat::MaterialBuilder* {
        return &self->output(qualifier, target, precision, type, name.c_str(), location);
    }, allow_raw_pointers())
    .function("enableFramebufferFetch", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self)) [](filamat::MaterialBuilder* self) -> filamat::MaterialBuilder* {
        return &self->enableFramebufferFetch();
    }, allow_raw_pointers())
    .function("vertexDomainDeviceJittered", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, bool enabled)) [](filamat::MaterialBuilder* self, bool enabled) -> filamat::MaterialBuilder* {
        return &self->vertexDomainDeviceJittered(enabled);
    }, allow_raw_pointers())
    .function("useLegacyMorphing", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self)) [](filamat::MaterialBuilder* self) -> filamat::MaterialBuilder* {
        return &self->useLegacyMorphing();
    }, allow_raw_pointers())
    .function("groupSize", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::math::details::TVec3<unsigned int> groupSize)) [](filamat::MaterialBuilder* self, filament::math::details::TVec3<unsigned int> groupSize) -> filamat::MaterialBuilder* {
        return &self->groupSize(groupSize);
    }, allow_raw_pointers())
    .function("useDefaultDepthVariant", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self)) [](filamat::MaterialBuilder* self) -> filamat::MaterialBuilder* {
        return &self->useDefaultDepthVariant();
    }, allow_raw_pointers())
    .function("materialSource", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, std::string source)) [](filamat::MaterialBuilder* self, std::string source) -> filamat::MaterialBuilder* {
        return &self->materialSource(source.c_str());
    }, allow_raw_pointers())
    .function("setApiLevel", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, uint32_t apiLevel)) [](filamat::MaterialBuilder* self, uint32_t apiLevel) -> filamat::MaterialBuilder* {
        return &self->setApiLevel(apiLevel);
    }, allow_raw_pointers())
    .function("subpass", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, filament::backend::SamplerFormat format, filament::backend::Precision precision, std::string name)) [](filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, filament::backend::SamplerFormat format, filament::backend::Precision precision, std::string name) -> filamat::MaterialBuilder* {
        return &self->subpass(subpassType, format, precision, name.c_str());
    }, allow_raw_pointers())
    .function("subpassString", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, filament::backend::SamplerFormat format, std::string name)) [](filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, filament::backend::SamplerFormat format, std::string name) -> filamat::MaterialBuilder* {
        return &self->subpass(subpassType, format, name.c_str());
    }, allow_raw_pointers())
    .function("subpassPrecision", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, filament::backend::Precision precision, std::string name)) [](filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, filament::backend::Precision precision, std::string name) -> filamat::MaterialBuilder* {
        return &self->subpass(subpassType, precision, name.c_str());
    }, allow_raw_pointers())
    .function("subpass", (filamat::MaterialBuilder* (*) (filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, std::string name)) [](filamat::MaterialBuilder* self, filament::backend::SubpassType subpassType, std::string name) -> filamat::MaterialBuilder* {
        return &self->subpass(subpassType, name.c_str());
    }, allow_raw_pointers())
    .function("hasSamplerType", &filamat::MaterialBuilder::hasSamplerType)
    .function("getParameterCount", &filamat::MaterialBuilder::getParameterCount)
    .function("getSubpassCount", &filamat::MaterialBuilder::getSubpassCount)
    .function("getVariantFilter", &filamat::MaterialBuilder::getVariantFilter)
    .function("getFeatureLevel", &filamat::MaterialBuilder::getFeatureLevel)
    .function("getApiLevel", &filamat::MaterialBuilder::getApiLevel)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - MaterialBuilder::MaterialBuilder(const MaterialBuilder &): explicitly deleted
//   - MaterialBuilder::parameter(const char *, SamplerType, SamplerFormat, ParameterPrecision, bool, bool, const char *, std::optional<ShaderStageFlags>): parameter "stages" has unresolved type std::optional<ShaderStageFlags>
//   - MaterialBuilder::buffer(filament::BufferInterfaceBlock): parameter "bib" has unresolved type filament::BufferInterfaceBlock
//   - MaterialBuilder::stereoscopicType(StereoscopicType): parameter "stereoscopicType" is filament::backend::Platform::StereoscopicType, which is not bound
//   - MaterialBuilder::workarounds(Workarounds): parameter "workarounds" is filamat::MaterialBuilderBase::Workarounds, which is not bound
//   - MaterialBuilder::build(utils::JobSystem &): parameter "jobSystem" has unresolved type utils::JobSystem &
//   - MaterialBuilder::peek(filament::backend::ShaderStage, const CodeGenParams &, const PropertyList &): parameter "properties" has unresolved type const PropertyList &
//   - MaterialBuilder::getParameters() const: return type is std::vector<filamat::MaterialBuilder::Parameter>, which is not bound
//   - MaterialBuilder::getSubPasses() const: returns unresolved type const SubpassList &
//   - MaterialBuilder::getAttributeDatabase(): return type is std::array<filamat::MaterialBuilder::Attribute, 16>, which is not bound


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
