// This file has been generated by beamsplitter

#include <filamat/Package.h>
#include "../jsbindings_helpers.h"

#include <emscripten.h>
#include <emscripten/bind.h>

#include <string>
#include <vector>

using namespace emscripten;
using namespace filament;

EMSCRIPTEN_BINDINGS(filamat_Package) {

class_<filamat::Package>("filamat$Package")
    .constructor<>()
    .constructor<size_t>()
    .function("getSize", &filamat::Package::getSize)
    .function("setValid", &filamat::Package::setValid)
    .function("isValid", &filamat::Package::isValid)
    ;

// =============================================================================
// HANDWRITTEN SECTION
// =============================================================================
// The following could not be generated and need to be written by hand.
// Anything added below this comment block is preserved when regenerating.
//   - Package::Package(const void *, size_t): parameter "src": const void * is opaque, so there is nothing to marshal
//   - Package::Package(const Package &): explicitly deleted
//   - Package::getData() const: returns uint8_t *, an array with no length
//   - Package::getEnd() const: returns uint8_t *, an array with no length
//   - Package::invalidPackage(): returns filamat::Package by value, which cannot be copied


// The following C++ methods were not auto-generated and can be implemented here:

} // EMSCRIPTEN_BINDINGS
