// This file has been generated by beamsplitter
package com.google.android.filament.filamat;

public class Attribute_generated {
    public static final byte FLAG_NORMALIZED = (byte) 1;
    public static final byte FLAG_INTEGER_TARGET = (byte) 2;
    public static final byte BUFFER_UNUSED = (byte) -1;
    public int offset = 0;
    public byte stride = (byte) 0;
    public byte buffer;
    public int type = 0;
    public byte flags = (byte) 0;
}
