// This file has been generated by beamsplitter
package com.google.android.filament.filamat;

public class MaterialBuilder_generated {
    private final long mNativeObject;

    public MaterialBuilder_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static MaterialBuilder_generated create() {
        return new MaterialBuilder_generated(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long noSamplerValidation(boolean enabled) {
        return nNoSamplerValidation(mNativeObject, enabled);
    }
    private static native long nNoSamplerValidation(long nativeObject, boolean enabled);

    public long includeEssl1(boolean enabled) {
        return nIncludeEssl1(mNativeObject, enabled);
    }
    private static native long nIncludeEssl1(long nativeObject, boolean enabled);

    public long name(String name) {
        return nName(mNativeObject, name);
    }
    private static native long nName(long nativeObject, String name);

    public long compilationParameters(String params) {
        return nCompilationParameters(mNativeObject, params);
    }
    private static native long nCompilationParameters(long nativeObject, String params);

    public long shading(int shading) {
        return nShading(mNativeObject, shading);
    }
    private static native long nShading(long nativeObject, int shading);

    public long interpolation(int interpolation) {
        return nInterpolation(mNativeObject, interpolation);
    }
    private static native long nInterpolation(long nativeObject, int interpolation);

    public long parameter(String name, int type, int precision) {
        return nParameter(mNativeObject, name, type, precision);
    }
    private static native long nParameter(long nativeObject, String name, int type, int precision);

    public long parameter(String name, long size, int type, int precision) {
        return nParameter(mNativeObject, name, size, type, precision);
    }
    private static native long nParameter(long nativeObject, String name, long size, int type, int precision);

    public long variable(int v, String name) {
        return nVariable(mNativeObject, v, name);
    }
    private static native long nVariable(long nativeObject, int v, String name);

    public long variable(int v, String name, int precision) {
        return nVariable(mNativeObject, v, name, precision);
    }
    private static native long nVariable(long nativeObject, int v, String name, int precision);

    public long require(int attribute) {
        return nRequire(mNativeObject, attribute);
    }
    private static native long nRequire(long nativeObject, int attribute);

    public long materialDomain(int materialDomain) {
        return nMaterialDomain(mNativeObject, materialDomain);
    }
    private static native long nMaterialDomain(long nativeObject, int materialDomain);

    public long material(String code, long line) {
        return nMaterial(mNativeObject, code, line);
    }
    private static native long nMaterial(long nativeObject, String code, long line);

    public long materialVertex(String code, long line) {
        return nMaterialVertex(mNativeObject, code, line);
    }
    private static native long nMaterialVertex(long nativeObject, String code, long line);

    public long quality(int quality) {
        return nQuality(mNativeObject, quality);
    }
    private static native long nQuality(long nativeObject, int quality);

    public long featureLevel(int featureLevel) {
        return nFeatureLevel(mNativeObject, featureLevel);
    }
    private static native long nFeatureLevel(long nativeObject, int featureLevel);

    public long blending(int blending) {
        return nBlending(mNativeObject, blending);
    }
    private static native long nBlending(long nativeObject, int blending);

    public long customBlendFunctions(int srcRGB, int srcA, int dstRGB, int dstA) {
        return nCustomBlendFunctions(mNativeObject, srcRGB, srcA, dstRGB, dstA);
    }
    private static native long nCustomBlendFunctions(long nativeObject, int srcRGB, int srcA, int dstRGB, int dstA);

    public long postLightingBlending(int blending) {
        return nPostLightingBlending(mNativeObject, blending);
    }
    private static native long nPostLightingBlending(long nativeObject, int blending);

    public long vertexDomain(int domain) {
        return nVertexDomain(mNativeObject, domain);
    }
    private static native long nVertexDomain(long nativeObject, int domain);

    public long culling(int culling) {
        return nCulling(mNativeObject, culling);
    }
    private static native long nCulling(long nativeObject, int culling);

    public long colorWrite(boolean enable) {
        return nColorWrite(mNativeObject, enable);
    }
    private static native long nColorWrite(long nativeObject, boolean enable);

    public long depthWrite(boolean enable) {
        return nDepthWrite(mNativeObject, enable);
    }
    private static native long nDepthWrite(long nativeObject, boolean enable);

    public long depthCulling(boolean enable) {
        return nDepthCulling(mNativeObject, enable);
    }
    private static native long nDepthCulling(long nativeObject, boolean enable);

    public long instanced(boolean enable) {
        return nInstanced(mNativeObject, enable);
    }
    private static native long nInstanced(long nativeObject, boolean enable);

    public long doubleSided(boolean doubleSided) {
        return nDoubleSided(mNativeObject, doubleSided);
    }
    private static native long nDoubleSided(long nativeObject, boolean doubleSided);

    public long maskThreshold(float threshold) {
        return nMaskThreshold(mNativeObject, threshold);
    }
    private static native long nMaskThreshold(long nativeObject, float threshold);

    public long alphaToCoverage(boolean enable) {
        return nAlphaToCoverage(mNativeObject, enable);
    }
    private static native long nAlphaToCoverage(long nativeObject, boolean enable);

    public long shadowMultiplier(boolean shadowMultiplier) {
        return nShadowMultiplier(mNativeObject, shadowMultiplier);
    }
    private static native long nShadowMultiplier(long nativeObject, boolean shadowMultiplier);

    public long transparentShadow(boolean transparentShadow) {
        return nTransparentShadow(mNativeObject, transparentShadow);
    }
    private static native long nTransparentShadow(long nativeObject, boolean transparentShadow);

    public long coloredPenumbra(boolean coloredPenumbra) {
        return nColoredPenumbra(mNativeObject, coloredPenumbra);
    }
    private static native long nColoredPenumbra(long nativeObject, boolean coloredPenumbra);

    public long specularAntiAliasing(boolean specularAntiAliasing) {
        return nSpecularAntiAliasing(mNativeObject, specularAntiAliasing);
    }
    private static native long nSpecularAntiAliasing(long nativeObject, boolean specularAntiAliasing);

    public long specularAntiAliasingVariance(float screenSpaceVariance) {
        return nSpecularAntiAliasingVariance(mNativeObject, screenSpaceVariance);
    }
    private static native long nSpecularAntiAliasingVariance(long nativeObject, float screenSpaceVariance);

    public long specularAntiAliasingThreshold(float threshold) {
        return nSpecularAntiAliasingThreshold(mNativeObject, threshold);
    }
    private static native long nSpecularAntiAliasingThreshold(long nativeObject, float threshold);

    public long clearCoatIorChange(boolean clearCoatIorChange) {
        return nClearCoatIorChange(mNativeObject, clearCoatIorChange);
    }
    private static native long nClearCoatIorChange(long nativeObject, boolean clearCoatIorChange);

    public long flipUV(boolean flipUV) {
        return nFlipUV(mNativeObject, flipUV);
    }
    private static native long nFlipUV(long nativeObject, boolean flipUV);

    public long linearFog(boolean enabled) {
        return nLinearFog(mNativeObject, enabled);
    }
    private static native long nLinearFog(long nativeObject, boolean enabled);

    public long shadowFarAttenuation(boolean enabled) {
        return nShadowFarAttenuation(mNativeObject, enabled);
    }
    private static native long nShadowFarAttenuation(long nativeObject, boolean enabled);

    public long multiBounceAmbientOcclusion(boolean multiBounceAO) {
        return nMultiBounceAmbientOcclusion(mNativeObject, multiBounceAO);
    }
    private static native long nMultiBounceAmbientOcclusion(long nativeObject, boolean multiBounceAO);

    public long specularAmbientOcclusion(int specularAO) {
        return nSpecularAmbientOcclusion(mNativeObject, specularAO);
    }
    private static native long nSpecularAmbientOcclusion(long nativeObject, int specularAO);

    public long refractionMode(int refraction) {
        return nRefractionMode(mNativeObject, refraction);
    }
    private static native long nRefractionMode(long nativeObject, int refraction);

    public long refractionType(int refractionType) {
        return nRefractionType(mNativeObject, refractionType);
    }
    private static native long nRefractionType(long nativeObject, int refractionType);

    public long reflectionMode(int mode) {
        return nReflectionMode(mNativeObject, mode);
    }
    private static native long nReflectionMode(long nativeObject, int mode);

    public long transparencyMode(int mode) {
        return nTransparencyMode(mNativeObject, mode);
    }
    private static native long nTransparencyMode(long nativeObject, int mode);

    public long stereoscopicEyeCount(byte eyeCount) {
        return nStereoscopicEyeCount(mNativeObject, eyeCount);
    }
    private static native long nStereoscopicEyeCount(long nativeObject, byte eyeCount);

    public long customSurfaceShading(boolean customSurfaceShading) {
        return nCustomSurfaceShading(mNativeObject, customSurfaceShading);
    }
    private static native long nCustomSurfaceShading(long nativeObject, boolean customSurfaceShading);

    public long platform(int platform) {
        return nPlatform(mNativeObject, platform);
    }
    private static native long nPlatform(long nativeObject, int platform);

    public long targetApi(int targetApi) {
        return nTargetApi(mNativeObject, targetApi);
    }
    private static native long nTargetApi(long nativeObject, int targetApi);

    public long optimization(int optimization) {
        return nOptimization(mNativeObject, optimization);
    }
    private static native long nOptimization(long nativeObject, int optimization);

    public long printShaders(boolean printShaders) {
        return nPrintShaders(mNativeObject, printShaders);
    }
    private static native long nPrintShaders(long nativeObject, boolean printShaders);

    public long saveRawVariants(boolean saveRawVariants) {
        return nSaveRawVariants(mNativeObject, saveRawVariants);
    }
    private static native long nSaveRawVariants(long nativeObject, boolean saveRawVariants);

    public long generateDebugInfo(boolean generateDebugInfo) {
        return nGenerateDebugInfo(mNativeObject, generateDebugInfo);
    }
    private static native long nGenerateDebugInfo(long nativeObject, boolean generateDebugInfo);

    public long variantFilter(int variantFilter) {
        return nVariantFilter(mNativeObject, variantFilter);
    }
    private static native long nVariantFilter(long nativeObject, int variantFilter);

    public long shaderDefine(String name, String value) {
        return nShaderDefine(mNativeObject, name, value);
    }
    private static native long nShaderDefine(long nativeObject, String name, String value);

    public long output(int qualifier, int target, int precision, int type, String name, int location) {
        return nOutput(mNativeObject, qualifier, target, precision, type, name, location);
    }
    private static native long nOutput(long nativeObject, int qualifier, int target, int precision, int type, String name, int location);

    public long enableFramebufferFetch() {
        return nEnableFramebufferFetch(mNativeObject);
    }
    private static native long nEnableFramebufferFetch(long nativeObject);

    public long vertexDomainDeviceJittered(boolean enabled) {
        return nVertexDomainDeviceJittered(mNativeObject, enabled);
    }
    private static native long nVertexDomainDeviceJittered(long nativeObject, boolean enabled);

    public long useLegacyMorphing() {
        return nUseLegacyMorphing(mNativeObject);
    }
    private static native long nUseLegacyMorphing(long nativeObject);

    public long groupSize(int[] groupSize) {
        return nGroupSize(mNativeObject, groupSize);
    }
    private static native long nGroupSize(long nativeObject, int[] groupSize);

    public long useDefaultDepthVariant() {
        return nUseDefaultDepthVariant(mNativeObject);
    }
    private static native long nUseDefaultDepthVariant(long nativeObject);

    public long materialSource(String source) {
        return nMaterialSource(mNativeObject, source);
    }
    private static native long nMaterialSource(long nativeObject, String source);

    public long setApiLevel(int apiLevel) {
        return nSetApiLevel(mNativeObject, apiLevel);
    }
    private static native long nSetApiLevel(long nativeObject, int apiLevel);

    public long subpass(int subpassType, int format, int precision, String name) {
        return nSubpass(mNativeObject, subpassType, format, precision, name);
    }
    private static native long nSubpass(long nativeObject, int subpassType, int format, int precision, String name);

    public long subpassString(int subpassType, int format, String name) {
        return nSubpassString(mNativeObject, subpassType, format, name);
    }
    private static native long nSubpassString(long nativeObject, int subpassType, int format, String name);

    public long subpassPrecision(int subpassType, int precision, String name) {
        return nSubpassPrecision(mNativeObject, subpassType, precision, name);
    }
    private static native long nSubpassPrecision(long nativeObject, int subpassType, int precision, String name);

    public long subpass(int subpassType, String name) {
        return nSubpass(mNativeObject, subpassType, name);
    }
    private static native long nSubpass(long nativeObject, int subpassType, String name);

    public boolean hasSamplerType(int samplerType) {
        return nHasSamplerType(mNativeObject, samplerType);
    }
    private static native boolean nHasSamplerType(long nativeObject, int samplerType);

    public long getParameterCount() {
        return nGetParameterCount(mNativeObject);
    }
    private static native long nGetParameterCount(long nativeObject);

    public byte getSubpassCount() {
        return nGetSubpassCount(mNativeObject);
    }
    private static native byte nGetSubpassCount(long nativeObject);

    public int getVariantFilter() {
        return nGetVariantFilter(mNativeObject);
    }
    private static native int nGetVariantFilter(long nativeObject);

    public int getFeatureLevel() {
        return nGetFeatureLevel(mNativeObject);
    }
    private static native int nGetFeatureLevel(long nativeObject);

    public int getApiLevel() {
        return nGetApiLevel(mNativeObject);
    }
    private static native int nGetApiLevel(long nativeObject);

public static class Parameter {
    private final long mNativeObject;

    public Parameter(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static MaterialBuilder_generated.Parameter create() {
        return new MaterialBuilder_generated.Parameter(nCreate());
    }
    private static native long nCreate();

    public static MaterialBuilder_generated.Parameter create(String paramName, int t, long typeSize, int p) {
        return new MaterialBuilder_generated.Parameter(nCreate(paramName, t, typeSize, p));
    }
    private static native long nCreate(String paramName, int t, long typeSize, int p);

    public static MaterialBuilder_generated.Parameter create(String paramName, int t, int f, int p) {
        return new MaterialBuilder_generated.Parameter(nCreate(paramName, t, f, p));
    }
    private static native long nCreate(String paramName, int t, int f, int p);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public boolean isSampler() {
        return nIsSampler(mNativeObject);
    }
    private static native boolean nIsSampler(long nativeObject);

    public boolean isUniform() {
        return nIsUniform(mNativeObject);
    }
    private static native boolean nIsUniform(long nativeObject);

    public boolean isSubpass() {
        return nIsSubpass(mNativeObject);
    }
    private static native boolean nIsSubpass(long nativeObject);
}


public static class Output {
    private final long mNativeObject;

    public Output(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static MaterialBuilder_generated.Output create() {
        return new MaterialBuilder_generated.Output(nCreate());
    }
    private static native long nCreate();

    public static MaterialBuilder_generated.Output create(String outputName, int qualifier, int target, int precision, int type, int location) {
        return new MaterialBuilder_generated.Output(nCreate(outputName, qualifier, target, precision, type, location));
    }
    private static native long nCreate(String outputName, int qualifier, int target, int precision, int type, int location);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);
}


public static class Constant {
    private final long mNativeObject;

    public Constant(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}


public static class PushConstant {
    private final long mNativeObject;

    public PushConstant(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}


public static class CustomVariable {
    private final long mNativeObject;

    public CustomVariable(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}


public static class Attribute {
    private final long mNativeObject;

    public Attribute(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public String getAttributeName() {
        return nGetAttributeName(mNativeObject);
    }
    private static native String nGetAttributeName(long nativeObject);

    public String getDefineName() {
        return nGetDefineName(mNativeObject);
    }
    private static native String nGetDefineName(long nativeObject);
}

}
