// This file has been generated by beamsplitter
package com.google.android.filament.filamat;

public class StencilState_generated {
    public StencilState_generated.StencilOperations front = new StencilState_generated.StencilOperations();
    public StencilState_generated.StencilOperations back = new StencilState_generated.StencilOperations();
    public boolean stencilWrite = false;
    public byte padding = (byte) 0;

public static class StencilOperations {
    public byte ref;
    public byte readMask;
    public byte writeMask;
}

}
