/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package js emits emscripten/embind bindings from the IR.
//
// The emitter makes no decisions: what to bind, and why, was settled by the rules
// package. This file only says which declarations go into which file; the C++ text
// lives in templates/, the expressions in bind.go and cpp.go, and the round-trip
// that preserves a developer's own bindings in handwritten.go.
package js

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"beamsplitter2/emit"
	"beamsplitter2/ir"
)

// EmitAll writes each module's bindings into its own directory under outDir and
// reports the files it wrote, keyed by module name.
func EmitAll(names Names, api *ir.API, outDir string, modules []emit.Module) (map[string][]string, error) {
	written := map[string][]string{}
	for _, module := range modules {
		files, err := emitModule(names, api, outDir, module)
		if err != nil {
			return nil, fmt.Errorf("emitting %s: %w", module.Name, err)
		}
		written[module.Name] = files
	}
	return written, nil
}

// WriteSourceList records the generated files for CMake to include, across every
// module of every target. The build needs an explicit list rather than a glob, and
// a list kept by hand silently falls behind whenever a class appears or goes away.
func WriteSourceList(outDir string, written map[string][]string) error {
	var b strings.Builder
	b.WriteString("# This file has been generated by beamsplitter\n")

	for _, module := range sortedKeys(written) {
		variable := moduleSymbol(module) + "_GENERATED_SRC"
		fmt.Fprintf(&b, "\nset(%s\n", strings.ToUpper(variable))
		files := written[module]
		for i, file := range files {
			separator := ""
			if i == len(files)-1 {
				separator = ")"
			}
			fmt.Fprintf(&b, "  %s/%s%s\n", module, file, separator)
		}
	}
	return os.WriteFile(filepath.Join(outDir, "generated_sources.cmake"), []byte(b.String()), 0644)
}

func emitModule(names Names, api *ir.API, outDir string, module emit.Module) ([]string, error) {
	dir := filepath.Join(outDir, module.Name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, err
	}
	s := newScope(names, api, module)

	// The source list must name what was actually written. Globbing the directory
	// instead would sweep up files left behind by an earlier, differently named run.
	var written []string
	write := func(name string, f file) error {
		written = append(written, name)
		return os.WriteFile(filepath.Join(dir, name), []byte(f.render()), 0644)
	}

	for _, c := range s.topLevelClasses() {
		name := c.Name + "_generated.cpp"
		if err := write(name, s.classFile(c, filepath.Join(dir, name))); err != nil {
			return nil, err
		}
	}
	// These aggregate one kind of declaration for the whole module. The "all_"
	// prefix keeps them clear of the per-class files: filamat has a class named
	// Enums, and on a case-insensitive filesystem Enums_generated.cpp and
	// enums_generated.cpp are the same file.
	for name, build := range map[string]func() file{
		"all_enums_generated.cpp":   s.enumsFile,
		"all_structs_generated.cpp": s.structsFile,
		"all_math_generated.cpp":    s.mathFile,
	} {
		if err := write(name, build()); err != nil {
			return nil, err
		}
	}
	sort.Strings(written)
	return written, nil
}

// scope is the slice of the API that one module is responsible for.
type scope struct {
	names   Names
	api     *ir.API
	module  emit.Module
	classes []*ir.Class
	enums   []*ir.Enum
}

func newScope(names Names, api *ir.API, module emit.Module) *scope {
	s := &scope{names: names, api: api, module: module}
	for _, c := range api.Classes {
		if c.Bind && module.Owns(c.Header) {
			s.classes = append(s.classes, c)
		}
	}
	for _, e := range api.Enums {
		if e.Bind && module.Owns(e.Header) {
			s.enums = append(s.enums, e)
		}
	}
	return s
}

// symbol names an EMSCRIPTEN_BINDINGS block, which has to be unique across every
// translation unit linked into the same binary.
func (s *scope) symbol(name string) string {
	return moduleSymbol(s.module.Name) + "_" + name
}

func moduleSymbol(module string) string {
	return strings.NewReplacer("-", "_", ".", "_").Replace(module)
}

// classFile holds one top-level class and the classes nested inside it, so that a
// builder sits beside what it builds.
func (s *scope) classFile(c *ir.Class, path string) file {
	classes := append([]*ir.Class{c}, s.nestedClasses(c)...)
	f := file{Includes: []string{c.Header}, Symbol: s.symbol(c.Name)}

	for _, cls := range classes {
		// embind refuses to bind a class it cannot destroy, and Filament keeps the
		// destructors of engine-owned types to itself, so it has to be told.
		if cls.NoPublicDestructor {
			f.Opaque = append(f.Opaque, cls.Spelling())
		}
		f.Classes = append(f.Classes, s.classRegistrations(cls))
	}
	f.Handwritten = handwritten(classes, path)
	return f
}

func (s *scope) classRegistrations(c *ir.Class) classView {
	view := classView{CppName: c.Spelling(), JsName: s.names.Of(c.CppName)}

	for _, ctor := range c.Constructors {
		if !ctor.Bind {
			continue
		}
		types := make([]string, 0, len(ctor.Params))
		for _, p := range ctor.Params {
			types = append(types, nativeType(p.Type))
		}
		view.Constructors = append(view.Constructors, strings.Join(types, ", "))
	}
	for _, m := range c.Methods {
		if m.Bind {
			view.Registrations = append(view.Registrations, bindMethod(c, m))
		}
	}
	return view
}

func (s *scope) enumsFile() file {
	f := file{Symbol: s.symbol("enums")}
	headers := map[string]bool{}

	for _, e := range sortedByCppName(s.enums, func(e *ir.Enum) string { return e.CppName }) {
		if len(e.Values) == 0 {
			continue
		}
		headers[e.Header] = true
		view := enumView{CppName: e.Spelling(), JsName: s.names.Of(e.CppName)}
		for _, v := range e.Values {
			view.Values = append(view.Values, nameRef{Name: v.Name, CppName: e.Spelling() + "::" + v.Name})
		}
		f.Enums = append(f.Enums, view)
	}
	f.Includes = sortedKeys(headers)
	return f
}

func (s *scope) structsFile() file {
	f := file{Symbol: s.symbol("structs")}
	headers := map[string]bool{}

	for _, c := range sortedByCppName(s.classes, func(c *ir.Class) string { return c.CppName }) {
		if isHandle(c) || len(c.Fields) == 0 {
			continue
		}
		headers[c.Header] = true
		view := structView{CppName: c.Spelling(), JsName: s.names.Of(c.CppName)}
		for _, field := range c.Fields {
			if field.Bind && !field.Static {
				view.Fields = append(view.Fields, nameRef{Name: field.Name, CppName: c.Spelling() + "::" + field.Name})
			}
		}
		f.Structs = append(f.Structs, view)
	}
	f.Includes = sortedKeys(headers)
	return f
}

// mathFile registers Filament's vector types as JavaScript arrays. Every type
// crossing the boundary must be registered or embind throws at call time, and
// value_array matches the .d.ts, where a float3 is a plain number[].
func (s *scope) mathFile() file {
	used := map[string]*ir.Type{}
	s.forEachBoundType(func(t *ir.Type) {
		if (t.Kind == ir.KindVector || t.Kind == ir.KindQuat) && t.Canonical != "" {
			used[t.Canonical] = t
		}
	})

	f := file{
		Symbol:   s.symbol("math"),
		Includes: []string{"math/vec2.h", "math/vec3.h", "math/vec4.h", "math/quat.h"},
	}
	elements := []string{"x", "y", "z", "w"}
	for _, name := range sortedKeys(used) {
		t := used[name]
		rows := t.Rows
		if t.Kind == ir.KindQuat {
			rows = 4
		}
		if rows < 2 || rows > 4 || scalarCpp[t.Scalar] == "" {
			// A dependent type such as TVec2<T>, seen inside a class template, has no
			// concrete element type and nothing to register.
			continue
		}
		f.Arrays = append(f.Arrays, arrayView{
			CppName:  t.Canonical,
			JsName:   mathJsName(t),
			Elements: elements[:rows],
		})
	}
	return f
}

// mathJsName is the name the .d.ts already uses: float3, double2, quatf.
func mathJsName(t *ir.Type) string {
	scalar := map[ir.Kind]string{
		ir.KindF32: "float", ir.KindF64: "double",
		ir.KindI32: "int", ir.KindU32: "uint", ir.KindBool: "bool",
	}[t.Scalar]
	if scalar == "" {
		scalar = "float"
	}
	if t.Kind == ir.KindQuat {
		return "quat" + string(scalar[0])
	}
	return fmt.Sprintf("%s%d", scalar, t.Rows)
}

// isHandle reports a type bound as an object with methods on it rather than as
// a plain value. A struct is a value unless one of its methods would change it,
// which a copy cannot carry back.
func isHandle(c *ir.Class) bool {
	return c.Tag == "class" || c.Mutable()
}

// topLevelClasses are the classes that get a file of their own: the ones no
// other file will pick up.
//
// Being nested is not enough to be picked up. A handle nested inside a value
// struct has nowhere to go, because the struct is registered as a value object
// among all the others rather than in a file of its own -- which is what
// Aabb::Corners is.
func (s *scope) topLevelClasses() []*ir.Class {
	return s.selectClasses(func(c *ir.Class) bool { return isHandle(c) && !s.nestedInHandle(c) })
}

// nestedInHandle reports a class that some other class's file will register.
func (s *scope) nestedInHandle(c *ir.Class) bool {
	for _, other := range s.classes {
		if other != c && isHandle(other) && strings.HasPrefix(c.CppName, other.CppName+"::") {
			return true
		}
	}
	return false
}

// nestedClasses are the bindable classes declared inside parent.
func (s *scope) nestedClasses(parent *ir.Class) []*ir.Class {
	return s.selectClasses(func(c *ir.Class) bool {
		return isHandle(c) && strings.HasPrefix(c.CppName, parent.CppName+"::")
	})
}

func (s *scope) selectClasses(keep func(*ir.Class) bool) []*ir.Class {
	var out []*ir.Class
	for _, c := range s.classes {
		if keep(c) {
			out = append(out, c)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// forEachBoundType visits the type of everything this module actually registers,
// which is what decides the value types the module has to register alongside.
func (s *scope) forEachBoundType(visit func(*ir.Type)) {
	for _, c := range s.classes {
		for _, f := range c.Fields {
			if f.Bind {
				visit(f.Type)
			}
		}
		for _, m := range append(append([]*ir.Method{}, c.Constructors...), c.Methods...) {
			if !m.Bind {
				continue
			}
			visit(m.Return)
			for _, p := range m.Params {
				visit(p.Type)
			}
		}
	}
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedByCppName[T any](items []T, name func(T) string) []T {
	out := append([]T{}, items...)
	sort.Slice(out, func(i, j int) bool { return name(out[i]) < name(out[j]) })
	return out
}
