// This file has been generated by beamsplitter
package com.google.android.filament;

public class backend_Viewport_generated {
    public int left;
    public int bottom;
    public int width;
    public int height;

    public int right() {
        return nRight(this);
    }
    private static native int nRight(backend_Viewport_generated self);

    public int top() {
        return nTop(this);
    }
    private static native int nTop(backend_Viewport_generated self);
}
