// This file has been generated by beamsplitter
package com.google.android.filament;

public class Box_generated {
    private final long mNativeObject;

    public Box_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public boolean isEmpty() {
        return nIsEmpty(mNativeObject);
    }
    private static native boolean nIsEmpty(long nativeObject);

    public float[] getMin() {
        float[] out = new float[3];
        nGetMin(mNativeObject, out);
        return out;
    }
    private static native void nGetMin(long nativeObject, float[] out);

    public float[] getMax() {
        float[] out = new float[3];
        nGetMax(mNativeObject, out);
        return out;
    }
    private static native void nGetMax(long nativeObject, float[] out);

    public long set(float[] min, float[] max) {
        return nSet(mNativeObject, min, max);
    }
    private static native long nSet(long nativeObject, float[] min, float[] max);

    public long unionSelf(long box) {
        return nUnionSelf(mNativeObject, box);
    }
    private static native long nUnionSelf(long nativeObject, long box);

    public float[] getBoundingSphere() {
        float[] out = new float[4];
        nGetBoundingSphere(mNativeObject, out);
        return out;
    }
    private static native void nGetBoundingSphere(long nativeObject, float[] out);
}
