// This file has been generated by beamsplitter
package com.google.android.filament;

public class BufferObject_generated {
    private final long mNativeObject;

    public BufferObject_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getByteCount() {
        return nGetByteCount(mNativeObject);
    }
    private static native long nGetByteCount(long nativeObject);

public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static BufferObject_generated.Builder create() {
        return new BufferObject_generated.Builder(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long size(int byteCount) {
        return nSize(mNativeObject, byteCount);
    }
    private static native long nSize(long nativeObject, int byteCount);

    public long bindingType(int bindingType) {
        return nBindingType(mNativeObject, bindingType);
    }
    private static native long nBindingType(long nativeObject, int bindingType);

    public long name(String name, long len) {
        return nName(mNativeObject, name, len);
    }
    private static native long nName(long nativeObject, String name, long len);

    public long build(long engine) {
        return nBuild(mNativeObject, engine);
    }
    private static native long nBuild(long nativeObject, long engine);
}

}
