// This file has been generated by beamsplitter
package com.google.android.filament;

public class DepthOfFieldOptions_generated {
    public float cocScale = 1f;
    public float cocAspectRatio = 1f;
    public float maxApertureDiameter = 0.00999999977f;
    public boolean enabled = false;
    public int filter = 2;
    public boolean nativeResolution = false;
    public byte foregroundRingCount = (byte) 0;
    public byte backgroundRingCount = (byte) 0;
    public byte fastGatherRingCount = (byte) 0;
    public short maxForegroundCOC = (short) 0;
    public short maxBackgroundCOC = (short) 0;
}
