// This file has been generated by beamsplitter
package com.google.android.filament;

public class Entity_generated {
    private final long mNativeObject;

    public Entity_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Entity_generated create() {
        return new Entity_generated(nCreate());
    }
    private static native long nCreate();

    public boolean equals(int e) {
        return nEquals(mNativeObject, e);
    }
    private static native boolean nEquals(long nativeObject, int e);

    public boolean notEquals(int e) {
        return nNotEquals(mNativeObject, e);
    }
    private static native boolean nNotEquals(long nativeObject, int e);

    public boolean isNull() {
        return nIsNull(mNativeObject);
    }
    private static native boolean nIsNull(long nativeObject);

    public int getId() {
        return nGetId(mNativeObject);
    }
    private static native int nGetId(long nativeObject);

    public void clear() {
        nClear(mNativeObject);
    }
    private static native void nClear(long nativeObject);

    public static int smuggle(int entity) {
        return nSmuggle(entity);
    }
    private static native int nSmuggle(int entity);

    public static int import_(int identity) {
        return nImport(identity);
    }
    private static native int nImport(int identity);

public static class Hasher {
    private final long mNativeObject;

    public Hasher(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long call(long e) {
        return nCall(mNativeObject, e);
    }
    private static native long nCall(long nativeObject, long e);
}

}
