// This file has been generated by beamsplitter
package com.google.android.filament;

public class EntityManager_generated {
    private final long mNativeObject;

    public EntityManager_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static long get() {
        return nGet();
    }
    private static native long nGet();

    public void flushNotifications() {
        nFlushNotifications(mNativeObject);
    }
    private static native void nFlushNotifications(long nativeObject);

    public static long getMaxEntityCount() {
        return nGetMaxEntityCount();
    }
    private static native long nGetMaxEntityCount();

    public long getEntityCount() {
        return nGetEntityCount(mNativeObject);
    }
    private static native long nGetEntityCount(long nativeObject);

    public void create(long n, long entities) {
        nCreate(mNativeObject, n, entities);
    }
    private static native void nCreate(long nativeObject, long n, long entities);

    public void destroy(long n, long entities) {
        nDestroy(mNativeObject, n, entities);
    }
    private static native void nDestroy(long nativeObject, long n, long entities);

    public int create() {
        return nCreate(mNativeObject);
    }
    private static native int nCreate(long nativeObject);

    public void destroy(int e) {
        nDestroy(mNativeObject, e);
    }
    private static native void nDestroy(long nativeObject, int e);

    public boolean isAlive(int e) {
        return nIsAlive(mNativeObject, e);
    }
    private static native boolean nIsAlive(long nativeObject, int e);

    public void registerListener(long l) {
        nRegisterListener(mNativeObject, l);
    }
    private static native void nRegisterListener(long nativeObject, long l);

    public void unregisterListener(long l) {
        nUnregisterListener(mNativeObject, l);
    }
    private static native void nUnregisterListener(long nativeObject, long l);

    public void advanceEpoch() {
        nAdvanceEpoch(mNativeObject);
    }
    private static native void nAdvanceEpoch(long nativeObject);

    public void reclaimSafeEpochs() {
        nReclaimSafeEpochs(mNativeObject);
    }
    private static native void nReclaimSafeEpochs(long nativeObject);

    public long getLatestEpochID() {
        return nGetLatestEpochID(mNativeObject);
    }
    private static native long nGetLatestEpochID(long nativeObject);

    public static int getIndex(int e) {
        return nGetIndex(e);
    }
    private static native int nGetIndex(int e);

public static class Listener {
    private final long mNativeObject;

    public Listener(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public void onEntitiesDestroyed(long n, long entities) {
        nOnEntitiesDestroyed(mNativeObject, n, entities);
    }
    private static native void nOnEntitiesDestroyed(long nativeObject, long n, long entities);
}

}
