// This file has been generated by beamsplitter
package com.google.android.filament;

public class Fence_generated {
    private final long mNativeObject;

    public Fence_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public int wait(int mode, long timeout) {
        return nWait(mNativeObject, mode, timeout);
    }
    private static native int nWait(long nativeObject, int mode, long timeout);

    public static int waitAndDestroy(long fence, int mode) {
        return nWaitAndDestroy(fence, mode);
    }
    private static native int nWaitAndDestroy(long fence, int mode);
}
