// This file has been generated by beamsplitter
package com.google.android.filament;

public class FrameHistoryStream_generated {
    private final long mNativeObject;

    public FrameHistoryStream_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static FrameHistoryStream_generated create(long renderer) {
        return new FrameHistoryStream_generated(nCreate(renderer));
    }
    private static native long nCreate(long renderer);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

public static class Result {
    private final long mNativeObject;

    public Result(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static FrameHistoryStream_generated.Result create() {
        return new FrameHistoryStream_generated.Result(nCreate());
    }
    private static native long nCreate();

    public static FrameHistoryStream_generated.Result create(Renderer_generated.FrameInfo info) {
        return new FrameHistoryStream_generated.Result(nCreate(info));
    }
    private static native long nCreate(Renderer_generated.FrameInfo info);

    public static FrameHistoryStream_generated.Result create(int frameId) {
        return new FrameHistoryStream_generated.Result(nCreate(frameId));
    }
    private static native long nCreate(int frameId);

    public int getFrameId() {
        return nGetFrameId(mNativeObject);
    }
    private static native int nGetFrameId(long nativeObject);

    public int getMissingId() {
        return nGetMissingId(mNativeObject);
    }
    private static native int nGetMissingId(long nativeObject);
}


public static class NewFramesRange {
    private final long mNativeObject;

    public NewFramesRange(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

public static class Iterator {
    private final long mNativeObject;

    public Iterator(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static FrameHistoryStream_generated.NewFramesRange.Iterator create() {
        return new FrameHistoryStream_generated.NewFramesRange.Iterator(nCreate());
    }
    private static native long nCreate();

    public static FrameHistoryStream_generated.NewFramesRange.Iterator create(long historyStart, int historyIndex, int[] pLastProcessedFrameId) {
        return new FrameHistoryStream_generated.NewFramesRange.Iterator(nCreate(historyStart, historyIndex, pLastProcessedFrameId));
    }
    private static native long nCreate(long historyStart, int historyIndex, int[] pLastProcessedFrameId);

    public boolean equals(long rhs) {
        return nEquals(mNativeObject, rhs);
    }
    private static native boolean nEquals(long nativeObject, long rhs);

    public boolean notEquals(long rhs) {
        return nNotEquals(mNativeObject, rhs);
    }
    private static native boolean nNotEquals(long nativeObject, long rhs);
}

}

}
