// This file has been generated by beamsplitter
package com.google.android.filament;

public class FramePipelineEstimator_generated {
    private final long mNativeObject;

    public FramePipelineEstimator_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static double getZScore(int targetPercentile) {
        return nGetZScore(targetPercentile);
    }
    private static native double nGetZScore(int targetPercentile);

public static class Workload {
    private final long mNativeObject;

    public Workload(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}


public static class PacingSizing {
    private final long mNativeObject;

    public PacingSizing(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}

}
