// This file has been generated by beamsplitter
package com.google.android.filament;

public class Frustum_generated {
    private final long mNativeObject;

    public Frustum_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Frustum_generated create() {
        return new Frustum_generated(nCreate());
    }
    private static native long nCreate();

    public static Frustum_generated create(float[] pv) {
        return new Frustum_generated(nCreate(pv));
    }
    private static native long nCreate(float[] pv);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public void setProjection(float[] pv) {
        nSetProjection(mNativeObject, pv);
    }
    private static native void nSetProjection(long nativeObject, float[] pv);

    public float[] getNormalizedPlane(int plane) {
        float[] out = new float[4];
        nGetNormalizedPlane(mNativeObject, plane, out);
        return out;
    }
    private static native void nGetNormalizedPlane(long nativeObject, int plane, float[] out);

    public void getNormalizedPlanes(float[] planes) {
        nGetNormalizedPlanes(mNativeObject, planes);
    }
    private static native void nGetNormalizedPlanes(long nativeObject, float[] planes);

    public boolean intersects(long box) {
        return nIntersects(mNativeObject, box);
    }
    private static native boolean nIntersects(long nativeObject, long box);

    public boolean intersects(float[] sphere) {
        return nIntersects(mNativeObject, sphere);
    }
    private static native boolean nIntersects(long nativeObject, float[] sphere);

    public float contains(float[] p) {
        return nContains(mNativeObject, p);
    }
    private static native float nContains(long nativeObject, float[] p);
}
