// This file has been generated by beamsplitter
package com.google.android.filament;

public class Gamut_generated {
    private final long mNativeObject;

    public Gamut_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Gamut_generated create(Primaries_generated primaries) {
        return new Gamut_generated(nCreate(primaries));
    }
    private static native long nCreate(Primaries_generated primaries);

    public static Gamut_generated create(float[] r, float[] g, float[] b) {
        return new Gamut_generated(nCreate(r, g, b));
    }
    private static native long nCreate(float[] r, float[] g, float[] b);

    public Primaries_generated getPrimaries() {
        return nGetPrimaries(mNativeObject);
    }
    private static native Primaries_generated nGetPrimaries(long nativeObject);
}
