// This file has been generated by beamsplitter
package com.google.android.filament;

public class IndirectLight_generated {
    private final long mNativeObject;

    public IndirectLight_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public void setIntensity(float intensity) {
        nSetIntensity(mNativeObject, intensity);
    }
    private static native void nSetIntensity(long nativeObject, float intensity);

    public float getIntensity() {
        return nGetIntensity(mNativeObject);
    }
    private static native float nGetIntensity(long nativeObject);

    public void setRotation(float[] rotation) {
        nSetRotation(mNativeObject, rotation);
    }
    private static native void nSetRotation(long nativeObject, float[] rotation);

    public float[] getRotation() {
        float[] out = new float[9];
        nGetRotation(mNativeObject, out);
        return out;
    }
    private static native void nGetRotation(long nativeObject, float[] out);

    public long getReflectionsTexture() {
        return nGetReflectionsTexture(mNativeObject);
    }
    private static native long nGetReflectionsTexture(long nativeObject);

    public long getIrradianceTexture() {
        return nGetIrradianceTexture(mNativeObject);
    }
    private static native long nGetIrradianceTexture(long nativeObject);

    public static float[] getDirectionEstimate(float[] sh) {
        float[] out = new float[3];
        nGetDirectionEstimate(sh, out);
        return out;
    }
    private static native void nGetDirectionEstimate(float[] sh, float[] out);

    public static float[] getColorEstimate(float[] sh, float[] direction) {
        float[] out = new float[4];
        nGetColorEstimate(sh, direction, out);
        return out;
    }
    private static native void nGetColorEstimate(float[] sh, float[] direction, float[] out);

    public float[] getDirectionEstimate() {
        float[] out = new float[3];
        nGetDirectionEstimate(mNativeObject, out);
        return out;
    }
    private static native void nGetDirectionEstimate(long nativeObject, float[] out);

    public float[] getColorEstimate(float[] direction) {
        float[] out = new float[4];
        nGetColorEstimate(mNativeObject, direction, out);
        return out;
    }
    private static native void nGetColorEstimate(long nativeObject, float[] direction, float[] out);

public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static IndirectLight_generated.Builder create() {
        return new IndirectLight_generated.Builder(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long reflections(long cubemap) {
        return nReflections(mNativeObject, cubemap);
    }
    private static native long nReflections(long nativeObject, long cubemap);

    public long irradiance(byte bands, float[] sh) {
        return nIrradiance(mNativeObject, bands, sh);
    }
    private static native long nIrradiance(long nativeObject, byte bands, float[] sh);

    public long radiance(byte bands, float[] sh) {
        return nRadiance(mNativeObject, bands, sh);
    }
    private static native long nRadiance(long nativeObject, byte bands, float[] sh);

    public long irradiance(long cubemap) {
        return nIrradiance(mNativeObject, cubemap);
    }
    private static native long nIrradiance(long nativeObject, long cubemap);

    public long intensity(float envIntensity) {
        return nIntensity(mNativeObject, envIntensity);
    }
    private static native long nIntensity(long nativeObject, float envIntensity);

    public long rotation(float[] rotation) {
        return nRotation(mNativeObject, rotation);
    }
    private static native long nRotation(long nativeObject, float[] rotation);

    public long build(long engine) {
        return nBuild(mNativeObject, engine);
    }
    private static native long nBuild(long nativeObject, long engine);
}

}
