// This file has been generated by beamsplitter
package com.google.android.filament;

public class InstanceBuffer_generated {
    private final long mNativeObject;

    public InstanceBuffer_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getInstanceCount() {
        return nGetInstanceCount(mNativeObject);
    }
    private static native long nGetInstanceCount(long nativeObject);

    public void setLocalTransforms(float[] localTransforms, long count, long offset) {
        nSetLocalTransforms(mNativeObject, localTransforms, count, offset);
    }
    private static native void nSetLocalTransforms(long nativeObject, float[] localTransforms, long count, long offset);

    public float[] getLocalTransform(long index) {
        float[] out = new float[16];
        nGetLocalTransform(mNativeObject, index, out);
        return out;
    }
    private static native void nGetLocalTransform(long nativeObject, long index, float[] out);

public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static InstanceBuffer_generated.Builder create(long instanceCount) {
        return new InstanceBuffer_generated.Builder(nCreate(instanceCount));
    }
    private static native long nCreate(long instanceCount);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long localTransforms(float[] localTransforms) {
        return nLocalTransforms(mNativeObject, localTransforms);
    }
    private static native long nLocalTransforms(long nativeObject, float[] localTransforms);

    public long name(String name, long len) {
        return nName(mNativeObject, name, len);
    }
    private static native long nName(long nativeObject, String name, long len);

    public long build(long engine) {
        return nBuild(mNativeObject, engine);
    }
    private static native long nBuild(long nativeObject, long engine);
}

}
