// This file has been generated by beamsplitter
package com.google.android.filament;

public class LightManager_generated {
    private final long mNativeObject;

    public LightManager_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long getComponentCount() {
        return nGetComponentCount(mNativeObject);
    }
    private static native long nGetComponentCount(long nativeObject);

    public boolean hasComponent(int e) {
        return nHasComponent(mNativeObject, e);
    }
    private static native boolean nHasComponent(long nativeObject, int e);

    public boolean empty() {
        return nEmpty(mNativeObject);
    }
    private static native boolean nEmpty(long nativeObject);

    public int getEntity(int i) {
        return nGetEntity(mNativeObject, i);
    }
    private static native int nGetEntity(long nativeObject, int i);

    public long getEntities() {
        return nGetEntities(mNativeObject);
    }
    private static native long nGetEntities(long nativeObject);

    public int getInstance(int e) {
        return nGetInstance(mNativeObject, e);
    }
    private static native int nGetInstance(long nativeObject, int e);

    public void destroy(int e) {
        nDestroy(mNativeObject, e);
    }
    private static native void nDestroy(long nativeObject, int e);

    public int getType(int i) {
        return nGetType(mNativeObject, i);
    }
    private static native int nGetType(long nativeObject, int i);

    public boolean isDirectional(int i) {
        return nIsDirectional(mNativeObject, i);
    }
    private static native boolean nIsDirectional(long nativeObject, int i);

    public boolean isPointLight(int i) {
        return nIsPointLight(mNativeObject, i);
    }
    private static native boolean nIsPointLight(long nativeObject, int i);

    public boolean isSpotLight(int i) {
        return nIsSpotLight(mNativeObject, i);
    }
    private static native boolean nIsSpotLight(long nativeObject, int i);

    public void setLightChannel(int i, int channel, boolean enable) {
        nSetLightChannel(mNativeObject, i, channel, enable);
    }
    private static native void nSetLightChannel(long nativeObject, int i, int channel, boolean enable);

    public boolean getLightChannel(int i, int channel) {
        return nGetLightChannel(mNativeObject, i, channel);
    }
    private static native boolean nGetLightChannel(long nativeObject, int i, int channel);

    public void setPosition(int i, float[] position) {
        nSetPosition(mNativeObject, i, position);
    }
    private static native void nSetPosition(long nativeObject, int i, float[] position);

    public float[] getPosition(int i) {
        float[] out = new float[3];
        nGetPosition(mNativeObject, i, out);
        return out;
    }
    private static native void nGetPosition(long nativeObject, int i, float[] out);

    public void setDirection(int i, float[] direction) {
        nSetDirection(mNativeObject, i, direction);
    }
    private static native void nSetDirection(long nativeObject, int i, float[] direction);

    public float[] getDirection(int i) {
        float[] out = new float[3];
        nGetDirection(mNativeObject, i, out);
        return out;
    }
    private static native void nGetDirection(long nativeObject, int i, float[] out);

    public void setColor(int i, float[] color) {
        nSetColor(mNativeObject, i, color);
    }
    private static native void nSetColor(long nativeObject, int i, float[] color);

    public float[] getColor(int i) {
        float[] out = new float[3];
        nGetColor(mNativeObject, i, out);
        return out;
    }
    private static native void nGetColor(long nativeObject, int i, float[] out);

    public void setIntensity(int i, float intensity) {
        nSetIntensity(mNativeObject, i, intensity);
    }
    private static native void nSetIntensity(long nativeObject, int i, float intensity);

    public void setIntensity(int i, float watts, float efficiency) {
        nSetIntensity(mNativeObject, i, watts, efficiency);
    }
    private static native void nSetIntensity(long nativeObject, int i, float watts, float efficiency);

    public void setIntensityCandela(int i, float intensity) {
        nSetIntensityCandela(mNativeObject, i, intensity);
    }
    private static native void nSetIntensityCandela(long nativeObject, int i, float intensity);

    public float getIntensity(int i) {
        return nGetIntensity(mNativeObject, i);
    }
    private static native float nGetIntensity(long nativeObject, int i);

    public void setFalloff(int i, float radius) {
        nSetFalloff(mNativeObject, i, radius);
    }
    private static native void nSetFalloff(long nativeObject, int i, float radius);

    public float getFalloff(int i) {
        return nGetFalloff(mNativeObject, i);
    }
    private static native float nGetFalloff(long nativeObject, int i);

    public void setSpotLightCone(int i, float inner, float outer) {
        nSetSpotLightCone(mNativeObject, i, inner, outer);
    }
    private static native void nSetSpotLightCone(long nativeObject, int i, float inner, float outer);

    public float getSpotLightOuterCone(int i) {
        return nGetSpotLightOuterCone(mNativeObject, i);
    }
    private static native float nGetSpotLightOuterCone(long nativeObject, int i);

    public float getSpotLightInnerCone(int i) {
        return nGetSpotLightInnerCone(mNativeObject, i);
    }
    private static native float nGetSpotLightInnerCone(long nativeObject, int i);

    public void setSunAngularRadius(int i, float angularRadius) {
        nSetSunAngularRadius(mNativeObject, i, angularRadius);
    }
    private static native void nSetSunAngularRadius(long nativeObject, int i, float angularRadius);

    public float getSunAngularRadius(int i) {
        return nGetSunAngularRadius(mNativeObject, i);
    }
    private static native float nGetSunAngularRadius(long nativeObject, int i);

    public void setSunHaloSize(int i, float haloSize) {
        nSetSunHaloSize(mNativeObject, i, haloSize);
    }
    private static native void nSetSunHaloSize(long nativeObject, int i, float haloSize);

    public float getSunHaloSize(int i) {
        return nGetSunHaloSize(mNativeObject, i);
    }
    private static native float nGetSunHaloSize(long nativeObject, int i);

    public void setSunHaloFalloff(int i, float haloFalloff) {
        nSetSunHaloFalloff(mNativeObject, i, haloFalloff);
    }
    private static native void nSetSunHaloFalloff(long nativeObject, int i, float haloFalloff);

    public float getSunHaloFalloff(int i) {
        return nGetSunHaloFalloff(mNativeObject, i);
    }
    private static native float nGetSunHaloFalloff(long nativeObject, int i);

    public LightManager_generated.ShadowOptions getShadowOptions(int i) {
        return nGetShadowOptions(mNativeObject, i);
    }
    private static native LightManager_generated.ShadowOptions nGetShadowOptions(long nativeObject, int i);

    public void setShadowOptions(int i, LightManager_generated.ShadowOptions options) {
        nSetShadowOptions(mNativeObject, i, options);
    }
    private static native void nSetShadowOptions(long nativeObject, int i, LightManager_generated.ShadowOptions options);

    public void setShadowCaster(int i, boolean shadowCaster) {
        nSetShadowCaster(mNativeObject, i, shadowCaster);
    }
    private static native void nSetShadowCaster(long nativeObject, int i, boolean shadowCaster);

    public boolean isShadowCaster(int i) {
        return nIsShadowCaster(mNativeObject, i);
    }
    private static native boolean nIsShadowCaster(long nativeObject, int i);

public static class ShadowOptions {
    public int mapSize = 1024;
    public byte shadowCascades = (byte) 1;
    public float[] cascadeSplitPositions = new float[3];
    public float constantBias = 0.00100000005f;
    public float normalBias = 1f;
    public float shadowFar = 0f;
    public float shadowNearHint = 1f;
    public float shadowFarHint = 100f;
    public boolean stable = false;
    public boolean lispsm = true;
    public float polygonOffsetConstant = 0.5f;
    public float polygonOffsetSlope = 2f;
    public boolean screenSpaceContactShadows = false;
    public byte stepCount = (byte) 8;
    public float maxShadowDistance = 0.300000012f;
    public LightManager_generated.ShadowOptions.Vsm vsm = new LightManager_generated.ShadowOptions.Vsm();
    public float shadowBulbRadius = -1f;
    public float[] transform = new float[4];
    public float penumbraScale = 1f;
    public float penumbraRatioScale = 1f;
    public float maxPenumbraRatio = 0f;
    public float maxSearchRadius = 0f;

public static class Vsm {
    public boolean elvsm = false;
    public float blurWidth = 0f;
}

}


public static class ShadowCascades {
    private final long mNativeObject;

    public ShadowCascades(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static void computeUniformSplits(float[] splitPositions, byte cascades) {
        nComputeUniformSplits(splitPositions, cascades);
    }
    private static native void nComputeUniformSplits(float[] splitPositions, byte cascades);

    public static void computeLogSplits(float[] splitPositions, byte cascades, float near, float far) {
        nComputeLogSplits(splitPositions, cascades, near, far);
    }
    private static native void nComputeLogSplits(float[] splitPositions, byte cascades, float near, float far);

    public static void computePracticalSplits(float[] splitPositions, byte cascades, float near, float far, float lambda) {
        nComputePracticalSplits(splitPositions, cascades, near, far, lambda);
    }
    private static native void nComputePracticalSplits(float[] splitPositions, byte cascades, float near, float far, float lambda);
}


public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static LightManager_generated.Builder create(int type) {
        return new LightManager_generated.Builder(nCreate(type));
    }
    private static native long nCreate(int type);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long lightChannel(int channel, boolean enable) {
        return nLightChannel(mNativeObject, channel, enable);
    }
    private static native long nLightChannel(long nativeObject, int channel, boolean enable);

    public long castShadows(boolean enable) {
        return nCastShadows(mNativeObject, enable);
    }
    private static native long nCastShadows(long nativeObject, boolean enable);

    public long shadowOptions(LightManager_generated.ShadowOptions options) {
        return nShadowOptions(mNativeObject, options);
    }
    private static native long nShadowOptions(long nativeObject, LightManager_generated.ShadowOptions options);

    public long castLight(boolean enable) {
        return nCastLight(mNativeObject, enable);
    }
    private static native long nCastLight(long nativeObject, boolean enable);

    public long position(float[] position) {
        return nPosition(mNativeObject, position);
    }
    private static native long nPosition(long nativeObject, float[] position);

    public long direction(float[] direction) {
        return nDirection(mNativeObject, direction);
    }
    private static native long nDirection(long nativeObject, float[] direction);

    public long color(float[] color) {
        return nColor(mNativeObject, color);
    }
    private static native long nColor(long nativeObject, float[] color);

    public long intensity(float intensity) {
        return nIntensity(mNativeObject, intensity);
    }
    private static native long nIntensity(long nativeObject, float intensity);

    public long intensityCandela(float intensity) {
        return nIntensityCandela(mNativeObject, intensity);
    }
    private static native long nIntensityCandela(long nativeObject, float intensity);

    public long intensity(float watts, float efficiency) {
        return nIntensity(mNativeObject, watts, efficiency);
    }
    private static native long nIntensity(long nativeObject, float watts, float efficiency);

    public long falloff(float radius) {
        return nFalloff(mNativeObject, radius);
    }
    private static native long nFalloff(long nativeObject, float radius);

    public long spotLightCone(float inner, float outer) {
        return nSpotLightCone(mNativeObject, inner, outer);
    }
    private static native long nSpotLightCone(long nativeObject, float inner, float outer);

    public long sunAngularRadius(float angularRadiusDeg) {
        return nSunAngularRadius(mNativeObject, angularRadiusDeg);
    }
    private static native long nSunAngularRadius(long nativeObject, float angularRadiusDeg);

    public long sunHaloSize(float haloSize) {
        return nSunHaloSize(mNativeObject, haloSize);
    }
    private static native long nSunHaloSize(long nativeObject, float haloSize);

    public long sunHaloFalloff(float haloFalloff) {
        return nSunHaloFalloff(mNativeObject, haloFalloff);
    }
    private static native long nSunHaloFalloff(long nativeObject, float haloFalloff);

    public int build(long engine, int entity) {
        return nBuild(mNativeObject, engine, entity);
    }
    private static native int nBuild(long nativeObject, long engine, int entity);
}

}
