// This file has been generated by beamsplitter
package com.google.android.filament;

public class Material_generated {
    private final long mNativeObject;

    public Material_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public long createInstance(String name) {
        return nCreateInstance(mNativeObject, name);
    }
    private static native long nCreateInstance(long nativeObject, String name);

    public String getName() {
        return nGetName(mNativeObject);
    }
    private static native String nGetName(long nativeObject);

    public int getShading() {
        return nGetShading(mNativeObject);
    }
    private static native int nGetShading(long nativeObject);

    public int getInterpolation() {
        return nGetInterpolation(mNativeObject);
    }
    private static native int nGetInterpolation(long nativeObject);

    public int getBlendingMode() {
        return nGetBlendingMode(mNativeObject);
    }
    private static native int nGetBlendingMode(long nativeObject);

    public int getVertexDomain() {
        return nGetVertexDomain(mNativeObject);
    }
    private static native int nGetVertexDomain(long nativeObject);

    public int getSupportedVariants() {
        return nGetSupportedVariants(mNativeObject);
    }
    private static native int nGetSupportedVariants(long nativeObject);

    public int getMaterialDomain() {
        return nGetMaterialDomain(mNativeObject);
    }
    private static native int nGetMaterialDomain(long nativeObject);

    public int getCullingMode() {
        return nGetCullingMode(mNativeObject);
    }
    private static native int nGetCullingMode(long nativeObject);

    public int getTransparencyMode() {
        return nGetTransparencyMode(mNativeObject);
    }
    private static native int nGetTransparencyMode(long nativeObject);

    public boolean isColorWriteEnabled() {
        return nIsColorWriteEnabled(mNativeObject);
    }
    private static native boolean nIsColorWriteEnabled(long nativeObject);

    public boolean isDepthWriteEnabled() {
        return nIsDepthWriteEnabled(mNativeObject);
    }
    private static native boolean nIsDepthWriteEnabled(long nativeObject);

    public boolean isDepthCullingEnabled() {
        return nIsDepthCullingEnabled(mNativeObject);
    }
    private static native boolean nIsDepthCullingEnabled(long nativeObject);

    public boolean isDoubleSided() {
        return nIsDoubleSided(mNativeObject);
    }
    private static native boolean nIsDoubleSided(long nativeObject);

    public boolean isAlphaToCoverageEnabled() {
        return nIsAlphaToCoverageEnabled(mNativeObject);
    }
    private static native boolean nIsAlphaToCoverageEnabled(long nativeObject);

    public float getMaskThreshold() {
        return nGetMaskThreshold(mNativeObject);
    }
    private static native float nGetMaskThreshold(long nativeObject);

    public boolean hasShadowMultiplier() {
        return nHasShadowMultiplier(mNativeObject);
    }
    private static native boolean nHasShadowMultiplier(long nativeObject);

    public boolean hasSpecularAntiAliasing() {
        return nHasSpecularAntiAliasing(mNativeObject);
    }
    private static native boolean nHasSpecularAntiAliasing(long nativeObject);

    public float getSpecularAntiAliasingVariance() {
        return nGetSpecularAntiAliasingVariance(mNativeObject);
    }
    private static native float nGetSpecularAntiAliasingVariance(long nativeObject);

    public float getSpecularAntiAliasingThreshold() {
        return nGetSpecularAntiAliasingThreshold(mNativeObject);
    }
    private static native float nGetSpecularAntiAliasingThreshold(long nativeObject);

    public int getRefractionMode() {
        return nGetRefractionMode(mNativeObject);
    }
    private static native int nGetRefractionMode(long nativeObject);

    public int getRefractionType() {
        return nGetRefractionType(mNativeObject);
    }
    private static native int nGetRefractionType(long nativeObject);

    public int getReflectionMode() {
        return nGetReflectionMode(mNativeObject);
    }
    private static native int nGetReflectionMode(long nativeObject);

    public int getFeatureLevel() {
        return nGetFeatureLevel(mNativeObject);
    }
    private static native int nGetFeatureLevel(long nativeObject);

    public long getParameterCount() {
        return nGetParameterCount(mNativeObject);
    }
    private static native long nGetParameterCount(long nativeObject);

    public long getParameters(long parameters, long count) {
        return nGetParameters(mNativeObject, parameters, count);
    }
    private static native long nGetParameters(long nativeObject, long parameters, long count);

    public boolean isSampler(String name) {
        return nIsSampler(mNativeObject, name);
    }
    private static native boolean nIsSampler(long nativeObject, String name);

    public String getSource() {
        return nGetSource(mNativeObject);
    }
    private static native String nGetSource(long nativeObject);

    public String getParameterTransformName(String samplerName) {
        return nGetParameterTransformName(mNativeObject, samplerName);
    }
    private static native String nGetParameterTransformName(long nativeObject, String samplerName);

    public void setDefaultParameter(String name, boolean value) {
        nSetDefaultParameter(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameter(long nativeObject, String name, boolean value);

    public void setDefaultParameterInt(String name, int value) {
        nSetDefaultParameterInt(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterInt(long nativeObject, String name, int value);

    public void setDefaultParameterString(String name, int value) {
        nSetDefaultParameterString(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterString(long nativeObject, String name, int value);

    public void setDefaultParameter(String name, float value) {
        nSetDefaultParameter(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameter(long nativeObject, String name, float value);

    public void setDefaultParameterFloat2(String name, float[] value) {
        nSetDefaultParameterFloat2(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterFloat2(long nativeObject, String name, float[] value);

    public void setDefaultParameterFloat3(String name, float[] value) {
        nSetDefaultParameterFloat3(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterFloat3(long nativeObject, String name, float[] value);

    public void setDefaultParameterFloat4(String name, float[] value) {
        nSetDefaultParameterFloat4(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterFloat4(long nativeObject, String name, float[] value);

    public void setDefaultParameterMat3f(String name, float[] value) {
        nSetDefaultParameterMat3f(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterMat3f(long nativeObject, String name, float[] value);

    public void setDefaultParameterMat4f(String name, float[] value) {
        nSetDefaultParameterMat4f(mNativeObject, name, value);
    }
    private static native void nSetDefaultParameterMat4f(long nativeObject, String name, float[] value);

    public void setDefaultParameter(String name, long texture, long sampler) {
        nSetDefaultParameter(mNativeObject, name, texture, sampler);
    }
    private static native void nSetDefaultParameter(long nativeObject, String name, long texture, long sampler);

    public void setDefaultParameterFloat3(String name, int type, float[] color) {
        nSetDefaultParameterFloat3(mNativeObject, name, type, color);
    }
    private static native void nSetDefaultParameterFloat3(long nativeObject, String name, int type, float[] color);

    public void setDefaultParameterFloat4(String name, int type, float[] color) {
        nSetDefaultParameterFloat4(mNativeObject, name, type, color);
    }
    private static native void nSetDefaultParameterFloat4(long nativeObject, String name, int type, float[] color);

    public long getDefaultInstance() {
        return nGetDefaultInstance(mNativeObject);
    }
    private static native long nGetDefaultInstance(long nativeObject);

public static class ParameterInfo {
    private final long mNativeObject;

    public ParameterInfo(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }
}


public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Material_generated.Builder create() {
        return new Material_generated.Builder(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long sphericalHarmonicsBandCount(long shBandCount) {
        return nSphericalHarmonicsBandCount(mNativeObject, shBandCount);
    }
    private static native long nSphericalHarmonicsBandCount(long nativeObject, long shBandCount);

    public long shadowSamplingQuality(int quality) {
        return nShadowSamplingQuality(mNativeObject, quality);
    }
    private static native long nShadowSamplingQuality(long nativeObject, int quality);

    public long uboBatching(int uboBatchingMode) {
        return nUboBatching(mNativeObject, uboBatchingMode);
    }
    private static native long nUboBatching(long nativeObject, int uboBatchingMode);

    public long build(long engine) {
        return nBuild(mNativeObject, engine);
    }
    private static native long nBuild(long nativeObject, long engine);
}

}
