// This file has been generated by beamsplitter
package com.google.android.filament;

public class MaterialInstance_generated {
    private final long mNativeObject;

    public MaterialInstance_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static long duplicate(long other, String name) {
        return nDuplicate(other, name);
    }
    private static native long nDuplicate(long other, String name);

    public long getMaterial() {
        return nGetMaterial(mNativeObject);
    }
    private static native long nGetMaterial(long nativeObject);

    public String getName() {
        return nGetName(mNativeObject);
    }
    private static native String nGetName(long nativeObject);

    public void setParameter(String name, long nameLength, boolean value) {
        nSetParameter(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameter(long nativeObject, String name, long nameLength, boolean value);

    public void setParameterInt(String name, long nameLength, int value) {
        nSetParameterInt(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterInt(long nativeObject, String name, long nameLength, int value);

    public void setParameterLong(String name, long nameLength, int value) {
        nSetParameterLong(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterLong(long nativeObject, String name, long nameLength, int value);

    public void setParameter(String name, long nameLength, float value) {
        nSetParameter(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameter(long nativeObject, String name, long nameLength, float value);

    public void setParameterFloat2(String name, long nameLength, float[] value) {
        nSetParameterFloat2(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterFloat2(long nativeObject, String name, long nameLength, float[] value);

    public void setParameterFloat3(String name, long nameLength, float[] value) {
        nSetParameterFloat3(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterFloat3(long nativeObject, String name, long nameLength, float[] value);

    public void setParameterFloat4(String name, long nameLength, float[] value) {
        nSetParameterFloat4(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterFloat4(long nativeObject, String name, long nameLength, float[] value);

    public void setParameterMat3f(String name, long nameLength, float[] value) {
        nSetParameterMat3f(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterMat3f(long nativeObject, String name, long nameLength, float[] value);

    public void setParameterMat4f(String name, long nameLength, float[] value) {
        nSetParameterMat4f(mNativeObject, name, nameLength, value);
    }
    private static native void nSetParameterMat4f(long nativeObject, String name, long nameLength, float[] value);

    public void setParameter(String name, boolean value) {
        nSetParameter(mNativeObject, name, value);
    }
    private static native void nSetParameter(long nativeObject, String name, boolean value);

    public void setParameterInt(String name, int value) {
        nSetParameterInt(mNativeObject, name, value);
    }
    private static native void nSetParameterInt(long nativeObject, String name, int value);

    public void setParameterString(String name, int value) {
        nSetParameterString(mNativeObject, name, value);
    }
    private static native void nSetParameterString(long nativeObject, String name, int value);

    public void setParameter(String name, float value) {
        nSetParameter(mNativeObject, name, value);
    }
    private static native void nSetParameter(long nativeObject, String name, float value);

    public void setParameterFloat2(String name, float[] value) {
        nSetParameterFloat2(mNativeObject, name, value);
    }
    private static native void nSetParameterFloat2(long nativeObject, String name, float[] value);

    public void setParameterFloat3(String name, float[] value) {
        nSetParameterFloat3(mNativeObject, name, value);
    }
    private static native void nSetParameterFloat3(long nativeObject, String name, float[] value);

    public void setParameterFloat4(String name, float[] value) {
        nSetParameterFloat4(mNativeObject, name, value);
    }
    private static native void nSetParameterFloat4(long nativeObject, String name, float[] value);

    public void setParameterMat3f(String name, float[] value) {
        nSetParameterMat3f(mNativeObject, name, value);
    }
    private static native void nSetParameterMat3f(long nativeObject, String name, float[] value);

    public void setParameterMat4f(String name, float[] value) {
        nSetParameterMat4f(mNativeObject, name, value);
    }
    private static native void nSetParameterMat4f(long nativeObject, String name, float[] value);

    public void setParameter(String name, long nameLength, boolean[] values, long count) {
        nSetParameter(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameter(long nativeObject, String name, long nameLength, boolean[] values, long count);

    public void setParameterLong(String name, long nameLength, int[] values, long count) {
        nSetParameterLong(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterLong(long nativeObject, String name, long nameLength, int[] values, long count);

    public void setParameterInt(String name, long nameLength, int[] values, long count) {
        nSetParameterInt(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterInt(long nativeObject, String name, long nameLength, int[] values, long count);

    public void setParameterLong(String name, long nameLength, float[] values, long count) {
        nSetParameterLong(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterLong(long nativeObject, String name, long nameLength, float[] values, long count);

    public void setParameterFloat2(String name, long nameLength, float[] values, long count) {
        nSetParameterFloat2(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterFloat2(long nativeObject, String name, long nameLength, float[] values, long count);

    public void setParameterFloat3(String name, long nameLength, float[] values, long count) {
        nSetParameterFloat3(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterFloat3(long nativeObject, String name, long nameLength, float[] values, long count);

    public void setParameterFloat4(String name, long nameLength, float[] values, long count) {
        nSetParameterFloat4(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterFloat4(long nativeObject, String name, long nameLength, float[] values, long count);

    public void setParameterMat3f(String name, long nameLength, float[] values, long count) {
        nSetParameterMat3f(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterMat3f(long nativeObject, String name, long nameLength, float[] values, long count);

    public void setParameterMat4f(String name, long nameLength, float[] values, long count) {
        nSetParameterMat4f(mNativeObject, name, nameLength, values, count);
    }
    private static native void nSetParameterMat4f(long nativeObject, String name, long nameLength, float[] values, long count);

    public void setParameter(String name, boolean[] values, long count) {
        nSetParameter(mNativeObject, name, values, count);
    }
    private static native void nSetParameter(long nativeObject, String name, boolean[] values, long count);

    public void setParameterLong(String name, int[] values, long count) {
        nSetParameterLong(mNativeObject, name, values, count);
    }
    private static native void nSetParameterLong(long nativeObject, String name, int[] values, long count);

    public void setParameterInt(String name, int[] values, long count) {
        nSetParameterInt(mNativeObject, name, values, count);
    }
    private static native void nSetParameterInt(long nativeObject, String name, int[] values, long count);

    public void setParameterLong(String name, float[] values, long count) {
        nSetParameterLong(mNativeObject, name, values, count);
    }
    private static native void nSetParameterLong(long nativeObject, String name, float[] values, long count);

    public void setParameterFloat2(String name, float[] values, long count) {
        nSetParameterFloat2(mNativeObject, name, values, count);
    }
    private static native void nSetParameterFloat2(long nativeObject, String name, float[] values, long count);

    public void setParameterFloat3(String name, float[] values, long count) {
        nSetParameterFloat3(mNativeObject, name, values, count);
    }
    private static native void nSetParameterFloat3(long nativeObject, String name, float[] values, long count);

    public void setParameterFloat4(String name, float[] values, long count) {
        nSetParameterFloat4(mNativeObject, name, values, count);
    }
    private static native void nSetParameterFloat4(long nativeObject, String name, float[] values, long count);

    public void setParameterMat3f(String name, float[] values, long count) {
        nSetParameterMat3f(mNativeObject, name, values, count);
    }
    private static native void nSetParameterMat3f(long nativeObject, String name, float[] values, long count);

    public void setParameterMat4f(String name, float[] values, long count) {
        nSetParameterMat4f(mNativeObject, name, values, count);
    }
    private static native void nSetParameterMat4f(long nativeObject, String name, float[] values, long count);

    public void setParameter(String name, long nameLength, long texture, long sampler) {
        nSetParameter(mNativeObject, name, nameLength, texture, sampler);
    }
    private static native void nSetParameter(long nativeObject, String name, long nameLength, long texture, long sampler);

    public void setParameter(String name, long texture, long sampler) {
        nSetParameter(mNativeObject, name, texture, sampler);
    }
    private static native void nSetParameter(long nativeObject, String name, long texture, long sampler);

    public void setParameterFloat3(String name, long nameLength, int type, float[] color) {
        nSetParameterFloat3(mNativeObject, name, nameLength, type, color);
    }
    private static native void nSetParameterFloat3(long nativeObject, String name, long nameLength, int type, float[] color);

    public void setParameterFloat3(String name, int type, float[] color) {
        nSetParameterFloat3(mNativeObject, name, type, color);
    }
    private static native void nSetParameterFloat3(long nativeObject, String name, int type, float[] color);

    public void setParameterFloat4(String name, long nameLength, int type, float[] color) {
        nSetParameterFloat4(mNativeObject, name, nameLength, type, color);
    }
    private static native void nSetParameterFloat4(long nativeObject, String name, long nameLength, int type, float[] color);

    public void setParameterFloat4(String name, int type, float[] color) {
        nSetParameterFloat4(mNativeObject, name, type, color);
    }
    private static native void nSetParameterFloat4(long nativeObject, String name, int type, float[] color);

    public void setScissor(int left, int bottom, int width, int height) {
        nSetScissor(mNativeObject, left, bottom, width, height);
    }
    private static native void nSetScissor(long nativeObject, int left, int bottom, int width, int height);

    public void unsetScissor() {
        nUnsetScissor(mNativeObject);
    }
    private static native void nUnsetScissor(long nativeObject);

    public void setPolygonOffset(float scale, float constant) {
        nSetPolygonOffset(mNativeObject, scale, constant);
    }
    private static native void nSetPolygonOffset(long nativeObject, float scale, float constant);

    public void setMaskThreshold(float threshold) {
        nSetMaskThreshold(mNativeObject, threshold);
    }
    private static native void nSetMaskThreshold(long nativeObject, float threshold);

    public float getMaskThreshold() {
        return nGetMaskThreshold(mNativeObject);
    }
    private static native float nGetMaskThreshold(long nativeObject);

    public void setSpecularAntiAliasingVariance(float variance) {
        nSetSpecularAntiAliasingVariance(mNativeObject, variance);
    }
    private static native void nSetSpecularAntiAliasingVariance(long nativeObject, float variance);

    public float getSpecularAntiAliasingVariance() {
        return nGetSpecularAntiAliasingVariance(mNativeObject);
    }
    private static native float nGetSpecularAntiAliasingVariance(long nativeObject);

    public void setSpecularAntiAliasingThreshold(float threshold) {
        nSetSpecularAntiAliasingThreshold(mNativeObject, threshold);
    }
    private static native void nSetSpecularAntiAliasingThreshold(long nativeObject, float threshold);

    public float getSpecularAntiAliasingThreshold() {
        return nGetSpecularAntiAliasingThreshold(mNativeObject);
    }
    private static native float nGetSpecularAntiAliasingThreshold(long nativeObject);

    public void setDoubleSided(boolean doubleSided) {
        nSetDoubleSided(mNativeObject, doubleSided);
    }
    private static native void nSetDoubleSided(long nativeObject, boolean doubleSided);

    public boolean isDoubleSided() {
        return nIsDoubleSided(mNativeObject);
    }
    private static native boolean nIsDoubleSided(long nativeObject);

    public void setTransparencyMode(int mode) {
        nSetTransparencyMode(mNativeObject, mode);
    }
    private static native void nSetTransparencyMode(long nativeObject, int mode);

    public int getTransparencyMode() {
        return nGetTransparencyMode(mNativeObject);
    }
    private static native int nGetTransparencyMode(long nativeObject);

    public void setCullingMode(int culling) {
        nSetCullingMode(mNativeObject, culling);
    }
    private static native void nSetCullingMode(long nativeObject, int culling);

    public void setCullingMode(int colorPassCullingMode, int shadowPassCullingMode) {
        nSetCullingMode(mNativeObject, colorPassCullingMode, shadowPassCullingMode);
    }
    private static native void nSetCullingMode(long nativeObject, int colorPassCullingMode, int shadowPassCullingMode);

    public int getCullingMode() {
        return nGetCullingMode(mNativeObject);
    }
    private static native int nGetCullingMode(long nativeObject);

    public int getShadowCullingMode() {
        return nGetShadowCullingMode(mNativeObject);
    }
    private static native int nGetShadowCullingMode(long nativeObject);

    public void setColorWrite(boolean enable) {
        nSetColorWrite(mNativeObject, enable);
    }
    private static native void nSetColorWrite(long nativeObject, boolean enable);

    public boolean isColorWriteEnabled() {
        return nIsColorWriteEnabled(mNativeObject);
    }
    private static native boolean nIsColorWriteEnabled(long nativeObject);

    public void setDepthWrite(boolean enable) {
        nSetDepthWrite(mNativeObject, enable);
    }
    private static native void nSetDepthWrite(long nativeObject, boolean enable);

    public boolean isDepthWriteEnabled() {
        return nIsDepthWriteEnabled(mNativeObject);
    }
    private static native boolean nIsDepthWriteEnabled(long nativeObject);

    public void setDepthCulling(boolean enable) {
        nSetDepthCulling(mNativeObject, enable);
    }
    private static native void nSetDepthCulling(long nativeObject, boolean enable);

    public void setDepthFunc(int depthFunc) {
        nSetDepthFunc(mNativeObject, depthFunc);
    }
    private static native void nSetDepthFunc(long nativeObject, int depthFunc);

    public int getDepthFunc() {
        return nGetDepthFunc(mNativeObject);
    }
    private static native int nGetDepthFunc(long nativeObject);

    public boolean isDepthCullingEnabled() {
        return nIsDepthCullingEnabled(mNativeObject);
    }
    private static native boolean nIsDepthCullingEnabled(long nativeObject);

    public void setStencilWrite(boolean enable) {
        nSetStencilWrite(mNativeObject, enable);
    }
    private static native void nSetStencilWrite(long nativeObject, boolean enable);

    public boolean isStencilWriteEnabled() {
        return nIsStencilWriteEnabled(mNativeObject);
    }
    private static native boolean nIsStencilWriteEnabled(long nativeObject);

    public void setStencilCompareFunction(int func, int face) {
        nSetStencilCompareFunction(mNativeObject, func, face);
    }
    private static native void nSetStencilCompareFunction(long nativeObject, int func, int face);

    public void setStencilOpStencilFail(int op, int face) {
        nSetStencilOpStencilFail(mNativeObject, op, face);
    }
    private static native void nSetStencilOpStencilFail(long nativeObject, int op, int face);

    public void setStencilOpDepthFail(int op, int face) {
        nSetStencilOpDepthFail(mNativeObject, op, face);
    }
    private static native void nSetStencilOpDepthFail(long nativeObject, int op, int face);

    public void setStencilOpDepthStencilPass(int op, int face) {
        nSetStencilOpDepthStencilPass(mNativeObject, op, face);
    }
    private static native void nSetStencilOpDepthStencilPass(long nativeObject, int op, int face);

    public void setStencilReferenceValue(byte value, int face) {
        nSetStencilReferenceValue(mNativeObject, value, face);
    }
    private static native void nSetStencilReferenceValue(long nativeObject, byte value, int face);

    public void setStencilReadMask(byte readMask, int face) {
        nSetStencilReadMask(mNativeObject, readMask, face);
    }
    private static native void nSetStencilReadMask(long nativeObject, byte readMask, int face);

    public void setStencilWriteMask(byte writeMask, int face) {
        nSetStencilWriteMask(mNativeObject, writeMask, face);
    }
    private static native void nSetStencilWriteMask(long nativeObject, byte writeMask, int face);

    public void commit(long engine) {
        nCommit(mNativeObject, engine);
    }
    private static native void nCommit(long nativeObject, long engine);
}
