// This file has been generated by beamsplitter
package com.google.android.filament;

public class MultiSampleAntiAliasingOptions_generated {
    public boolean enabled = false;
    public byte sampleCount = (byte) 4;
    public boolean customResolve = false;
}
