// This file has been generated by beamsplitter
package com.google.android.filament;

public class NameComponentManager_generated {
    private final long mNativeObject;

    public NameComponentManager_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static NameComponentManager_generated create(long em) {
        return new NameComponentManager_generated(nCreate(em));
    }
    private static native long nCreate(long em);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public int getInstance(int e) {
        return nGetInstance(mNativeObject, e);
    }
    private static native int nGetInstance(long nativeObject, int e);

    public void addComponent(int e) {
        nAddComponent(mNativeObject, e);
    }
    private static native void nAddComponent(long nativeObject, int e);

    public void removeComponent(int e) {
        nRemoveComponent(mNativeObject, e);
    }
    private static native void nRemoveComponent(long nativeObject, int e);

    public void destroyComponents(long entities, long count) {
        nDestroyComponents(mNativeObject, entities, count);
    }
    private static native void nDestroyComponents(long nativeObject, long entities, long count);

    public void destroy(int e) {
        nDestroy(mNativeObject, e);
    }
    private static native void nDestroy(long nativeObject, int e);

    public void setName(int instance, String name) {
        nSetName(mNativeObject, instance, name);
    }
    private static native void nSetName(long nativeObject, int instance, String name);

    public String getName(int instance) {
        return nGetName(mNativeObject, instance);
    }
    private static native String nGetName(long nativeObject, int instance);

    public void gc() {
        nGc(mNativeObject);
    }
    private static native void nGc(long nativeObject);
}
