// This file has been generated by beamsplitter
package com.google.android.filament;

public class PBRNeutralToneMapper_generated {
    private final long mNativeObject;

    public PBRNeutralToneMapper_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static PBRNeutralToneMapper_generated create() {
        return new PBRNeutralToneMapper_generated(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public float[] call(float[] color) {
        float[] out = new float[3];
        nCall(mNativeObject, color, out);
        return out;
    }
    private static native void nCall(long nativeObject, float[] color, float[] out);

    public boolean isOneDimensional() {
        return nIsOneDimensional(mNativeObject);
    }
    private static native boolean nIsOneDimensional(long nativeObject);

    public boolean isLDR() {
        return nIsLDR(mNativeObject);
    }
    private static native boolean nIsLDR(long nativeObject);
}
