// This file has been generated by beamsplitter
package com.google.android.filament;

public class Primaries_generated {
    public float[] r = new float[2];
    public float[] g = new float[2];
    public float[] b = new float[2];

    public boolean equals(Primaries_generated rhs) {
        return nEquals(this, rhs);
    }
    private static native boolean nEquals(Primaries_generated self, Primaries_generated rhs);
}
