// This file has been generated by beamsplitter
package com.google.android.filament;

public class RenderPassFlags_generated {
    public int clear;
    public int discardStart;
    public int discardEnd;
}
