// This file has been generated by beamsplitter
package com.google.android.filament;

public class Scene_generated {
    private final long mNativeObject;

    public Scene_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public void setSkybox(long skybox) {
        nSetSkybox(mNativeObject, skybox);
    }
    private static native void nSetSkybox(long nativeObject, long skybox);

    public long getSkybox() {
        return nGetSkybox(mNativeObject);
    }
    private static native long nGetSkybox(long nativeObject);

    public void setIndirectLight(long ibl) {
        nSetIndirectLight(mNativeObject, ibl);
    }
    private static native void nSetIndirectLight(long nativeObject, long ibl);

    public long getIndirectLight() {
        return nGetIndirectLight(mNativeObject);
    }
    private static native long nGetIndirectLight(long nativeObject);

    public void addEntity(int entity) {
        nAddEntity(mNativeObject, entity);
    }
    private static native void nAddEntity(long nativeObject, int entity);

    public void addEntities(long entities, long count) {
        nAddEntities(mNativeObject, entities, count);
    }
    private static native void nAddEntities(long nativeObject, long entities, long count);

    public void remove(int entity) {
        nRemove(mNativeObject, entity);
    }
    private static native void nRemove(long nativeObject, int entity);

    public void removeEntities(long entities, long count) {
        nRemoveEntities(mNativeObject, entities, count);
    }
    private static native void nRemoveEntities(long nativeObject, long entities, long count);

    public void removeAllEntities() {
        nRemoveAllEntities(mNativeObject);
    }
    private static native void nRemoveAllEntities(long nativeObject);

    public long getEntityCount() {
        return nGetEntityCount(mNativeObject);
    }
    private static native long nGetEntityCount(long nativeObject);

    public long getRenderableCount() {
        return nGetRenderableCount(mNativeObject);
    }
    private static native long nGetRenderableCount(long nativeObject);

    public long getLightCount() {
        return nGetLightCount(mNativeObject);
    }
    private static native long nGetLightCount(long nativeObject);

    public boolean hasEntity(int entity) {
        return nHasEntity(mNativeObject, entity);
    }
    private static native boolean nHasEntity(long nativeObject, int entity);
}
