// This file has been generated by beamsplitter
package com.google.android.filament;

public class ScreenSpaceReflectionsOptions_generated {
    public float thickness = 0.100000001f;
    public float bias = 0.00999999977f;
    public float maxDistance = 3f;
    public float stride = 2f;
    public boolean enabled = false;
}
