// This file has been generated by beamsplitter
package com.google.android.filament;

public class SkinningBuffer_generated {
    private final long mNativeObject;

    public SkinningBuffer_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public void setBones(long engine, long transforms, long count, long offset) {
        nSetBones(mNativeObject, engine, transforms, count, offset);
    }
    private static native void nSetBones(long nativeObject, long engine, long transforms, long count, long offset);

    public void setBones(long engine, float[] transforms, long count, long offset) {
        nSetBones(mNativeObject, engine, transforms, count, offset);
    }
    private static native void nSetBones(long nativeObject, long engine, float[] transforms, long count, long offset);

    public long getBoneCount() {
        return nGetBoneCount(mNativeObject);
    }
    private static native long nGetBoneCount(long nativeObject);

public static class Builder {
    private final long mNativeObject;

    public Builder(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static SkinningBuffer_generated.Builder create() {
        return new SkinningBuffer_generated.Builder(nCreate());
    }
    private static native long nCreate();

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public long boneCount(int boneCount) {
        return nBoneCount(mNativeObject, boneCount);
    }
    private static native long nBoneCount(long nativeObject, int boneCount);

    public long initialize(boolean initialize) {
        return nInitialize(mNativeObject, initialize);
    }
    private static native long nInitialize(long nativeObject, boolean initialize);

    public long name(String name, long len) {
        return nName(mNativeObject, name, len);
    }
    private static native long nName(long nativeObject, String name, long len);

    public long build(long engine) {
        return nBuild(mNativeObject, engine);
    }
    private static native long nBuild(long nativeObject, long engine);
}

}
