// This file has been generated by beamsplitter
package com.google.android.filament;

public class TemporalAntiAliasingOptions_generated {
    public float filterWidth = 1f;
    public float feedback = 0.119999997f;
    public float lodBias = -1f;
    public float sharpness = 0f;
    public boolean enabled = false;
    public float upscaling = 1f;
    public boolean filterHistory = true;
    public boolean filterInput = true;
    public boolean useYCoCg = false;
    public boolean hdr = true;
    public int boxType = 0;
    public int boxClipping = 0;
    public int jitterPattern = 3;
    public float varianceGamma = 1f;
    public boolean preventFlickering = false;
    public boolean historyReprojection = true;
}
