// This file has been generated by beamsplitter
package com.google.android.filament;

public class Viewport_generated {
    private final long mNativeObject;

    public Viewport_generated(long nativeObject) {
        mNativeObject = nativeObject;
    }

    public long getNativeObject() {
        return mNativeObject;
    }

    public static Viewport_generated create() {
        return new Viewport_generated(nCreate());
    }
    private static native long nCreate();

    public static Viewport_generated create(int left, int bottom, int width, int height) {
        return new Viewport_generated(nCreate(left, bottom, width, height));
    }
    private static native long nCreate(int left, int bottom, int width, int height);

    public void destroy() {
        nDestroy(mNativeObject);
    }
    private static native void nDestroy(long nativeObject);

    public boolean empty() {
        return nEmpty(mNativeObject);
    }
    private static native boolean nEmpty(long nativeObject);
}
